AppAirBnB: UTN.Winform.AppAirBnB.Layers.Entities.Tarjeta Class Reference
UTN.Winform.AppAirBnB.Layers.Entities.Tarjeta Class Reference
Public Member Functions
override string ToString ()
Properties
int ID [get, set]
string Tipo [get, set]
Detailed Description
Definition at line 9 of file Tarjeta.cs.
Member Function Documentation
ToString()
override string UTN.Winform.AppAirBnB.Layers.Entities.Tarjeta.ToString ()
Referenced by UTN.Winform.AppAirBnB.Layers.UI.Procesos.frmFacturacion.btnAgregar_Click(), UTN.Winform.AppAirBnB.Layers.DAL.DALEncFactura.GetFactura(), and UTN.Winform.AppAirBnB.Layers.UI.Procesos.frmFacturacion.toolStripBtnFacturar_Click().
Property Documentation
ID
int UTN.Winform.AppAirBnB.Layers.Entities.Tarjeta.ID get set
Definition at line 12 of file Tarjeta.cs.
Referenced by UTN.Winform.AppAirBnB.Layers.DAL.DALTarjeta.GetTarjetaById(), and UTN.Winform.AppAirBnB.Layers.DAL.DALEncFactura.SaveFactura().
 { get; set; }
Tipo
string UTN.Winform.AppAirBnB.Layers.Entities.Tarjeta.Tipo get set
Definition at line 13 of file Tarjeta.cs.
Referenced by UTN.Winform.AppAirBnB.Layers.DAL.DALTarjeta.GetTarjetaById().
 { get; set; }
The documentation for this class was generated from the following file:
C:/Users/JorgeMario/Desktop/Proyecto Programado Cuatrimestre I 2018 v4/AppAirBnB/AppAirBnB/Layers/Entities/Tarjeta.cs