appExamen1Sismos: UTN.Winform.Examen1.Sismos.Gestores.Gestor Class Reference
UTN.Winform.Examen1.Sismos.Gestores.Gestor Class Reference
Public Member Functions
void AgregarSismo (Sismo pSismo)
void AsignarInstitucion (IInstitucion pInstitucion)
List< Respuesta > ObtenerCalculos ()
string ObtenerXML ()
double TotalMagnitudes ()
Este metodo nos permite obtener un total de todas las magnitudes Ritchter
Private Attributes
IEvento _Evento = new Evento()
IInstitucion _Institucion = new Institucion()
Detailed Description
Definition at line 11 of file Gestor.cs.
Member Function Documentation
AgregarSismo()
void UTN.Winform.Examen1.Sismos.Gestores.Gestor.AgregarSismo (Sismo pSismo)
Implements UTN.Winform.Examen1.Sismos.Interfaces.IGestor.
Definition at line 17 of file Gestor.cs.
References UTN.Winform.Examen1.Sismos.Interfaces.IEvento.AgregarSismo().
         {
             _Evento.AgregarSismo(pSismo);
         }
AsignarInstitucion()
void UTN.Winform.Examen1.Sismos.Gestores.Gestor.AsignarInstitucion (IInstitucion pInstitucion)
Implements UTN.Winform.Examen1.Sismos.Interfaces.IGestor.
Definition at line 24 of file Gestor.cs.
References UTN.Winform.Examen1.Sismos.Interfaces.IEvento.AsignarInstitucion().
         {
             _Evento.AsignarInstitucion(pInstitucion);
         }
ObtenerCalculos()
List<Respuesta> UTN.Winform.Examen1.Sismos.Gestores.Gestor.ObtenerCalculos ()
Implements UTN.Winform.Examen1.Sismos.Interfaces.IGestor.
Definition at line 30 of file Gestor.cs.
References UTN.Winform.Examen1.Sismos.Interfaces.IEvento.ObtenerCalculos().
         {
             return _Evento.ObtenerCalculos();
         }
ObtenerXML()
string UTN.Winform.Examen1.Sismos.Gestores.Gestor.ObtenerXML ()
Implements UTN.Winform.Examen1.Sismos.Interfaces.IGestor.
Definition at line 38 of file Gestor.cs.
References UTN.Winform.Examen1.Sismos.Interfaces.IEvento.ObtenerXML().
         {
             return _Evento.ObtenerXML();
         }
TotalMagnitudes()
double UTN.Winform.Examen1.Sismos.Gestores.Gestor.TotalMagnitudes ()
Este metodo nos permite obtener un total de todas las magnitudes Ritchter
Returns
Implements UTN.Winform.Examen1.Sismos.Interfaces.IGestor.
Definition at line 50 of file Gestor.cs.
         {
             double parcial = 0;
             foreach (var item in ObtenerCalculos())
             {
                 parcial += item.MagnitudEscalaRitchter;
             }
             return parcial;
         }
Member Data Documentation
_Evento
IEvento UTN.Winform.Examen1.Sismos.Gestores.Gestor._Evento = new Evento() private
Definition at line 13 of file Gestor.cs.
_Institucion
IInstitucion UTN.Winform.Examen1.Sismos.Gestores.Gestor._Institucion = new Institucion() private
Definition at line 15 of file Gestor.cs.
The documentation for this class was generated from the following file:
C:/Users/JorgeMario/Documents/Visual Studio 2015/Projects/appExamen1Sismo/appExamen1Sismo/Gestores/Gestor.cs