appExamen1Sismos: UTN.Winform.Examen1.Sismos.UI.frmPrincipal Class Reference
UTN.Winform.Examen1.Sismos.UI.frmPrincipal Class Reference
Public Member Functions
frmPrincipal ()
Protected Member Functions
override void Dispose (bool disposing)
Clean up any resources being used.
Private Member Functions
void splitContainer2_SplitterMoved (object sender, SplitterEventArgs e)
void tspbtnSalir_Click (object sender, EventArgs e)
void frmPrincipal_Load (object sender, EventArgs e)
Se usa para asignar Culturizacion , nombre de ventana y se llama al metodo que llena el dgv
void CargarArchivoJSON ()
Realiza el recorrido de la listaJSON y asigna el nombre de la Institucion
void tspbtnEjecutar_Click (object sender, EventArgs e)
a. Leer el archivo Json nuevamente por medio de la clase DatosJSON. b.Extrae la Institución lo asigna a Evento por medio del Gestor c.Iterar la lista List<DatosJSON> y determinar si: i.El tipo de Tipo (Volcanico, Tectonico, Falla) y crear un objeto Sismo por medio del Factory ii.Asigna los properties respectivos al Objeto Sismo especializado y lo agrega a Evento por medio del Gestor.
void tspbtnNuevo_Click (object sender, EventArgs e)
Se encarga de limpiar cada objeto en ventana
void InitializeComponent ()
Required method for Designer support - do not modify the contents of this method with the code editor.
Private Attributes
IGestor _Gestor = new Gestor()
IGestor oGestor = new Gestor()
System.ComponentModel.IContainer components = null
Required designer variable.
System.Windows.Forms.StatusStrip statusStrip1
System.Windows.Forms.ToolStripStatusLabel toolStripStatusLabel1
System.Windows.Forms.Timer timer1
System.Windows.Forms.ToolStrip toolStrip1
System.Windows.Forms.ToolStripButton tspbtnNuevo
System.Windows.Forms.ToolStripButton tspbtnEjecutar
System.Windows.Forms.ToolStripButton tspbtnSalir
System.Windows.Forms.SplitContainer splitContainer1
System.Windows.Forms.DataGridView dgvInicial
System.Windows.Forms.SplitContainer splitContainer2
System.Windows.Forms.WebBrowser wbMostrar
System.Windows.Forms.DataGridView dgvResultados
Static Private Attributes
static readonly log4net.ILog _MyLogControlEventos
Detailed Description
Definition at line 22 of file frmPrincipal.cs.
Constructor & Destructor Documentation
frmPrincipal()
UTN.Winform.Examen1.Sismos.UI.frmPrincipal.frmPrincipal ()
Definition at line 24 of file frmPrincipal.cs.
         {
             InitializeComponent();
         }
Member Function Documentation
CargarArchivoJSON()
void UTN.Winform.Examen1.Sismos.UI.frmPrincipal.CargarArchivoJSON () private
Realiza el recorrido de la listaJSON y asigna el nombre de la Institucion
Definition at line 93 of file frmPrincipal.cs.
References UTN.Winform.Examen1.Sismos.Interfaces.IGestor.AgregarSismo(), UTN.Winform.Examen1.Sismos.Clases.Sismo.AmplitudHonda, UTN.Winform.Examen1.Sismos.Factory.FactorySismo.CrearSismo(), UTN.Winform.Examen1.Sismos.Clases.Sismo.FechaFinal, UTN.Winform.Examen1.Sismos.Clases.Sismo.FechaInicial, UTN.Winform.Examen1.Sismos.Util.JSONGenericObject< T >.JSonToObject(), and UTN.Winform.Examen1.Sismos.JsonData.DatosJSON.Lista.
         {
             string datos = "";
             dgvInicial.AutoGenerateColumns = true;
             datos = File.ReadAllText(@"C:\temp\datos.json");
             DatosJSON oDatosJSON = JSONGenericObject<DatosJSON>.JSonToObject(datos);
             // Llena el DataGridView
             dgvInicial.DataSource = oDatosJSON.Lista;
             // Recorrer lista
             foreach (var item in oDatosJSON.Lista)
             {
                 Sismo oSismo = null;
                 if (item.Tipo.Equals("falla",
                     StringComparison.CurrentCultureIgnoreCase))
                 {
                     oSismo = FactorySismo.CrearSismo(TipoSismo.Falla);
                     oSismo.AmplitudHonda = item.AmplitudHonda;
                     oSismo.FechaInicial = item.FechaInicial;
                     oSismo.FechaFinal = item.FechaFinal;
                 }
                 if (item.Tipo.Equals("Volcanico",
                     StringComparison.CurrentCultureIgnoreCase))
                 {
                     oSismo = FactorySismo.CrearSismo(TipoSismo.Volcanico);
                     //_resp.TipoSismo = "Volcanico";
                     oSismo.AmplitudHonda = item.AmplitudHonda;
                     oSismo.FechaInicial = item.FechaInicial;
                     oSismo.FechaFinal = item.FechaFinal;
                 }
                 if (item.Tipo.Equals("Tectonico",
                    StringComparison.CurrentCultureIgnoreCase))
                 {
                     oSismo = FactorySismo.CrearSismo(TipoSismo.Tectonico);
                     // _resp.TipoSismo = "Tectonico";
                     oSismo.AmplitudHonda = item.AmplitudHonda;
                     oSismo.FechaInicial = item.FechaInicial;
                     oSismo.FechaFinal = item.FechaFinal;
                 }
                 _Gestor.AgregarSismo(oSismo);
             }
         }
Dispose()
override void UTN.Winform.Examen1.Sismos.UI.frmPrincipal.Dispose (bool disposing) protected
Clean up any resources being used.
Parameters
disposing true if managed resources should be disposed; otherwise, false.
Definition at line 14 of file frmPrincipal.Designer.cs.
         {
             if (disposing && (components != null))
             {
                 components.Dispose();
             }
             base.Dispose(disposing);
         }
frmPrincipal_Load()
void UTN.Winform.Examen1.Sismos.UI.frmPrincipal.frmPrincipal_Load (object sender, EventArgs e) private
Se usa para asignar Culturizacion , nombre de ventana y se llama al metodo que llena el dgv
Parameters
sender
e
Definition at line 56 of file frmPrincipal.cs.
References UTN.Winform.Examen1.Sismos.Util.Utilitarios.CulturaInfo().
         {
             try
             {
                 Text = Application.ProductName;
                 Utilitarios.CulturaInfo();
                 CargarArchivoJSON();
                 _MyLogControlEventos.Info("El usuario se ha loggeado");
             }
             catch (Exception error)
             {
                 StringBuilder msg = new StringBuilder();
                 msg.AppendFormat("Error        \n");
                 msg.AppendFormat("Mensaje        : {0}\n", error.Message);
                 msg.AppendFormat("Data           : {0}\n", error.Data);
                 msg.AppendFormat("InnerException : {0}\n", error.InnerException);
                 msg.AppendFormat("Source         : {0}\n", error.Source);
                 msg.AppendFormat("StackTrace     : {0}\n", error.StackTrace);
                 msg.AppendFormat("TargetSite     : {0}\n", error.TargetSite);
                 //msg.AppendFormat("Close QUery    : {0}\n", error.)
                 _MyLogControlEventos.Error(msg.ToString());
                 MessageBox.Show(msg.ToString(), "Error");
             }
         }
InitializeComponent()
void UTN.Winform.Examen1.Sismos.UI.frmPrincipal.InitializeComponent () private
Required method for Designer support - do not modify the contents of this method with the code editor.
Definition at line 29 of file frmPrincipal.Designer.cs.
         {
             this.components = new System.ComponentModel.Container();
             this.statusStrip1 = new System.Windows.Forms.StatusStrip();
             this.toolStripStatusLabel1 = new System.Windows.Forms.ToolStripStatusLabel();
             this.timer1 = new System.Windows.Forms.Timer(this.components);
             this.toolStrip1 = new System.Windows.Forms.ToolStrip();
             this.tspbtnNuevo = new System.Windows.Forms.ToolStripButton();
             this.tspbtnEjecutar = new System.Windows.Forms.ToolStripButton();
             this.tspbtnSalir = new System.Windows.Forms.ToolStripButton();
             this.splitContainer1 = new System.Windows.Forms.SplitContainer();
             this.dgvInicial = new System.Windows.Forms.DataGridView();
             this.splitContainer2 = new System.Windows.Forms.SplitContainer();
             this.wbMostrar = new System.Windows.Forms.WebBrowser();
             this.dgvResultados = new System.Windows.Forms.DataGridView();
             this.statusStrip1.SuspendLayout();
             this.toolStrip1.SuspendLayout();
             ((System.ComponentModel.ISupportInitialize)(this.splitContainer1)).BeginInit();
             this.splitContainer1.Panel1.SuspendLayout();
             this.splitContainer1.Panel2.SuspendLayout();
             this.splitContainer1.SuspendLayout();
             ((System.ComponentModel.ISupportInitialize)(this.dgvInicial)).BeginInit();
             ((System.ComponentModel.ISupportInitialize)(this.splitContainer2)).BeginInit();
             this.splitContainer2.Panel1.SuspendLayout();
             this.splitContainer2.Panel2.SuspendLayout();
             this.splitContainer2.SuspendLayout();
             ((System.ComponentModel.ISupportInitialize)(this.dgvResultados)).BeginInit();
             this.SuspendLayout();
             //
             // statusStrip1
             //
             this.statusStrip1.Items.AddRange(new System.Windows.Forms.ToolStripItem[] {
             this.toolStripStatusLabel1});
             this.statusStrip1.Location = new System.Drawing.Point(0, 411);
             this.statusStrip1.Name = "statusStrip1";
             this.statusStrip1.Size = new System.Drawing.Size(765, 22);
             this.statusStrip1.TabIndex = 0;
             this.statusStrip1.Text = "statusStrip1";
             //
             // toolStripStatusLabel1
             //
             this.toolStripStatusLabel1.Name = "toolStripStatusLabel1";
             this.toolStripStatusLabel1.Size = new System.Drawing.Size(118, 17);
             this.toolStripStatusLabel1.Text = "toolStripStatusLabel1";
             //
             // toolStrip1
             //
             this.toolStrip1.AutoSize = false;
             this.toolStrip1.Items.AddRange(new System.Windows.Forms.ToolStripItem[] {
             this.tspbtnNuevo,
             this.tspbtnEjecutar,
             this.tspbtnSalir});
             this.toolStrip1.Location = new System.Drawing.Point(0, 0);
             this.toolStrip1.Name = "toolStrip1";
             this.toolStrip1.Size = new System.Drawing.Size(765, 66);
             this.toolStrip1.TabIndex = 1;
             this.toolStrip1.Text = "toolStrip1";
             //
             // tspbtnNuevo
             //
             this.tspbtnNuevo.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Center;
             this.tspbtnNuevo.Image = global::UTN.Winform.Examen1.Sismos.Properties.Resources.edit;
             this.tspbtnNuevo.ImageTransparentColor = System.Drawing.Color.Magenta;
             this.tspbtnNuevo.Name = "tspbtnNuevo";
             this.tspbtnNuevo.Size = new System.Drawing.Size(62, 63);
             this.tspbtnNuevo.Text = "Nuevo";
             this.tspbtnNuevo.Click += new System.EventHandler(this.tspbtnNuevo_Click);
             //
             // tspbtnEjecutar
             //
             this.tspbtnEjecutar.Image = global::UTN.Winform.Examen1.Sismos.Properties.Resources.logout;
             this.tspbtnEjecutar.ImageTransparentColor = System.Drawing.Color.Magenta;
             this.tspbtnEjecutar.Name = "tspbtnEjecutar";
             this.tspbtnEjecutar.Size = new System.Drawing.Size(69, 63);
             this.tspbtnEjecutar.Text = "Ejecutar";
             this.tspbtnEjecutar.Click += new System.EventHandler(this.tspbtnEjecutar_Click);
             //
             // tspbtnSalir
             //
             this.tspbtnSalir.Image = global::UTN.Winform.Examen1.Sismos.Properties.Resources._1_0OtJcqai2F72zJyTrqtLIA;
             this.tspbtnSalir.ImageTransparentColor = System.Drawing.Color.Magenta;
             this.tspbtnSalir.Name = "tspbtnSalir";
             this.tspbtnSalir.Size = new System.Drawing.Size(49, 63);
             this.tspbtnSalir.Text = "Salir";
             this.tspbtnSalir.Click += new System.EventHandler(this.tspbtnSalir_Click);
             //
             // splitContainer1
             //
             this.splitContainer1.Dock = System.Windows.Forms.DockStyle.Fill;
             this.splitContainer1.Location = new System.Drawing.Point(0, 66);
             this.splitContainer1.Name = "splitContainer1";
             //
             // splitContainer1.Panel1
             //
             this.splitContainer1.Panel1.Controls.Add(this.dgvInicial);
             //
             // splitContainer1.Panel2
             //
             this.splitContainer1.Panel2.Controls.Add(this.splitContainer2);
             this.splitContainer1.Size = new System.Drawing.Size(765, 345);
             this.splitContainer1.SplitterDistance = 335;
             this.splitContainer1.TabIndex = 2;
             //
             // dgvInicial
             //
             this.dgvInicial.AllowUserToAddRows = false;
             this.dgvInicial.ColumnHeadersHeightSizeMode = System.Windows.Forms.DataGridViewColumnHeadersHeightSizeMode.AutoSize;
             this.dgvInicial.Dock = System.Windows.Forms.DockStyle.Fill;
             this.dgvInicial.Location = new System.Drawing.Point(0, 0);
             this.dgvInicial.Name = "dgvInicial";
             this.dgvInicial.Size = new System.Drawing.Size(335, 345);
             this.dgvInicial.TabIndex = 0;
             //
             // splitContainer2
             //
             this.splitContainer2.BorderStyle = System.Windows.Forms.BorderStyle.Fixed3D;
             this.splitContainer2.Dock = System.Windows.Forms.DockStyle.Fill;
             this.splitContainer2.Location = new System.Drawing.Point(0, 0);
             this.splitContainer2.Name = "splitContainer2";
             this.splitContainer2.Orientation = System.Windows.Forms.Orientation.Horizontal;
             //
             // splitContainer2.Panel1
             //
             this.splitContainer2.Panel1.Controls.Add(this.wbMostrar);
             //
             // splitContainer2.Panel2
             //
             this.splitContainer2.Panel2.Controls.Add(this.dgvResultados);
             this.splitContainer2.Size = new System.Drawing.Size(426, 345);
             this.splitContainer2.SplitterDistance = 233;
             this.splitContainer2.TabIndex = 0;
             this.splitContainer2.SplitterMoved += new System.Windows.Forms.SplitterEventHandler(this.splitContainer2_SplitterMoved);
             //
             // wbMostrar
             //
             this.wbMostrar.Dock = System.Windows.Forms.DockStyle.Fill;
             this.wbMostrar.Location = new System.Drawing.Point(0, 0);
             this.wbMostrar.MinimumSize = new System.Drawing.Size(20, 20);
             this.wbMostrar.Name = "wbMostrar";
             this.wbMostrar.Size = new System.Drawing.Size(422, 229);
             this.wbMostrar.TabIndex = 0;
             //
             // dgvResultados
             //
             this.dgvResultados.AllowUserToAddRows = false;
             this.dgvResultados.ColumnHeadersHeightSizeMode = System.Windows.Forms.DataGridViewColumnHeadersHeightSizeMode.AutoSize;
             this.dgvResultados.Dock = System.Windows.Forms.DockStyle.Fill;
             this.dgvResultados.Location = new System.Drawing.Point(0, 0);
             this.dgvResultados.Name = "dgvResultados";
             this.dgvResultados.Size = new System.Drawing.Size(422, 104);
             this.dgvResultados.TabIndex = 0;
             //
             // frmPrincipal
             //
             this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
             this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
             this.ClientSize = new System.Drawing.Size(765, 433);
             this.Controls.Add(this.splitContainer1);
             this.Controls.Add(this.toolStrip1);
             this.Controls.Add(this.statusStrip1);
             this.Name = "frmPrincipal";
             this.StartPosition = System.Windows.Forms.FormStartPosition.CenterParent;
             this.Text = "frmPrincipal";
             this.WindowState = System.Windows.Forms.FormWindowState.Maximized;
             this.Load += new System.EventHandler(this.frmPrincipal_Load);
             this.statusStrip1.ResumeLayout(false);
             this.statusStrip1.PerformLayout();
             this.toolStrip1.ResumeLayout(false);
             this.toolStrip1.PerformLayout();
             this.splitContainer1.Panel1.ResumeLayout(false);
             this.splitContainer1.Panel2.ResumeLayout(false);
             ((System.ComponentModel.ISupportInitialize)(this.splitContainer1)).EndInit();
             this.splitContainer1.ResumeLayout(false);
             ((System.ComponentModel.ISupportInitialize)(this.dgvInicial)).EndInit();
             this.splitContainer2.Panel1.ResumeLayout(false);
             this.splitContainer2.Panel2.ResumeLayout(false);
             ((System.ComponentModel.ISupportInitialize)(this.splitContainer2)).EndInit();
             this.splitContainer2.ResumeLayout(false);
             ((System.ComponentModel.ISupportInitialize)(this.dgvResultados)).EndInit();
             this.ResumeLayout(false);
             this.PerformLayout();
         }
splitContainer2_SplitterMoved()
void UTN.Winform.Examen1.Sismos.UI.frmPrincipal.splitContainer2_SplitterMoved (object sender, SplitterEventArgs e) private
Definition at line 37 of file frmPrincipal.cs.
         {
         }
tspbtnEjecutar_Click()
void UTN.Winform.Examen1.Sismos.UI.frmPrincipal.tspbtnEjecutar_Click (object sender, EventArgs e) private
a. Leer el archivo Json nuevamente por medio de la clase DatosJSON. b.Extrae la Institución lo asigna a Evento por medio del Gestor c.Iterar la lista List<DatosJSON> y determinar si: i.El tipo de Tipo (Volcanico, Tectonico, Falla) y crear un objeto Sismo por medio del Factory ii.Asigna los properties respectivos al Objeto Sismo especializado y lo agrega a Evento por medio del Gestor.
Parameters
sender
e
Definition at line 159 of file frmPrincipal.cs.
References UTN.Winform.Examen1.Sismos.Interfaces.IGestor.AgregarSismo(), UTN.Winform.Examen1.Sismos.Clases.Sismo.AmplitudHonda, UTN.Winform.Examen1.Sismos.Interfaces.IGestor.AsignarInstitucion(), UTN.Winform.Examen1.Sismos.Factory.FactorySismo.CrearSismo(), UTN.Winform.Examen1.Sismos.Clases.Sismo.FechaFinal, UTN.Winform.Examen1.Sismos.Clases.Sismo.FechaInicial, UTN.Winform.Examen1.Sismos.JsonData.DatosJSON.Institucion, UTN.Winform.Examen1.Sismos.Util.JSONGenericObject< T >.JSonToObject(), UTN.Winform.Examen1.Sismos.Interfaces.IInstitucion.Nombre, UTN.Winform.Examen1.Sismos.Interfaces.IGestor.ObtenerCalculos(), UTN.Winform.Examen1.Sismos.Interfaces.IGestor.ObtenerXML(), and UTN.Winform.Examen1.Sismos.Interfaces.IGestor.TotalMagnitudes().
         {
             string datos = "";
             string xml = "";
             IInstitucion pInstitucion;
             pInstitucion = new Institucion();
             datos = File.ReadAllText(@"C:\temp\datos.json");
             DatosJSON oDatosJSON = JSONGenericObject<DatosJSON>.JSonToObject(datos);
             // Llena el DataGridView
             //dgvInicial.DataSource = oDatosJSON.Lista;
             pInstitucion.Nombre = oDatosJSON.Institucion;
             _Gestor.AsignarInstitucion(pInstitucion);
             foreach (var item in oDatosJSON.Lista)
             {
                 Sismo _Sismo = null;
                 if (item.Tipo.Equals("falla",
                     StringComparison.CurrentCultureIgnoreCase))
                 {
                     _Sismo = FactorySismo.CrearSismo(TipoSismo.Falla);
                     _Sismo.AmplitudHonda = item.AmplitudHonda;
                     _Sismo.FechaInicial = item.FechaInicial;
                     _Sismo.FechaFinal = item.FechaFinal;
                 }
                 if (item.Tipo.Equals("Volcanico",
                     StringComparison.CurrentCultureIgnoreCase))
                 {
                     _Sismo = FactorySismo.CrearSismo(TipoSismo.Volcanico);
                     //item.Tipo = oSismo.GetType().ToString();
                     _Sismo.AmplitudHonda = item.AmplitudHonda;
                     _Sismo.FechaInicial = item.FechaInicial;
                     _Sismo.FechaFinal = item.FechaFinal;
                 }
                 if (item.Tipo.Equals("Tectonico",
                    StringComparison.CurrentCultureIgnoreCase))
                 {
                     _Sismo = FactorySismo.CrearSismo(TipoSismo.Tectonico);
                     // item.Tipo = oSismo.GetType().ToString();
                     _Sismo.AmplitudHonda = item.AmplitudHonda;
                     _Sismo.FechaInicial = item.FechaInicial;
                     _Sismo.FechaFinal = item.FechaFinal;
                 }
                 oGestor.AgregarSismo(_Sismo);
             }
             toolStripStatusLabel1.Text = ("Total de Magnitudes :   ") + oGestor.TotalMagnitudes().ToString();
             dgvResultados.AutoGenerateColumns = true;
             dgvResultados.DataSource = oGestor.ObtenerCalculos();
             xml = _Gestor.ObtenerXML();
             if (!Directory.Exists(@"c:\temp\"))
                 Directory.CreateDirectory(@"c:\temp\");
             File.WriteAllText(@"c:\temp\examensismos.xml", xml);
             File.Copy(@"..\..\XSLT\examensismos.xslt", @"c:\temp\examensismos.xslt", true);
             wbMostrar.Url = new Uri(@"c:\temp\examensismos.xml");
         }
tspbtnNuevo_Click()
void UTN.Winform.Examen1.Sismos.UI.frmPrincipal.tspbtnNuevo_Click (object sender, EventArgs e) private
Se encarga de limpiar cada objeto en ventana
Parameters
sender
e
Definition at line 254 of file frmPrincipal.cs.
         {
             dgvInicial.DataSource = null;
             dgvResultados.DataSource = null;
             wbMostrar.Url = null;
         }
tspbtnSalir_Click()
void UTN.Winform.Examen1.Sismos.UI.frmPrincipal.tspbtnSalir_Click (object sender, EventArgs e) private
Definition at line 42 of file frmPrincipal.cs.
         {
             Close();
         }
Member Data Documentation
_Gestor
IGestor UTN.Winform.Examen1.Sismos.UI.frmPrincipal._Gestor = new Gestor() private
Definition at line 29 of file frmPrincipal.cs.
_MyLogControlEventos
readonly log4net.ILog UTN.Winform.Examen1.Sismos.UI.frmPrincipal._MyLogControlEventos static private
Initial value:
=
                                     log4net.LogManager.GetLogger("MyControlEventos")
Definition at line 32 of file frmPrincipal.cs.
components
System.ComponentModel.IContainer UTN.Winform.Examen1.Sismos.UI.frmPrincipal.components = null private
Required designer variable.
Definition at line 8 of file frmPrincipal.Designer.cs.
dgvInicial
System.Windows.Forms.DataGridView UTN.Winform.Examen1.Sismos.UI.frmPrincipal.dgvInicial private
Definition at line 223 of file frmPrincipal.Designer.cs.
dgvResultados
System.Windows.Forms.DataGridView UTN.Winform.Examen1.Sismos.UI.frmPrincipal.dgvResultados private
Definition at line 226 of file frmPrincipal.Designer.cs.
oGestor
IGestor UTN.Winform.Examen1.Sismos.UI.frmPrincipal.oGestor = new Gestor() private
Definition at line 30 of file frmPrincipal.cs.
splitContainer1
System.Windows.Forms.SplitContainer UTN.Winform.Examen1.Sismos.UI.frmPrincipal.splitContainer1 private
Definition at line 222 of file frmPrincipal.Designer.cs.
splitContainer2
System.Windows.Forms.SplitContainer UTN.Winform.Examen1.Sismos.UI.frmPrincipal.splitContainer2 private
Definition at line 224 of file frmPrincipal.Designer.cs.
statusStrip1
System.Windows.Forms.StatusStrip UTN.Winform.Examen1.Sismos.UI.frmPrincipal.statusStrip1 private
Definition at line 215 of file frmPrincipal.Designer.cs.
timer1
System.Windows.Forms.Timer UTN.Winform.Examen1.Sismos.UI.frmPrincipal.timer1 private
Definition at line 217 of file frmPrincipal.Designer.cs.
toolStrip1
System.Windows.Forms.ToolStrip UTN.Winform.Examen1.Sismos.UI.frmPrincipal.toolStrip1 private
Definition at line 218 of file frmPrincipal.Designer.cs.
toolStripStatusLabel1
System.Windows.Forms.ToolStripStatusLabel UTN.Winform.Examen1.Sismos.UI.frmPrincipal.toolStripStatusLabel1 private
Definition at line 216 of file frmPrincipal.Designer.cs.
tspbtnEjecutar
System.Windows.Forms.ToolStripButton UTN.Winform.Examen1.Sismos.UI.frmPrincipal.tspbtnEjecutar private
Definition at line 220 of file frmPrincipal.Designer.cs.
tspbtnNuevo
System.Windows.Forms.ToolStripButton UTN.Winform.Examen1.Sismos.UI.frmPrincipal.tspbtnNuevo private
Definition at line 219 of file frmPrincipal.Designer.cs.
tspbtnSalir
System.Windows.Forms.ToolStripButton UTN.Winform.Examen1.Sismos.UI.frmPrincipal.tspbtnSalir private
Definition at line 221 of file frmPrincipal.Designer.cs.
wbMostrar
System.Windows.Forms.WebBrowser UTN.Winform.Examen1.Sismos.UI.frmPrincipal.wbMostrar private
Definition at line 225 of file frmPrincipal.Designer.cs.
The documentation for this class was generated from the following files:
C:/Users/JorgeMario/Documents/Visual Studio 2015/Projects/appExamen1Sismo/appExamen1Sismo/UI/frmPrincipal.cs
C:/Users/JorgeMario/Documents/Visual Studio 2015/Projects/appExamen1Sismo/appExamen1Sismo/UI/frmPrincipal.Designer.cs