AppAirBnB: UTN.Winform.AppAirBnB.Layers.BLL.BLLHabitacion Class Reference
UTN.Winform.AppAirBnB.Layers.BLL.BLLHabitacion Class Reference
Public Member Functions
bool DeleteHabitacion (double pId)
List< HabitacionDTO > GetAllHabitacion ()
Habitacion GetHabitacionById (double pId)
Habitacion SaveHabitacion (Habitacion pHabitacion)
Habitacion UpdateHabitacion (Habitacion pHabitacion)
Detailed Description
Definition at line 13 of file BLLHabitacion.cs.
Member Function Documentation
DeleteHabitacion()
bool UTN.Winform.AppAirBnB.Layers.BLL.BLLHabitacion.DeleteHabitacion (double pId)
Implements UTN.Winform.AppAirBnB.Layers.Interface.IBLLHabitacion.
Definition at line 15 of file BLLHabitacion.cs.
References UTN.Winform.AppAirBnB.Layers.Interface.IDALHabitacion.DeleteHabitacion().
         {
             IDALHabitacion _IDALHabitacion = new DALHabitacion();
             return _IDALHabitacion.DeleteHabitacion(pId);
         }
GetAllHabitacion()
List<HabitacionDTO> UTN.Winform.AppAirBnB.Layers.BLL.BLLHabitacion.GetAllHabitacion ()
Implements UTN.Winform.AppAirBnB.Layers.Interface.IBLLHabitacion.
Definition at line 21 of file BLLHabitacion.cs.
References UTN.Winform.AppAirBnB.Layers.Interface.IDALHabitacion.GetAllHabitacion().
         {
             IDALHabitacion _IDALHabitacion = new DALHabitacion();
             return _IDALHabitacion.GetAllHabitacion();
         }
GetHabitacionById()
Habitacion UTN.Winform.AppAirBnB.Layers.BLL.BLLHabitacion.GetHabitacionById (double pId)
Implements UTN.Winform.AppAirBnB.Layers.Interface.IBLLHabitacion.
Definition at line 27 of file BLLHabitacion.cs.
References UTN.Winform.AppAirBnB.Layers.Interface.IDALHabitacion.GetHabitacionById().
         {
             IDALHabitacion _IDALHabitacion = new DALHabitacion();
             return _IDALHabitacion.GetHabitacionById(pId);
         }
SaveHabitacion()
Habitacion UTN.Winform.AppAirBnB.Layers.BLL.BLLHabitacion.SaveHabitacion (Habitacion pHabitacion)
Implements UTN.Winform.AppAirBnB.Layers.Interface.IBLLHabitacion.
Definition at line 34 of file BLLHabitacion.cs.
References UTN.Winform.AppAirBnB.Layers.Interface.IDALHabitacion.GetHabitacionById(), UTN.Winform.AppAirBnB.Layers.Entities.Habitacion.NUM, UTN.Winform.AppAirBnB.Layers.Interface.IDALHabitacion.SaveHabitacion(), and UTN.Winform.AppAirBnB.Layers.Interface.IDALHabitacion.UpdateHabitacion().
         {
             IDALHabitacion _IDALHabitacion = new DALHabitacion();
             Habitacion oHabitacion = null;
             if (_IDALHabitacion.GetHabitacionById(pHabitacion.NUM) == null)
                 oHabitacion = _IDALHabitacion.SaveHabitacion(pHabitacion);
             else
                 oHabitacion = _IDALHabitacion.UpdateHabitacion(pHabitacion);
             return oHabitacion;
         }
UpdateHabitacion()
Habitacion UTN.Winform.AppAirBnB.Layers.BLL.BLLHabitacion.UpdateHabitacion (Habitacion pHabitacion)
Implements UTN.Winform.AppAirBnB.Layers.Interface.IBLLHabitacion.
Definition at line 46 of file BLLHabitacion.cs.
         {
             throw new NotImplementedException();
         }
The documentation for this class was generated from the following file:
C:/Users/JorgeMario/Desktop/Proyecto Programado Cuatrimestre I 2018 v4/AppAirBnB/AppAirBnB/Layers/BLL/BLLHabitacion.cs