AppAirBnB: UTN.Winform.AppAirBnB.Layers.UI.Procesos.frmReservacion Class Reference
UTN.Winform.AppAirBnB.Layers.UI.Procesos.frmReservacion Class Reference
Public Member Functions
frmReservacion ()
Protected Member Functions
override void Dispose (bool disposing)
Clean up any resources being used.
Private Member Functions
void toolStripBtnNuevo_Click (object sender, EventArgs e)
void CargarDatos ()
void frmReservacion_Load (object sender, EventArgs e)
void toolStripBtnReservar_Click (object sender, EventArgs e)
void toolStripBtnSalir_Click (object sender, EventArgs e)
void toolStripButton1_Click (object sender, EventArgs e)
void btnBuscarHuesped_Click (object sender, EventArgs e)
void btnBuscarProducto_Click (object sender, EventArgs e)
void InitializeComponent ()
Required method for Designer support - do not modify the contents of this method with the code editor.
Private Attributes
Huesped _Huesped = null
Reservacion _Reservacion = null
object cmbTarjeta
System.ComponentModel.IContainer components = null
Required designer variable.
System.Windows.Forms.ToolStrip tspBarraSuperior
System.Windows.Forms.ToolStripButton toolStripBtnNuevo
System.Windows.Forms.ToolStripButton toolStripBtnReservar
System.Windows.Forms.ToolStripButton toolStripBtnSalir
System.Windows.Forms.StatusStrip sttBarraInferior
System.Windows.Forms.TableLayoutPanel tableLayoutPanel3
System.Windows.Forms.Label lblCantidad
System.Windows.Forms.Button btnBuscarProducto
System.Windows.Forms.Label label5
System.Windows.Forms.GroupBox groupBox1
System.Windows.Forms.TableLayoutPanel tlpAgrupamiento
System.Windows.Forms.Label label3
System.Windows.Forms.TextBox txtHuespedId
System.Windows.Forms.Button btnBuscarHuesped
System.Windows.Forms.Label label11
System.Windows.Forms.DataGridView dgvDetalleReserva
System.Windows.Forms.GroupBox groupBox2
System.Windows.Forms.MaskedTextBox mskCantidad
System.Windows.Forms.MaskedTextBox mskNUMHabitacion
System.Windows.Forms.Label label1
System.Windows.Forms.DateTimePicker dtpCheckIN
System.Windows.Forms.Label label2
System.Windows.Forms.DateTimePicker dtpCheckOut
System.Windows.Forms.TextBox txtNumeroReservacion
System.Windows.Forms.ToolStripStatusLabel toolStripStatusLabel1
System.Windows.Forms.TextBox txtSub
System.Windows.Forms.Label label4
System.Windows.Forms.ToolStripButton toolStripButton1
Static Private Attributes
static readonly ILog _MyLogControlEventos = log4net.LogManager.GetLogger("MyControlEventos")
Detailed Description
Definition at line 19 of file frmReservacion.cs.
Constructor & Destructor Documentation
frmReservacion()
UTN.Winform.AppAirBnB.Layers.UI.Procesos.frmReservacion.frmReservacion ()
Definition at line 26 of file frmReservacion.cs.
         {
             InitializeComponent();
         }
Member Function Documentation
btnBuscarHuesped_Click()
void UTN.Winform.AppAirBnB.Layers.UI.Procesos.frmReservacion.btnBuscarHuesped_Click (object sender, EventArgs e) private
Definition at line 275 of file frmReservacion.cs.
References UTN.Winform.AppAirBnB.Layers.UI.Filtros.frmFiltroHuesped._Huesped, and UTN.Winform.AppAirBnB.Layers.Entities.Huesped.ID.
         {
             frmFiltroHuesped ofrmFiltroHuesped = new frmFiltroHuesped();
             Huesped oHuesped = null;
             try
             {
                 ofrmFiltroHuesped.ShowDialog();
                 if (ofrmFiltroHuesped.DialogResult == DialogResult.OK)
                 {
                     oHuesped = ofrmFiltroHuesped._Huesped;
                     this.txtHuespedId.Text = oHuesped.ID.ToString();
                 }
             }
             catch (Exception er)
             {
                 StringBuilder msg = new StringBuilder();
                 msg.AppendFormat("Message        {0}\n", er.Message);
                 msg.AppendFormat("Source         {0}\n", er.Source);
                 msg.AppendFormat("InnerException {0}\n", er.InnerException);
                 msg.AppendFormat("StackTrace     {0}\n", er.StackTrace);
                 msg.AppendFormat("TargetSite     {0}\n", er.TargetSite);
                 // Log error
                 _MyLogControlEventos.ErrorFormat("Error {0}", msg.ToString());
                 // Mensaje de Error
                 MessageBox.Show("Se ha producido el siguiente error " + er.Message, "Error", MessageBoxButtons.OK, MessageBoxIcon.Error);
             }
         }
btnBuscarProducto_Click()
void UTN.Winform.AppAirBnB.Layers.UI.Procesos.frmReservacion.btnBuscarProducto_Click (object sender, EventArgs e) private
Definition at line 307 of file frmReservacion.cs.
References UTN.Winform.AppAirBnB.Layers.UI.Filtros.frmFiltroHabi.FHabitacion, and UTN.Winform.AppAirBnB.Layers.Entities.DTO.HabitacionDTO.NUM.
         {
             frmFiltroHabi ofrmFiltroHabi = new frmFiltroHabi();
             HabitacionDTO oHabitacion = null;
             try
             {
                 ofrmFiltroHabi.ShowDialog();
                 if (ofrmFiltroHabi.DialogResult == DialogResult.OK)
                 {
                     oHabitacion = ofrmFiltroHabi.FHabitacion;
                     this.mskNUMHabitacion.Text = oHabitacion.NUM.ToString();
                 }
             }
             catch (Exception er)
             {
                 StringBuilder msg = new StringBuilder();
                 msg.AppendFormat("Message        {0}\n", er.Message);
                 msg.AppendFormat("Source         {0}\n", er.Source);
                 msg.AppendFormat("InnerException {0}\n", er.InnerException);
                 msg.AppendFormat("StackTrace     {0}\n", er.StackTrace);
                 msg.AppendFormat("TargetSite     {0}\n", er.TargetSite);
                 // Log error
                 _MyLogControlEventos.ErrorFormat("Error {0}", msg.ToString());
                 // Mensaje de Error
                 MessageBox.Show("Se ha producido el siguiente error " + er.Message, "Error", MessageBoxButtons.OK, MessageBoxIcon.Error);
             }
         }
CargarDatos()
void UTN.Winform.AppAirBnB.Layers.UI.Procesos.frmReservacion.CargarDatos () private
Definition at line 68 of file frmReservacion.cs.
References UTN.Winform.AppAirBnB.Layers.Interface.IBLLReservacion.GetAllReservacion().
         {
             IBLLReservacion _BLLReserva = new BLLReservacion();
             // Configuracion del DataGridView para que se vea bien la imagen.
             dgvDetalleReserva.AutoGenerateColumns = true;
             // Cargar el DataGridView
             this.dgvDetalleReserva.DataSource = _BLLReserva.GetAllReservacion();
         }
Dispose()
override void UTN.Winform.AppAirBnB.Layers.UI.Procesos.frmReservacion.Dispose (bool disposing) protected
Clean up any resources being used.
Parameters
disposing true if managed resources should be disposed; otherwise, false.
Definition at line 14 of file frmReservacion.Designer.cs.
         {
             if (disposing && (components != null))
             {
                 components.Dispose();
             }
             base.Dispose(disposing);
         }
frmReservacion_Load()
void UTN.Winform.AppAirBnB.Layers.UI.Procesos.frmReservacion.frmReservacion_Load (object sender, EventArgs e) private
Definition at line 86 of file frmReservacion.cs.
References UTN.Winform.AppAirBnB.Layers.Interface.IBLLReservacion.GetCurrentNumeroReserva().
         {
             IBLLReservacion _BLLReservacion = new BLLReservacion();
             try
             {
                 // Mostar Numero de factura
                 this.txtNumeroReservacion.Text = _BLLReservacion.GetCurrentNumeroReserva().ToString();
                 CargarDatos();
             }
             catch (Exception er)
             {
                 StringBuilder msg = new StringBuilder();
                 msg.AppendFormat("Message        {0}\n", er.Message);
                 msg.AppendFormat("Source         {0}\n", er.Source);
                 msg.AppendFormat("InnerException {0}\n", er.InnerException);
                 msg.AppendFormat("StackTrace     {0}\n", er.StackTrace);
                 msg.AppendFormat("TargetSite     {0}\n", er.TargetSite);
                 // Log error
                 _MyLogControlEventos.ErrorFormat("Error {0}", msg.ToString());
                 // Mensaje de Error
                 MessageBox.Show("Se ha producido el siguiente error " + er.Message, "Error", MessageBoxButtons.OK, MessageBoxIcon.Error);
             }
         }
InitializeComponent()
void UTN.Winform.AppAirBnB.Layers.UI.Procesos.frmReservacion.InitializeComponent () private
Required method for Designer support - do not modify the contents of this method with the code editor.
Definition at line 29 of file frmReservacion.Designer.cs.
         {
             this.tspBarraSuperior = new System.Windows.Forms.ToolStrip();
             this.sttBarraInferior = new System.Windows.Forms.StatusStrip();
             this.toolStripStatusLabel1 = new System.Windows.Forms.ToolStripStatusLabel();
             this.tableLayoutPanel3 = new System.Windows.Forms.TableLayoutPanel();
             this.mskNUMHabitacion = new System.Windows.Forms.MaskedTextBox();
             this.label5 = new System.Windows.Forms.Label();
             this.lblCantidad = new System.Windows.Forms.Label();
             this.mskCantidad = new System.Windows.Forms.MaskedTextBox();
             this.btnBuscarProducto = new System.Windows.Forms.Button();
             this.groupBox1 = new System.Windows.Forms.GroupBox();
             this.tlpAgrupamiento = new System.Windows.Forms.TableLayoutPanel();
             this.label11 = new System.Windows.Forms.Label();
             this.label3 = new System.Windows.Forms.Label();
             this.txtHuespedId = new System.Windows.Forms.TextBox();
             this.label1 = new System.Windows.Forms.Label();
             this.dtpCheckIN = new System.Windows.Forms.DateTimePicker();
             this.label2 = new System.Windows.Forms.Label();
             this.dtpCheckOut = new System.Windows.Forms.DateTimePicker();
             this.txtNumeroReservacion = new System.Windows.Forms.TextBox();
             this.btnBuscarHuesped = new System.Windows.Forms.Button();
             this.dgvDetalleReserva = new System.Windows.Forms.DataGridView();
             this.groupBox2 = new System.Windows.Forms.GroupBox();
             this.txtSub = new System.Windows.Forms.TextBox();
             this.label4 = new System.Windows.Forms.Label();
             this.toolStripBtnNuevo = new System.Windows.Forms.ToolStripButton();
             this.toolStripBtnReservar = new System.Windows.Forms.ToolStripButton();
             this.toolStripButton1 = new System.Windows.Forms.ToolStripButton();
             this.toolStripBtnSalir = new System.Windows.Forms.ToolStripButton();
             this.tspBarraSuperior.SuspendLayout();
             this.sttBarraInferior.SuspendLayout();
             this.tableLayoutPanel3.SuspendLayout();
             this.groupBox1.SuspendLayout();
             this.tlpAgrupamiento.SuspendLayout();
             ((System.ComponentModel.ISupportInitialize)(this.dgvDetalleReserva)).BeginInit();
             this.groupBox2.SuspendLayout();
             this.SuspendLayout();
             //
             // tspBarraSuperior
             //
             this.tspBarraSuperior.Items.AddRange(new System.Windows.Forms.ToolStripItem[] {
             this.toolStripBtnNuevo,
             this.toolStripBtnReservar,
             this.toolStripButton1,
             this.toolStripBtnSalir});
             this.tspBarraSuperior.Location = new System.Drawing.Point(0, 0);
             this.tspBarraSuperior.Name = "tspBarraSuperior";
             this.tspBarraSuperior.Size = new System.Drawing.Size(1131, 55);
             this.tspBarraSuperior.TabIndex = 2;
             this.tspBarraSuperior.Text = "toolStrip1";
             //
             // sttBarraInferior
             //
             this.sttBarraInferior.Items.AddRange(new System.Windows.Forms.ToolStripItem[] {
             this.toolStripStatusLabel1});
             this.sttBarraInferior.Location = new System.Drawing.Point(0, 453);
             this.sttBarraInferior.Name = "sttBarraInferior";
             this.sttBarraInferior.Size = new System.Drawing.Size(1131, 22);
             this.sttBarraInferior.TabIndex = 3;
             this.sttBarraInferior.Text = "statusStrip1";
             //
             // toolStripStatusLabel1
             //
             this.toolStripStatusLabel1.Name = "toolStripStatusLabel1";
             this.toolStripStatusLabel1.Size = new System.Drawing.Size(0, 17);
             //
             // tableLayoutPanel3
             //
             this.tableLayoutPanel3.ColumnCount = 3;
             this.tableLayoutPanel3.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 37.9822F));
             this.tableLayoutPanel3.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 62.0178F));
             this.tableLayoutPanel3.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Absolute, 155F));
             this.tableLayoutPanel3.Controls.Add(this.mskNUMHabitacion, 1, 0);
             this.tableLayoutPanel3.Controls.Add(this.btnBuscarProducto, 2, 1);
             this.tableLayoutPanel3.Controls.Add(this.label5, 0, 0);
             this.tableLayoutPanel3.Controls.Add(this.lblCantidad, 0, 1);
             this.tableLayoutPanel3.Controls.Add(this.mskCantidad, 1, 1);
             this.tableLayoutPanel3.Location = new System.Drawing.Point(16, 274);
             this.tableLayoutPanel3.Name = "tableLayoutPanel3";
             this.tableLayoutPanel3.RowCount = 5;
             this.tableLayoutPanel3.RowStyles.Add(new System.Windows.Forms.RowStyle());
             this.tableLayoutPanel3.RowStyles.Add(new System.Windows.Forms.RowStyle());
             this.tableLayoutPanel3.RowStyles.Add(new System.Windows.Forms.RowStyle());
             this.tableLayoutPanel3.RowStyles.Add(new System.Windows.Forms.RowStyle());
             this.tableLayoutPanel3.RowStyles.Add(new System.Windows.Forms.RowStyle());
             this.tableLayoutPanel3.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 20F));
             this.tableLayoutPanel3.Size = new System.Drawing.Size(493, 99);
             this.tableLayoutPanel3.TabIndex = 9;
             //
             // mskNUMHabitacion
             //
             this.mskNUMHabitacion.Location = new System.Drawing.Point(131, 3);
             this.mskNUMHabitacion.Mask = "99999999999";
             this.mskNUMHabitacion.Name = "mskNUMHabitacion";
             this.mskNUMHabitacion.Size = new System.Drawing.Size(193, 20);
             this.mskNUMHabitacion.TabIndex = 4;
             //
             // label5
             //
             this.label5.AutoSize = true;
             this.label5.Location = new System.Drawing.Point(3, 0);
             this.label5.Name = "label5";
             this.label5.Size = new System.Drawing.Size(98, 13);
             this.label5.TabIndex = 0;
             this.label5.Text = "Numero Habitacin";
             //
             // lblCantidad
             //
             this.lblCantidad.AutoSize = true;
             this.lblCantidad.Location = new System.Drawing.Point(3, 26);
             this.lblCantidad.Name = "lblCantidad";
             this.lblCantidad.Size = new System.Drawing.Size(30, 13);
             this.lblCantidad.TabIndex = 5;
             this.lblCantidad.Text = "Das";
             //
             // mskCantidad
             //
             this.mskCantidad.Location = new System.Drawing.Point(131, 29);
             this.mskCantidad.Mask = "999999999999";
             this.mskCantidad.Name = "mskCantidad";
             this.mskCantidad.Size = new System.Drawing.Size(193, 20);
             this.mskCantidad.TabIndex = 6;
             //
             // btnBuscarProducto
             //
             this.btnBuscarProducto.Location = new System.Drawing.Point(340, 29);
             this.btnBuscarProducto.Name = "btnBuscarProducto";
             this.btnBuscarProducto.Size = new System.Drawing.Size(110, 67);
             this.btnBuscarProducto.TabIndex = 1;
             this.btnBuscarProducto.Text = "Buscar Habitacion";
             this.btnBuscarProducto.TextImageRelation = System.Windows.Forms.TextImageRelation.ImageBeforeText;
             this.btnBuscarProducto.UseVisualStyleBackColor = true;
             this.btnBuscarProducto.Click += new System.EventHandler(this.btnBuscarProducto_Click);
             //
             // groupBox1
             //
             this.groupBox1.Controls.Add(this.tlpAgrupamiento);
             this.groupBox1.FlatStyle = System.Windows.Forms.FlatStyle.Popup;
             this.groupBox1.Location = new System.Drawing.Point(0, 52);
             this.groupBox1.Name = "groupBox1";
             this.groupBox1.Size = new System.Drawing.Size(521, 398);
             this.groupBox1.TabIndex = 8;
             this.groupBox1.TabStop = false;
             this.groupBox1.Text = "Reservacin";
             //
             // tlpAgrupamiento
             //
             this.tlpAgrupamiento.BackColor = System.Drawing.SystemColors.Control;
             this.tlpAgrupamiento.ColumnCount = 3;
             this.tlpAgrupamiento.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Absolute, 129F));
             this.tlpAgrupamiento.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Absolute, 208F));
             this.tlpAgrupamiento.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Absolute, 306F));
             this.tlpAgrupamiento.Controls.Add(this.label11, 0, 0);
             this.tlpAgrupamiento.Controls.Add(this.label3, 0, 3);
             this.tlpAgrupamiento.Controls.Add(this.txtHuespedId, 1, 3);
             this.tlpAgrupamiento.Controls.Add(this.label1, 0, 4);
             this.tlpAgrupamiento.Controls.Add(this.dtpCheckIN, 1, 4);
             this.tlpAgrupamiento.Controls.Add(this.label2, 0, 5);
             this.tlpAgrupamiento.Controls.Add(this.dtpCheckOut, 1, 5);
             this.tlpAgrupamiento.Controls.Add(this.txtNumeroReservacion, 1, 0);
             this.tlpAgrupamiento.Controls.Add(this.btnBuscarHuesped, 2, 3);
             this.tlpAgrupamiento.Location = new System.Drawing.Point(16, 29);
             this.tlpAgrupamiento.Name = "tlpAgrupamiento";
             this.tlpAgrupamiento.RowCount = 6;
             this.tlpAgrupamiento.RowStyles.Add(new System.Windows.Forms.RowStyle());
             this.tlpAgrupamiento.RowStyles.Add(new System.Windows.Forms.RowStyle());
             this.tlpAgrupamiento.RowStyles.Add(new System.Windows.Forms.RowStyle());
             this.tlpAgrupamiento.RowStyles.Add(new System.Windows.Forms.RowStyle());
             this.tlpAgrupamiento.RowStyles.Add(new System.Windows.Forms.RowStyle());
             this.tlpAgrupamiento.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 20F));
             this.tlpAgrupamiento.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 20F));
             this.tlpAgrupamiento.Size = new System.Drawing.Size(493, 175);
             this.tlpAgrupamiento.TabIndex = 2;
             //
             // label11
             //
             this.label11.AutoSize = true;
             this.label11.Location = new System.Drawing.Point(3, 0);
             this.label11.Name = "label11";
             this.label11.Size = new System.Drawing.Size(87, 13);
             this.label11.TabIndex = 11;
             this.label11.Text = "No. Reservacin";
             //
             // label3
             //
             this.label3.AutoSize = true;
             this.label3.Location = new System.Drawing.Point(3, 26);
             this.label3.Name = "label3";
             this.label3.Size = new System.Drawing.Size(50, 13);
             this.label3.TabIndex = 2;
             this.label3.Text = "Huesped";
             //
             // txtHuespedId
             //
             this.txtHuespedId.Location = new System.Drawing.Point(132, 29);
             this.txtHuespedId.Name = "txtHuespedId";
             this.txtHuespedId.Size = new System.Drawing.Size(200, 20);
             this.txtHuespedId.TabIndex = 8;
             //
             // label1
             //
             this.label1.AutoSize = true;
             this.label1.Location = new System.Drawing.Point(3, 52);
             this.label1.Name = "label1";
             this.label1.Size = new System.Drawing.Size(52, 13);
             this.label1.TabIndex = 17;
             this.label1.Text = "Check IN";
             //
             // dtpCheckIN
             //
             this.dtpCheckIN.Location = new System.Drawing.Point(132, 55);
             this.dtpCheckIN.Name = "dtpCheckIN";
             this.dtpCheckIN.Size = new System.Drawing.Size(200, 20);
             this.dtpCheckIN.TabIndex = 15;
             //
             // label2
             //
             this.label2.AutoSize = true;
             this.label2.Location = new System.Drawing.Point(3, 88);
             this.label2.Name = "label2";
             this.label2.Size = new System.Drawing.Size(64, 13);
             this.label2.TabIndex = 18;
             this.label2.Text = "Check OUT";
             //
             // dtpCheckOut
             //
             this.dtpCheckOut.Location = new System.Drawing.Point(132, 91);
             this.dtpCheckOut.Name = "dtpCheckOut";
             this.dtpCheckOut.Size = new System.Drawing.Size(200, 20);
             this.dtpCheckOut.TabIndex = 19;
             //
             // txtNumeroReservacion
             //
             this.txtNumeroReservacion.Location = new System.Drawing.Point(132, 3);
             this.txtNumeroReservacion.Name = "txtNumeroReservacion";
             this.txtNumeroReservacion.Size = new System.Drawing.Size(200, 20);
             this.txtNumeroReservacion.TabIndex = 20;
             //
             // btnBuscarHuesped
             //
             this.btnBuscarHuesped.Location = new System.Drawing.Point(340, 29);
             this.btnBuscarHuesped.Name = "btnBuscarHuesped";
             this.tlpAgrupamiento.SetRowSpan(this.btnBuscarHuesped, 2);
             this.btnBuscarHuesped.Size = new System.Drawing.Size(110, 56);
             this.btnBuscarHuesped.TabIndex = 9;
             this.btnBuscarHuesped.Text = "Buscar Huesped";
             this.btnBuscarHuesped.TextImageRelation = System.Windows.Forms.TextImageRelation.ImageBeforeText;
             this.btnBuscarHuesped.UseVisualStyleBackColor = true;
             this.btnBuscarHuesped.Click += new System.EventHandler(this.btnBuscarHuesped_Click);
             //
             // dgvDetalleReserva
             //
             this.dgvDetalleReserva.AllowUserToAddRows = false;
             this.dgvDetalleReserva.AllowUserToDeleteRows = false;
             this.dgvDetalleReserva.ColumnHeadersHeightSizeMode = System.Windows.Forms.DataGridViewColumnHeadersHeightSizeMode.AutoSize;
             this.dgvDetalleReserva.Location = new System.Drawing.Point(541, 76);
             this.dgvDetalleReserva.Name = "dgvDetalleReserva";
             this.dgvDetalleReserva.ReadOnly = true;
             this.dgvDetalleReserva.Size = new System.Drawing.Size(578, 325);
             this.dgvDetalleReserva.TabIndex = 10;
             //
             // groupBox2
             //
             this.groupBox2.Controls.Add(this.txtSub);
             this.groupBox2.Controls.Add(this.label4);
             this.groupBox2.Location = new System.Drawing.Point(527, 53);
             this.groupBox2.Name = "groupBox2";
             this.groupBox2.Size = new System.Drawing.Size(555, 397);
             this.groupBox2.TabIndex = 12;
             this.groupBox2.TabStop = false;
             this.groupBox2.Text = "Descripcin";
             //
             // txtSub
             //
             this.txtSub.Location = new System.Drawing.Point(426, 355);
             this.txtSub.Name = "txtSub";
             this.txtSub.Size = new System.Drawing.Size(123, 20);
             this.txtSub.TabIndex = 1;
             //
             // label4
             //
             this.label4.AutoSize = true;
             this.label4.Location = new System.Drawing.Point(367, 355);
             this.label4.Name = "label4";
             this.label4.Size = new System.Drawing.Size(52, 13);
             this.label4.TabIndex = 0;
             this.label4.Text = "Subtotal :";
             //
             // toolStripBtnNuevo
             //
             this.toolStripBtnNuevo.Image = global::UTN.Winform.AppAirBnB.Properties.Resources._48_48_5fcb865b3ad895719c10c7bfe5771fa4_pen;
             this.toolStripBtnNuevo.ImageScaling = System.Windows.Forms.ToolStripItemImageScaling.None;
             this.toolStripBtnNuevo.ImageTransparentColor = System.Drawing.Color.Magenta;
             this.toolStripBtnNuevo.Name = "toolStripBtnNuevo";
             this.toolStripBtnNuevo.Size = new System.Drawing.Size(94, 52);
             this.toolStripBtnNuevo.Text = "Nuevo";
             this.toolStripBtnNuevo.Click += new System.EventHandler(this.toolStripBtnNuevo_Click);
             //
             // toolStripBtnReservar
             //
             this.toolStripBtnReservar.Image = global::UTN.Winform.AppAirBnB.Properties.Resources._48_48_6d18f14292ffd3debaca5d368aec541f_building;
             this.toolStripBtnReservar.ImageScaling = System.Windows.Forms.ToolStripItemImageScaling.None;
             this.toolStripBtnReservar.ImageTransparentColor = System.Drawing.Color.Magenta;
             this.toolStripBtnReservar.Name = "toolStripBtnReservar";
             this.toolStripBtnReservar.Size = new System.Drawing.Size(103, 52);
             this.toolStripBtnReservar.Text = "Reservar";
             this.toolStripBtnReservar.Click += new System.EventHandler(this.toolStripBtnReservar_Click);
             //
             // toolStripButton1
             //
             this.toolStripButton1.Image = global::UTN.Winform.AppAirBnB.Properties.Resources._48_48_2105a9c63eeaa7a280f82fb9c0ce8123_bulb;
             this.toolStripButton1.ImageScaling = System.Windows.Forms.ToolStripItemImageScaling.None;
             this.toolStripButton1.ImageTransparentColor = System.Drawing.Color.Magenta;
             this.toolStripButton1.Name = "toolStripButton1";
             this.toolStripButton1.Size = new System.Drawing.Size(105, 52);
             this.toolStripButton1.Text = "Cancelar";
             this.toolStripButton1.Click += new System.EventHandler(this.toolStripButton1_Click);
             //
             // toolStripBtnSalir
             //
             this.toolStripBtnSalir.Image = global::UTN.Winform.AppAirBnB.Properties.Resources._48_48_10696bc060189f66efd1c9d2397cac66_bullseye;
             this.toolStripBtnSalir.ImageScaling = System.Windows.Forms.ToolStripItemImageScaling.None;
             this.toolStripBtnSalir.ImageTransparentColor = System.Drawing.Color.Magenta;
             this.toolStripBtnSalir.Name = "toolStripBtnSalir";
             this.toolStripBtnSalir.Size = new System.Drawing.Size(81, 52);
             this.toolStripBtnSalir.Text = "Salir";
             this.toolStripBtnSalir.Click += new System.EventHandler(this.toolStripBtnSalir_Click);
             //
             // frmReservacion
             //
             this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
             this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
             this.ClientSize = new System.Drawing.Size(1131, 475);
             this.Controls.Add(this.dgvDetalleReserva);
             this.Controls.Add(this.groupBox2);
             this.Controls.Add(this.tableLayoutPanel3);
             this.Controls.Add(this.groupBox1);
             this.Controls.Add(this.sttBarraInferior);
             this.Controls.Add(this.tspBarraSuperior);
             this.Name = "frmReservacion";
             this.StartPosition = System.Windows.Forms.FormStartPosition.CenterParent;
             this.Text = "Reservacin";
             this.WindowState = System.Windows.Forms.FormWindowState.Maximized;
             this.Load += new System.EventHandler(this.frmReservacion_Load);
             this.tspBarraSuperior.ResumeLayout(false);
             this.tspBarraSuperior.PerformLayout();
             this.sttBarraInferior.ResumeLayout(false);
             this.sttBarraInferior.PerformLayout();
             this.tableLayoutPanel3.ResumeLayout(false);
             this.tableLayoutPanel3.PerformLayout();
             this.groupBox1.ResumeLayout(false);
             this.tlpAgrupamiento.ResumeLayout(false);
             this.tlpAgrupamiento.PerformLayout();
             ((System.ComponentModel.ISupportInitialize)(this.dgvDetalleReserva)).EndInit();
             this.groupBox2.ResumeLayout(false);
             this.groupBox2.PerformLayout();
             this.ResumeLayout(false);
             this.PerformLayout();
         }
toolStripBtnNuevo_Click()
void UTN.Winform.AppAirBnB.Layers.UI.Procesos.frmReservacion.toolStripBtnNuevo_Click (object sender, EventArgs e) private
Definition at line 31 of file frmReservacion.cs.
References UTN.Winform.AppAirBnB.Layers.Interface.IBLLReservacion.GetNextNumeroReserva().
         {
             IBLLReservacion _BLLReservacion = new BLLReservacion();
             try
             {
                 _Huesped = null;
                 this.txtHuespedId.Text = "";
                 this.txtNumeroReservacion.Text = "";
                 this.mskCantidad.Text = "";
                 this.mskNUMHabitacion.Text = "";
                 this.mskCantidad.Text = "";
                 txtNumeroReservacion.Focus();
                 // Mostar Numero de factura
                 this.txtNumeroReservacion.Text = _BLLReservacion.GetNextNumeroReserva().ToString();
             }
             catch (Exception er)
             {
                 StringBuilder msg = new StringBuilder();
                 msg.AppendFormat("Message        {0}\n", er.Message);
                 msg.AppendFormat("Source         {0}\n", er.Source);
                 msg.AppendFormat("InnerException {0}\n", er.InnerException);
                 msg.AppendFormat("StackTrace     {0}\n", er.StackTrace);
                 msg.AppendFormat("TargetSite     {0}\n", er.TargetSite);
                 // Log error
                 _MyLogControlEventos.ErrorFormat("Error {0}", msg.ToString());
                 // Mensaje de Error
                 MessageBox.Show("Se ha producido el siguiente error " + er.Message, "Error", MessageBoxButtons.OK, MessageBoxIcon.Error);
             }
         }
toolStripBtnReservar_Click()
void UTN.Winform.AppAirBnB.Layers.UI.Procesos.frmReservacion.toolStripBtnReservar_Click (object sender, EventArgs e) private
Definition at line 115 of file frmReservacion.cs.
References UTN.Winform.AppAirBnB.Layers.Entities.Reservacion._Habitacion, UTN.Winform.AppAirBnB.Layers.Entities.Reservacion._Huesped, UTN.Winform.AppAirBnB.Layers.Interface.IBLLHabitacion.GetHabitacionById(), UTN.Winform.AppAirBnB.Layers.Interface.IBLLHuesped.GetHuespedById(), UTN.Winform.AppAirBnB.Layers.Entities.Reservacion.ID, and UTN.Winform.AppAirBnB.Layers.Entities.Habitacion.Precio.
         {
             try
             {
                 Reservacion oReservacion = null;
                 IBLLReservacion _IBLLReservacion = new BLLReservacion();
                 IBLLHabitacion _BLLHabitacion = new BLLHabitacion();
                 IBLLHuesped _BLLHuesped = new BLLHuesped();
                 if (this.txtHuespedId == null)
                 {
                     MessageBox.Show(" Es un dato requerido !", "Atencin");
                     return;
                 }
                 oReservacion = new Reservacion();
                 oReservacion.ID = double.Parse(this.txtNumeroReservacion.Text);
                 oReservacion._Huesped = _BLLHuesped.GetHuespedById( double.Parse(this.txtHuespedId.Text.ToString()));
                 oReservacion._Habitacion = _BLLHabitacion.GetHabitacionById(double.Parse(this.mskNUMHabitacion.Text.ToString()));
                 foreach (var item in _IBLLReservacion.GetAllReservacion())
                 {
                     if (item.CheckIN.Day == this.dtpCheckIN.Value.Day &&
                         item.CheckIN.Month == this.dtpCheckIN.Value.Month
                         && item._Habitacion.NUM == _BLLHabitacion.GetHabitacionById(double.Parse(this.mskNUMHabitacion.Text.ToString())).NUM)
                     {
                             MessageBox.Show(" La Habitacion se encuantra Ocupada !", "Atencin");
                             return;
                     }
                     if (item.CheckOUT.Day == this.dtpCheckOut.Value.Day && item.CheckOUT.Month == this.dtpCheckOut.Value.Month &&
                         item._Habitacion.NUM == _BLLHabitacion.GetHabitacionById(double.Parse(this.mskNUMHabitacion.Text.ToString())).NUM)
                     {
                         MessageBox.Show(" La Habitacion se encuantra Ocupada !", "Atencin");
                         return;
                     }
                 }
                 if (this.dtpCheckIN.Value.Day < DateTime.Now.Day || this.dtpCheckIN.Value.Month < DateTime.Now.Month)
                 {
                     MessageBox.Show(" No puede reservar fechas anteriores a la actual !", "Atencin");
                     return;
                 }
                 if (this.dtpCheckOut.Value.Day < DateTime.Now.Day || this.dtpCheckOut.Value.Month < DateTime.Now.Month
                     || this.dtpCheckOut.Value.Day < this.dtpCheckIN.Value.Day || this.dtpCheckOut.Value.Month < dtpCheckIN.Value.Month)
                 {
                     MessageBox.Show(" No puede reservar fechas anteriores a la actual !", "Atencin");
                     return;
                 }
                 oReservacion.CheckIN = (DateTime)this.dtpCheckIN.Value;
                 oReservacion.CheckOUT = (DateTime)this.dtpCheckOut.Value;
                 oReservacion.CantDias = double.Parse(this.mskCantidad.Text);
                 oReservacion.Subtotal = double.Parse(this.mskCantidad.Text) * _BLLHabitacion.GetHabitacionById(double.Parse(this.mskNUMHabitacion.Text.ToString())).Precio;
                 txtSub.Text = oReservacion.Subtotal.ToString();
                 _IBLLReservacion.SaveReserva(oReservacion);
                 if (oReservacion != null)
                     this.CargarDatos();
             }
             catch (Exception er)
             {
                 StringBuilder msg = new StringBuilder();
                 msg.AppendFormat("Message        {0}\n", er.Message);
                 msg.AppendFormat("Source         {0}\n", er.Source);
                 msg.AppendFormat("InnerException {0}\n", er.InnerException);
                 msg.AppendFormat("StackTrace     {0}\n", er.StackTrace);
                 msg.AppendFormat("TargetSite     {0}\n", er.TargetSite);
                 // Log error
                 _MyLogControlEventos.ErrorFormat("Error {0}", msg.ToString());
                 // Mensaje de Error
                 MessageBox.Show("Se ha producido el siguiente error " + er.Message, "Error", MessageBoxButtons.OK, MessageBoxIcon.Error);
             }
         }
toolStripBtnSalir_Click()
void UTN.Winform.AppAirBnB.Layers.UI.Procesos.frmReservacion.toolStripBtnSalir_Click (object sender, EventArgs e) private
Definition at line 228 of file frmReservacion.cs.
         {
             Close();
         }
toolStripButton1_Click()
void UTN.Winform.AppAirBnB.Layers.UI.Procesos.frmReservacion.toolStripButton1_Click (object sender, EventArgs e) private
Definition at line 233 of file frmReservacion.cs.
References UTN.Winform.AppAirBnB.Layers.Interface.IBLLReservacion.DeleteReserva(), and UTN.Winform.AppAirBnB.Layers.Entities.Reservacion.ID.
         {
             IBLLReservacion _IBLLReservacion = new BLLReservacion();
             try
             {
                 if (this.dgvDetalleReserva.SelectedRows.Count > 0)
                 {
                     Reservacion oReservacion = this.dgvDetalleReserva.SelectedRows[0].DataBoundItem as Reservacion;
                     if (MessageBox.Show($"Seguro que desea borrar el registro de Reservacion :  {oReservacion.ID} ?", "Confirmacin", MessageBoxButtons.YesNo, MessageBoxIcon.Question) == DialogResult.Yes)
                     {
                         _IBLLReservacion.DeleteReserva(oReservacion.ID);
                         this.CargarDatos();
                     }
                 }
                 else
                 {
                     MessageBox.Show("Seleccione el registro !", "Atencin", MessageBoxButtons.OK, MessageBoxIcon.Error);
                 }
             }
             catch (Exception er)
             {
                 StringBuilder msg = new StringBuilder();
                 msg.AppendFormat("Message        {0}\n", er.Message);
                 msg.AppendFormat("Source         {0}\n", er.Source);
                 msg.AppendFormat("InnerException {0}\n", er.InnerException);
                 msg.AppendFormat("StackTrace     {0}\n", er.StackTrace);
                 msg.AppendFormat("TargetSite     {0}\n", er.TargetSite);
                 // Log error
                 //_MyLogControlEventos.ErrorFormat("Error {0}", msg.ToString());
                 // Mensaje de Error
                 MessageBox.Show("Se ha producido el siguiente error " + er.Message, "Error", MessageBoxButtons.OK, MessageBoxIcon.Error);
             }
         }
Member Data Documentation
_Huesped
Huesped UTN.Winform.AppAirBnB.Layers.UI.Procesos.frmReservacion._Huesped = null private
Definition at line 22 of file frmReservacion.cs.
_MyLogControlEventos
readonly ILog UTN.Winform.AppAirBnB.Layers.UI.Procesos.frmReservacion._MyLogControlEventos = log4net.LogManager.GetLogger("MyControlEventos") static private
Definition at line 21 of file frmReservacion.cs.
_Reservacion
Reservacion UTN.Winform.AppAirBnB.Layers.UI.Procesos.frmReservacion._Reservacion = null private
Definition at line 23 of file frmReservacion.cs.
btnBuscarHuesped
System.Windows.Forms.Button UTN.Winform.AppAirBnB.Layers.UI.Procesos.frmReservacion.btnBuscarHuesped private
Definition at line 406 of file frmReservacion.Designer.cs.
btnBuscarProducto
System.Windows.Forms.Button UTN.Winform.AppAirBnB.Layers.UI.Procesos.frmReservacion.btnBuscarProducto private
Definition at line 400 of file frmReservacion.Designer.cs.
cmbTarjeta
object UTN.Winform.AppAirBnB.Layers.UI.Procesos.frmReservacion.cmbTarjeta private
Definition at line 24 of file frmReservacion.cs.
components
System.ComponentModel.IContainer UTN.Winform.AppAirBnB.Layers.UI.Procesos.frmReservacion.components = null private
Required designer variable.
Definition at line 8 of file frmReservacion.Designer.cs.
dgvDetalleReserva
System.Windows.Forms.DataGridView UTN.Winform.AppAirBnB.Layers.UI.Procesos.frmReservacion.dgvDetalleReserva private
Definition at line 408 of file frmReservacion.Designer.cs.
dtpCheckIN
System.Windows.Forms.DateTimePicker UTN.Winform.AppAirBnB.Layers.UI.Procesos.frmReservacion.dtpCheckIN private
Definition at line 413 of file frmReservacion.Designer.cs.
dtpCheckOut
System.Windows.Forms.DateTimePicker UTN.Winform.AppAirBnB.Layers.UI.Procesos.frmReservacion.dtpCheckOut private
Definition at line 415 of file frmReservacion.Designer.cs.
groupBox1
System.Windows.Forms.GroupBox UTN.Winform.AppAirBnB.Layers.UI.Procesos.frmReservacion.groupBox1 private
Definition at line 402 of file frmReservacion.Designer.cs.
groupBox2
System.Windows.Forms.GroupBox UTN.Winform.AppAirBnB.Layers.UI.Procesos.frmReservacion.groupBox2 private
Definition at line 409 of file frmReservacion.Designer.cs.
label1
System.Windows.Forms.Label UTN.Winform.AppAirBnB.Layers.UI.Procesos.frmReservacion.label1 private
Definition at line 412 of file frmReservacion.Designer.cs.
label11
System.Windows.Forms.Label UTN.Winform.AppAirBnB.Layers.UI.Procesos.frmReservacion.label11 private
Definition at line 407 of file frmReservacion.Designer.cs.
label2
System.Windows.Forms.Label UTN.Winform.AppAirBnB.Layers.UI.Procesos.frmReservacion.label2 private
Definition at line 414 of file frmReservacion.Designer.cs.
label3
System.Windows.Forms.Label UTN.Winform.AppAirBnB.Layers.UI.Procesos.frmReservacion.label3 private
Definition at line 404 of file frmReservacion.Designer.cs.
label4
System.Windows.Forms.Label UTN.Winform.AppAirBnB.Layers.UI.Procesos.frmReservacion.label4 private
Definition at line 419 of file frmReservacion.Designer.cs.
label5
System.Windows.Forms.Label UTN.Winform.AppAirBnB.Layers.UI.Procesos.frmReservacion.label5 private
Definition at line 401 of file frmReservacion.Designer.cs.
lblCantidad
System.Windows.Forms.Label UTN.Winform.AppAirBnB.Layers.UI.Procesos.frmReservacion.lblCantidad private
Definition at line 399 of file frmReservacion.Designer.cs.
mskCantidad
System.Windows.Forms.MaskedTextBox UTN.Winform.AppAirBnB.Layers.UI.Procesos.frmReservacion.mskCantidad private
Definition at line 410 of file frmReservacion.Designer.cs.
mskNUMHabitacion
System.Windows.Forms.MaskedTextBox UTN.Winform.AppAirBnB.Layers.UI.Procesos.frmReservacion.mskNUMHabitacion private
Definition at line 411 of file frmReservacion.Designer.cs.
sttBarraInferior
System.Windows.Forms.StatusStrip UTN.Winform.AppAirBnB.Layers.UI.Procesos.frmReservacion.sttBarraInferior private
Definition at line 397 of file frmReservacion.Designer.cs.
tableLayoutPanel3
System.Windows.Forms.TableLayoutPanel UTN.Winform.AppAirBnB.Layers.UI.Procesos.frmReservacion.tableLayoutPanel3 private
Definition at line 398 of file frmReservacion.Designer.cs.
tlpAgrupamiento
System.Windows.Forms.TableLayoutPanel UTN.Winform.AppAirBnB.Layers.UI.Procesos.frmReservacion.tlpAgrupamiento private
Definition at line 403 of file frmReservacion.Designer.cs.
toolStripBtnNuevo
System.Windows.Forms.ToolStripButton UTN.Winform.AppAirBnB.Layers.UI.Procesos.frmReservacion.toolStripBtnNuevo private
Definition at line 394 of file frmReservacion.Designer.cs.
toolStripBtnReservar
System.Windows.Forms.ToolStripButton UTN.Winform.AppAirBnB.Layers.UI.Procesos.frmReservacion.toolStripBtnReservar private
Definition at line 395 of file frmReservacion.Designer.cs.
toolStripBtnSalir
System.Windows.Forms.ToolStripButton UTN.Winform.AppAirBnB.Layers.UI.Procesos.frmReservacion.toolStripBtnSalir private
Definition at line 396 of file frmReservacion.Designer.cs.
toolStripButton1
System.Windows.Forms.ToolStripButton UTN.Winform.AppAirBnB.Layers.UI.Procesos.frmReservacion.toolStripButton1 private
Definition at line 420 of file frmReservacion.Designer.cs.
toolStripStatusLabel1
System.Windows.Forms.ToolStripStatusLabel UTN.Winform.AppAirBnB.Layers.UI.Procesos.frmReservacion.toolStripStatusLabel1 private
Definition at line 417 of file frmReservacion.Designer.cs.
tspBarraSuperior
System.Windows.Forms.ToolStrip UTN.Winform.AppAirBnB.Layers.UI.Procesos.frmReservacion.tspBarraSuperior private
Definition at line 393 of file frmReservacion.Designer.cs.
txtHuespedId
System.Windows.Forms.TextBox UTN.Winform.AppAirBnB.Layers.UI.Procesos.frmReservacion.txtHuespedId private
Definition at line 405 of file frmReservacion.Designer.cs.
txtNumeroReservacion
System.Windows.Forms.TextBox UTN.Winform.AppAirBnB.Layers.UI.Procesos.frmReservacion.txtNumeroReservacion private
Definition at line 416 of file frmReservacion.Designer.cs.
txtSub
System.Windows.Forms.TextBox UTN.Winform.AppAirBnB.Layers.UI.Procesos.frmReservacion.txtSub private
Definition at line 418 of file frmReservacion.Designer.cs.
The documentation for this class was generated from the following files:
C:/Users/JorgeMario/Desktop/Proyecto Programado Cuatrimestre I 2018 v4/AppAirBnB/AppAirBnB/Layers/UI/Procesos/frmReservacion.cs
C:/Users/JorgeMario/Desktop/Proyecto Programado Cuatrimestre I 2018 v4/AppAirBnB/AppAirBnB/Layers/UI/Procesos/frmReservacion.Designer.cs