AppAirBnB: UTN.Winform.AppAirBnB.Layers.DAL.DALLogin Class Reference
UTN.Winform.AppAirBnB.Layers.DAL.DALLogin Class Reference
Public Member Functions
bool Login (string pUsuario, string pContrasena)
Static Private Attributes
static readonly ILog _MyLogControlEventos = LogManager.GetLogger("MyControlEventos")
Detailed Description
Definition at line 14 of file DALLogin.cs.
Member Function Documentation
Login()
bool UTN.Winform.AppAirBnB.Layers.DAL.DALLogin.Login (string pUsuario, string pContrasena)
Implements UTN.Winform.AppAirBnB.Layers.Interface.IDALLogin.
Definition at line 18 of file DALLogin.cs.
References UTN.Winform.AppAirBnB.Layers.Persistencia.FactoryConexion.CreateConnection(), UTN.Winform.AppAirBnB.Layers.Persistencia.FactoryDataBase.CreateDataBase(), UTN.Winform.AppAirBnB.Util.Utilitarios.CreateGenericErrorExceptionDetail(), and UTN.Winform.AppAirBnB.Util.Utilitarios.CreateSQLExceptionsErrorDetails().
         {
             StringBuilder conexion = new StringBuilder();
             try
             {
                 using (IDataBase db = FactoryDataBase.CreateDataBase(FactoryConexion.CreateConnection(pUsuario, pContrasena)))
                 {
                     // Si esto da error es porque el usuario no existe!
                 }
                 return true;
             }
             catch (SqlException sqlError)
             {
                 StringBuilder msg = new StringBuilder();
                 msg.AppendFormat(Utilitarios.CreateSQLExceptionsErrorDetails(sqlError));
                 _MyLogControlEventos.ErrorFormat("Error {0}", msg.ToString());
                 throw;
             }
             catch (Exception er)
             {
                 StringBuilder msg = new StringBuilder();
                 msg.AppendFormat(Utilitarios.CreateGenericErrorExceptionDetail(er));
                 _MyLogControlEventos.ErrorFormat("Error {0}", msg.ToString());
                 throw;
             }
         }
Member Data Documentation
_MyLogControlEventos
readonly ILog UTN.Winform.AppAirBnB.Layers.DAL.DALLogin._MyLogControlEventos = LogManager.GetLogger("MyControlEventos") static private
Definition at line 16 of file DALLogin.cs.
The documentation for this class was generated from the following file:
C:/Users/JorgeMario/Desktop/Proyecto Programado Cuatrimestre I 2018 v4/AppAirBnB/AppAirBnB/Layers/DAL/DALLogin.cs