AppAirBnB: UTN.Winform.AppAirBnB.Layers.BLL.BLLSeguridad Class Reference
UTN.Winform.AppAirBnB.Layers.BLL.BLLSeguridad Class Reference
Public Member Functions
void CreateUser (string pUuario, string pContrasena, string pBaseDatos)
IEnumerable< string > GetDataBases ()
IEnumerable< string > GetLoginsXDataBase (string pBaseDatos)
IEnumerable< string > GetLogins ()
Detailed Description
Definition at line 11 of file BLLSeguridad.cs.
Member Function Documentation
CreateUser()
void UTN.Winform.AppAirBnB.Layers.BLL.BLLSeguridad.CreateUser (string pUuario, string pContrasena, string pBaseDatos)
Implements UTN.Winform.AppAirBnB.Layers.Interface.IBLLSeguridad.
Definition at line 14 of file BLLSeguridad.cs.
References UTN.Winform.AppAirBnB.Layers.Interface.IDALSeguridad.CreateUser().
         {
             IDALSeguridad _DALSeguridad = new DALSeguridad();
             List<string> lista = new List<string>();
             lista.Add("master");
             lista.Add("model");
             lista.Add("msdb");
             lista.Add("tempdb");
             if (lista.FindAll(p => p.Equals(pBaseDatos, StringComparison.CurrentCultureIgnoreCase)).Count > 0)
             {
                 throw new Exception($"No se puede crear Logins en la Base de Datos {pBaseDatos}");
             }
             _DALSeguridad.CreateUser(pUuario, pContrasena, pBaseDatos);
         }
GetDataBases()
IEnumerable<string> UTN.Winform.AppAirBnB.Layers.BLL.BLLSeguridad.GetDataBases ()
Implements UTN.Winform.AppAirBnB.Layers.Interface.IBLLSeguridad.
Definition at line 32 of file BLLSeguridad.cs.
References UTN.Winform.AppAirBnB.Layers.Interface.IDALSeguridad.GetDataBases().
         {
             IDALSeguridad _DALSeguridad = new DALSeguridad();
             return _DALSeguridad.GetDataBases();
         }
GetLogins()
IEnumerable<string> UTN.Winform.AppAirBnB.Layers.BLL.BLLSeguridad.GetLogins ()
Implements UTN.Winform.AppAirBnB.Layers.Interface.IBLLSeguridad.
Definition at line 44 of file BLLSeguridad.cs.
References UTN.Winform.AppAirBnB.Layers.Interface.IDALSeguridad.GetLogins().
         {
             IDALSeguridad _DALSeguridad = new DALSeguridad();
             return _DALSeguridad.GetLogins();
         }
GetLoginsXDataBase()
IEnumerable<string> UTN.Winform.AppAirBnB.Layers.BLL.BLLSeguridad.GetLoginsXDataBase (string pBaseDatos)
Implements UTN.Winform.AppAirBnB.Layers.Interface.IBLLSeguridad.
Definition at line 38 of file BLLSeguridad.cs.
References UTN.Winform.AppAirBnB.Layers.Interface.IDALSeguridad.GetLoginsXDataBase().
         {
             IDALSeguridad _DALSeguridad = new DALSeguridad();
             return _DALSeguridad.GetLoginsXDataBase(pBaseDatos);
         }
The documentation for this class was generated from the following file:
C:/Users/JorgeMario/Desktop/Proyecto Programado Cuatrimestre I 2018 v4/AppAirBnB/AppAirBnB/Layers/BLL/BLLSeguridad.cs