AppAirBnB: UTN.Winform.AppAirBnB.Layers.DAL.DALTarjeta Class Reference
UTN.Winform.AppAirBnB.Layers.DAL.DALTarjeta Class Reference
Public Member Functions
DALTarjeta ()
List< Tarjeta > GetAllTarjeta ()
Tarjeta GetTarjetaById (double pIdTarjeta)
Private Attributes
Usuario _Usuario = new Usuario()
Static Private Attributes
static readonly ILog _MyLogControlEventos = LogManager.GetLogger("MyControlEventos")
Detailed Description
Definition at line 16 of file DALTarjeta.cs.
Constructor & Destructor Documentation
DALTarjeta()
UTN.Winform.AppAirBnB.Layers.DAL.DALTarjeta.DALTarjeta ()
Definition at line 21 of file DALTarjeta.cs.
References UTN.Winform.AppAirBnB.Properties.Settings.Default, UTN.Winform.AppAirBnB.Layers.Entities.Usuario.Login, UTN.Winform.AppAirBnB.Properties.Settings.Login, UTN.Winform.AppAirBnB.Layers.Entities.Usuario.Password, and UTN.Winform.AppAirBnB.Properties.Settings.Password.
         {
             _Usuario.Login = Settings.Default.Login;
             _Usuario.Password = Settings.Default.Password;
         }
Member Function Documentation
GetAllTarjeta()
List<Tarjeta> UTN.Winform.AppAirBnB.Layers.DAL.DALTarjeta.GetAllTarjeta ()
Implements UTN.Winform.AppAirBnB.Layers.Interface.IDALTarjeta.
Definition at line 27 of file DALTarjeta.cs.
References UTN.Winform.AppAirBnB.Layers.Persistencia.FactoryConexion.CreateConnection(), UTN.Winform.AppAirBnB.Layers.Persistencia.FactoryDataBase.CreateDataBase(), UTN.Winform.AppAirBnB.Layers.Persistencia.IDataBase.ExecuteReader(), UTN.Winform.AppAirBnB.Layers.Entities.Usuario.Login, and UTN.Winform.AppAirBnB.Layers.Entities.Usuario.Password.
         {
             IDataReader reader = null;
             List<Tarjeta> lista = new List<Tarjeta>();
             Tarjeta oTarjeta = null;
             SqlCommand command = new SqlCommand();
             try
             {
                 string sql = @"usp_SELECT_Tarjeta_All";
                 command.CommandText = sql;
                 command.CommandType = CommandType.StoredProcedure;
                 using (IDataBase db = FactoryDataBase.CreateDataBase(FactoryConexion.CreateConnection(_Usuario.Login, _Usuario.Password)))
                 {
                     reader = db.ExecuteReader(command);
                     // Si devolvió filas
                     while (reader.Read())
                     {
                         oTarjeta = new Tarjeta();
                         oTarjeta.ID = int.Parse(reader["ID"].ToString());
                         oTarjeta.Tipo = reader["Tipo"].ToString();
                         lista.Add(oTarjeta);
                     }
                 }
                 return lista;
             }
             catch (Exception er)
             {
                 StringBuilder msg = new StringBuilder();
                 msg.AppendFormat("Message        {0}\n", er.Message);
                 msg.AppendFormat("Source         {0}\n", er.Source);
                 msg.AppendFormat("InnerException {0}\n", er.InnerException);
                 msg.AppendFormat("StackTrace     {0}\n", er.StackTrace);
                 msg.AppendFormat("TargetSite     {0}\n", er.TargetSite);
                 _MyLogControlEventos.ErrorFormat("Error {0}", msg.ToString());
                 throw;
             }
         }
GetTarjetaById()
Tarjeta UTN.Winform.AppAirBnB.Layers.DAL.DALTarjeta.GetTarjetaById (double pIdTarjeta)
Implements UTN.Winform.AppAirBnB.Layers.Interface.IDALTarjeta.
Definition at line 71 of file DALTarjeta.cs.
References UTN.Winform.AppAirBnB.Layers.Persistencia.FactoryConexion.CreateConnection(), UTN.Winform.AppAirBnB.Layers.Persistencia.FactoryDataBase.CreateDataBase(), UTN.Winform.AppAirBnB.Layers.Persistencia.IDataBase.ExecuteReader(), UTN.Winform.AppAirBnB.Layers.Entities.Tarjeta.ID, UTN.Winform.AppAirBnB.Layers.Entities.Usuario.Login, UTN.Winform.AppAirBnB.Layers.Entities.Usuario.Password, and UTN.Winform.AppAirBnB.Layers.Entities.Tarjeta.Tipo.
         {
             DataSet ds = null;
             Tarjeta oTarjeta = null;
             SqlCommand command = new SqlCommand();
             string sql = @"usp_SELECT_Tarjeta_ByID";
             try
             {
                 command.Parameters.AddWithValue("@ID", pIdTarjeta);
                 command.CommandText = sql;
                 command.CommandType = CommandType.StoredProcedure;
                 using (IDataBase db = FactoryDataBase.CreateDataBase(FactoryConexion.CreateConnection(_Usuario.Login, _Usuario.Password)))
                 {
                     ds = db.ExecuteReader(command, "query");
                 }
                 // Si devolvió filas
                 if (ds.Tables[0].Rows.Count > 0)
                 {
                     // Iterar en todas las filas y Mapearlas
                     foreach (DataRow dr in ds.Tables[0].Rows)
                     {
                         oTarjeta = new Tarjeta();
                         oTarjeta.ID = int.Parse(dr["ID"].ToString());
                         oTarjeta.Tipo = dr["Tipo"].ToString();
                     }
                 }
                 return oTarjeta;
             }
             catch (Exception er)
             {
                 StringBuilder msg = new StringBuilder();
                 msg.AppendFormat("Message        {0}\n", er.Message);
                 msg.AppendFormat("Source         {0}\n", er.Source);
                 msg.AppendFormat("InnerException {0}\n", er.InnerException);
                 msg.AppendFormat("StackTrace     {0}\n", er.StackTrace);
                 msg.AppendFormat("TargetSite     {0}\n", er.TargetSite);
                 _MyLogControlEventos.ErrorFormat("Error {0}", msg.ToString());
                 throw;
             }
         }
Member Data Documentation
_MyLogControlEventos
readonly ILog UTN.Winform.AppAirBnB.Layers.DAL.DALTarjeta._MyLogControlEventos = LogManager.GetLogger("MyControlEventos") static private
Definition at line 18 of file DALTarjeta.cs.
_Usuario
Usuario UTN.Winform.AppAirBnB.Layers.DAL.DALTarjeta._Usuario = new Usuario() private
Definition at line 20 of file DALTarjeta.cs.
The documentation for this class was generated from the following file:
C:/Users/JorgeMario/Desktop/Proyecto Programado Cuatrimestre I 2018 v4/AppAirBnB/AppAirBnB/Layers/DAL/DALTarjeta.cs