AppAirBnB: UTN.Winform.AppAirBnB.Layers.DAL.DALPais Class Reference
UTN.Winform.AppAirBnB.Layers.DAL.DALPais Class Reference
Public Member Functions
DALPais ()
List< Pais > GetAllPais ()
Private Attributes
Usuario _Usuario = new Usuario()
Static Private Attributes
static readonly ILog _MyLogControlEventos = LogManager.GetLogger("MyControlEventos")
Detailed Description
Definition at line 17 of file DALPais.cs.
Constructor & Destructor Documentation
DALPais()
UTN.Winform.AppAirBnB.Layers.DAL.DALPais.DALPais ()
Definition at line 22 of file DALPais.cs.
References UTN.Winform.AppAirBnB.Properties.Settings.Default, UTN.Winform.AppAirBnB.Layers.Entities.Usuario.Login, UTN.Winform.AppAirBnB.Properties.Settings.Login, UTN.Winform.AppAirBnB.Layers.Entities.Usuario.Password, and UTN.Winform.AppAirBnB.Properties.Settings.Password.
         {
             _Usuario.Login = Settings.Default.Login;
             _Usuario.Password = Settings.Default.Password;
         }
Member Function Documentation
GetAllPais()
List<Pais> UTN.Winform.AppAirBnB.Layers.DAL.DALPais.GetAllPais ()
Implements UTN.Winform.AppAirBnB.Layers.Interface.IDALPais.
Definition at line 27 of file DALPais.cs.
References UTN.Winform.AppAirBnB.Layers.Persistencia.FactoryConexion.CreateConnection(), UTN.Winform.AppAirBnB.Layers.Persistencia.FactoryDataBase.CreateDataBase(), UTN.Winform.AppAirBnB.Util.Utilitarios.CreateGenericErrorExceptionDetail(), UTN.Winform.AppAirBnB.Util.Utilitarios.CreateSQLExceptionsErrorDetails(), UTN.Winform.AppAirBnB.Layers.Entities.Pais.Detalle, UTN.Winform.AppAirBnB.Layers.Persistencia.IDataBase.ExecuteReader(), UTN.Winform.AppAirBnB.Layers.Entities.Pais.ID, UTN.Winform.AppAirBnB.Layers.Entities.Usuario.Login, and UTN.Winform.AppAirBnB.Layers.Entities.Usuario.Password.
         {
             IDataReader reader = null;
             List<Pais> lista = new List<Pais>();
             SqlCommand command = new SqlCommand();
             string sql = @"usp_SELECT_Pais_All";
             command.CommandText = sql;
             command.CommandType = CommandType.StoredProcedure;
             try
             {
                 using (IDataBase db = FactoryDataBase.CreateDataBase(FactoryConexion.CreateConnection(_Usuario.Login, _Usuario.Password)))
                 {
                     reader = db.ExecuteReader(command);
                     while (reader.Read())
                     {
                         Pais oPais = new Pais();
                         oPais.ID = int.Parse(reader["ID"].ToString());
                         oPais.Detalle = reader["Detalle"].ToString();
                         lista.Add(oPais);
                     }
                 }
                 return lista;
             }
             catch (SqlException sqlError)
             {
                 StringBuilder msg = new StringBuilder();
                 msg.AppendFormat(Utilitarios.CreateSQLExceptionsErrorDetails(sqlError));
                 msg.AppendFormat("SQL             {0}\n", command.CommandText);
                 _MyLogControlEventos.ErrorFormat("Error {0}", msg.ToString());
                 throw;
             }
             catch (Exception er)
             {
                 StringBuilder msg = new StringBuilder();
                 msg.AppendFormat(Utilitarios.CreateGenericErrorExceptionDetail(er));
                 _MyLogControlEventos.ErrorFormat("Error {0}", msg.ToString());
                 throw;
             }
         }
Member Data Documentation
_MyLogControlEventos
readonly ILog UTN.Winform.AppAirBnB.Layers.DAL.DALPais._MyLogControlEventos = LogManager.GetLogger("MyControlEventos") static private
Definition at line 19 of file DALPais.cs.
_Usuario
Usuario UTN.Winform.AppAirBnB.Layers.DAL.DALPais._Usuario = new Usuario() private
Definition at line 21 of file DALPais.cs.
The documentation for this class was generated from the following file:
C:/Users/JorgeMario/Desktop/Proyecto Programado Cuatrimestre I 2018 v4/AppAirBnB/AppAirBnB/Layers/DAL/DALPais.cs