AppAirBnB: UTN.Winform.AppAirBnB.Layers.BLL.BLLHuesped Class Reference
UTN.Winform.AppAirBnB.Layers.BLL.BLLHuesped Class Reference
Public Member Functions
List< Huesped > GetHuespedByFilter (string pDescripcion)
Huesped GetHuespedById (double pIdHuesped)
List< Huesped > GetAllHuesped ()
Huesped SaveHuesped (Huesped oHuesped)
bool DeleteHuesped (double pId)
Detailed Description
Definition at line 12 of file BLLHuesped.cs.
Member Function Documentation
DeleteHuesped()
bool UTN.Winform.AppAirBnB.Layers.BLL.BLLHuesped.DeleteHuesped (double pId)
Implements UTN.Winform.AppAirBnB.Layers.Interface.IBLLHuesped.
Definition at line 54 of file BLLHuesped.cs.
References UTN.Winform.AppAirBnB.Layers.Interface.IDALHuesped.DeleteHuesped().
         {
             IDALHuesped _DALHuesped = new DALHuesped();
             return _DALHuesped.DeleteHuesped(pId);
         }
GetAllHuesped()
List<Huesped> UTN.Winform.AppAirBnB.Layers.BLL.BLLHuesped.GetAllHuesped ()
Implements UTN.Winform.AppAirBnB.Layers.Interface.IBLLHuesped.
Definition at line 27 of file BLLHuesped.cs.
References UTN.Winform.AppAirBnB.Layers.Interface.IDALHuesped.GetAllHuesped().
         {
             IDALHuesped _DALHuesped = new DALHuesped();
             return _DALHuesped.GetAllHuesped();
         }
GetHuespedByFilter()
List<Huesped> UTN.Winform.AppAirBnB.Layers.BLL.BLLHuesped.GetHuespedByFilter (string pDescripcion)
Implements UTN.Winform.AppAirBnB.Layers.Interface.IBLLHuesped.
Definition at line 15 of file BLLHuesped.cs.
References UTN.Winform.AppAirBnB.Layers.Interface.IDALHuesped.GetHuespedByFilter().
         {
             IDALHuesped _DALHuesped = new DALHuesped();
             return _DALHuesped.GetHuespedByFilter(pDescripcion);
         }
GetHuespedById()
Huesped UTN.Winform.AppAirBnB.Layers.BLL.BLLHuesped.GetHuespedById (double pIdHuesped)
Implements UTN.Winform.AppAirBnB.Layers.Interface.IBLLHuesped.
Definition at line 21 of file BLLHuesped.cs.
References UTN.Winform.AppAirBnB.Layers.Interface.IDALHuesped.GetHuespedById().
         {
             IDALHuesped _DALHuesped = new DALHuesped();
             return _DALHuesped.GetHuespedById(pIdHuesped);
         }
SaveHuesped()
Huesped UTN.Winform.AppAirBnB.Layers.BLL.BLLHuesped.SaveHuesped (Huesped oHuesped)
Implements UTN.Winform.AppAirBnB.Layers.Interface.IBLLHuesped.
Definition at line 33 of file BLLHuesped.cs.
References UTN.Winform.AppAirBnB.Layers.Interface.IDALHuesped.GetHuespedById(), UTN.Winform.AppAirBnB.Layers.Entities.Huesped.ID, UTN.Winform.AppAirBnB.Layers.Interface.IDALHuesped.SaveHuesped(), and UTN.Winform.AppAirBnB.Layers.Interface.IDALHuesped.UpdateHuesped().
         {
             IDALHuesped _DALHuesped = new DALHuesped();
             Huesped _Huesped = null;
             if (_DALHuesped.GetHuespedById(oHuesped.ID).ID <= 0)
             {
                 _Huesped = _DALHuesped.SaveHuesped(oHuesped);
             }
             else
             {
                 _Huesped = _DALHuesped.UpdateHuesped(oHuesped);
             }
             return _DALHuesped.GetHuespedById(_Huesped.ID);
         }
The documentation for this class was generated from the following file:
C:/Users/JorgeMario/Desktop/Proyecto Programado Cuatrimestre I 2018 v4/AppAirBnB/AppAirBnB/Layers/BLL/BLLHuesped.cs