AppAirBnB: UTN.Winform.AppAirBnB.Layers.DAL.DALHuesped Class Reference
UTN.Winform.AppAirBnB.Layers.DAL.DALHuesped Class Reference
Public Member Functions
DALHuesped ()
bool DeleteHuesped (double pId)
List< Huesped > GetAllHuesped ()
List< Huesped > GetHuespedByFilter (string pDescripcion)
Huesped GetHuespedById (double pIdHuesped)
Huesped SaveHuesped (Huesped oHuesped)
Huesped UpdateHuesped (Huesped pHuesped)
Private Attributes
Usuario _Usuario = new Usuario()
Static Private Attributes
static readonly ILog _MyLogControlEventos = LogManager.GetLogger("MyControlEventos")
Detailed Description
Definition at line 17 of file DALHuesped.cs.
Constructor & Destructor Documentation
DALHuesped()
UTN.Winform.AppAirBnB.Layers.DAL.DALHuesped.DALHuesped ()
Definition at line 23 of file DALHuesped.cs.
References UTN.Winform.AppAirBnB.Properties.Settings.Default, UTN.Winform.AppAirBnB.Layers.Entities.Usuario.Login, UTN.Winform.AppAirBnB.Properties.Settings.Login, UTN.Winform.AppAirBnB.Layers.Entities.Usuario.Password, and UTN.Winform.AppAirBnB.Properties.Settings.Password.
         {
             _Usuario.Login = Settings.Default.Login;
             _Usuario.Password = Settings.Default.Password;
         }
Member Function Documentation
DeleteHuesped()
bool UTN.Winform.AppAirBnB.Layers.DAL.DALHuesped.DeleteHuesped (double pId)
string sql = "Delete from Cliente Where (IdCliente =) ";
Implements UTN.Winform.AppAirBnB.Layers.Interface.IDALHuesped.
Definition at line 29 of file DALHuesped.cs.
References UTN.Winform.AppAirBnB.Layers.Persistencia.FactoryConexion.CreateConnection(), UTN.Winform.AppAirBnB.Layers.Persistencia.FactoryDataBase.CreateDataBase(), UTN.Winform.AppAirBnB.Util.Utilitarios.CreateGenericErrorExceptionDetail(), UTN.Winform.AppAirBnB.Util.Utilitarios.CreateSQLExceptionsErrorDetails(), UTN.Winform.AppAirBnB.Layers.Persistencia.IDataBase.ExecuteNonQuery(), UTN.Winform.AppAirBnB.Layers.Entities.Usuario.Login, and UTN.Winform.AppAirBnB.Layers.Entities.Usuario.Password.
         {
             bool retorno = false;
             double rows = 0d;
             SqlCommand command = new SqlCommand();
             try
             {
                 string sql = "usp_DELETE_Huesped_ByID";
                 command.Parameters.AddWithValue("@ID", pId);
                 command.CommandText = sql;
                 command.CommandType = CommandType.StoredProcedure;
                 using (IDataBase db = FactoryDataBase.CreateDataBase(FactoryConexion.CreateConnection(_Usuario.Login, _Usuario.Password)))
                 {
                     rows = db.ExecuteNonQuery(command, IsolationLevel.ReadCommitted);
                 }
                 // Si devuelve filas quiere decir que se salvo entonces extraerlo
                 if (rows > 0)
                     retorno = true;
                 return retorno;
             }
             catch (SqlException sqlError)
             {
                 StringBuilder msg = new StringBuilder();
                 msg.AppendFormat(Utilitarios.CreateSQLExceptionsErrorDetails(sqlError));
                 msg.AppendFormat("SQL             {0}\n", command.CommandText);
                 _MyLogControlEventos.ErrorFormat("Error {0}", msg.ToString());
                 throw;
             }
             catch (Exception er)
             {
                 StringBuilder msg = new StringBuilder();
                 msg.AppendFormat(Utilitarios.CreateGenericErrorExceptionDetail(er));
                 _MyLogControlEventos.ErrorFormat("Error {0}", msg.ToString());
                 throw;
             }
         }
GetAllHuesped()
List<Huesped> UTN.Winform.AppAirBnB.Layers.DAL.DALHuesped.GetAllHuesped ()
Implements UTN.Winform.AppAirBnB.Layers.Interface.IDALHuesped.
Definition at line 70 of file DALHuesped.cs.
References UTN.Winform.AppAirBnB.Layers.Entities.Huesped.Apellido1, UTN.Winform.AppAirBnB.Layers.Entities.Huesped.Apellido2, UTN.Winform.AppAirBnB.Layers.Entities.Huesped.Correo, UTN.Winform.AppAirBnB.Layers.Persistencia.FactoryConexion.CreateConnection(), UTN.Winform.AppAirBnB.Layers.Persistencia.FactoryDataBase.CreateDataBase(), UTN.Winform.AppAirBnB.Util.Utilitarios.CreateGenericErrorExceptionDetail(), UTN.Winform.AppAirBnB.Util.Utilitarios.CreateSQLExceptionsErrorDetails(), UTN.Winform.AppAirBnB.Layers.Persistencia.IDataBase.ExecuteReader(), UTN.Winform.AppAirBnB.Layers.Entities.Huesped.ID, UTN.Winform.AppAirBnB.Layers.Entities.Usuario.Login, UTN.Winform.AppAirBnB.Layers.Entities.Huesped.Nombre, UTN.Winform.AppAirBnB.Layers.Entities.Usuario.Password, and UTN.Winform.AppAirBnB.Layers.Entities.Huesped.Telefono.
         {
             DataSet ds = null;
             List<Huesped> lista = new List<Huesped>();
             SqlCommand command = new SqlCommand();
                 string sql = @"usp_SELECT_Huesped_All";
                 try
                 {
                     command.CommandText = sql;
                     command.CommandType = CommandType.StoredProcedure;
                     using (IDataBase db = FactoryDataBase.CreateDataBase(FactoryConexion.CreateConnection(_Usuario.Login, _Usuario.Password)))
                     {
                         ds = db.ExecuteReader(command, "query");
                     }
                     // Si devolvió filas
                     if (ds.Tables[0].Rows.Count > 0)
                 {
                     foreach (DataRow dr in ds.Tables[0].Rows)
                     {
                         Huesped oHuesped = new Huesped();
                         oHuesped.ID = (int)dr["ID"];
                         oHuesped.Nombre = dr["Nombre"].ToString();
                         oHuesped.Apellido1 = dr["Apellido1"].ToString();
                         oHuesped.Apellido2 = dr["Apellido2"].ToString();
                         oHuesped.Telefono = dr["Telefono"].ToString();
                         oHuesped.Correo = dr["Correo"].ToString();
                         lista.Add(oHuesped);
                     }
                 }
                 return lista;
             }
             catch (SqlException sqlError)
             {
                 StringBuilder msg = new StringBuilder();
                 msg.AppendFormat(Utilitarios.CreateSQLExceptionsErrorDetails(sqlError));
                 msg.AppendFormat("SQL             {0}\n", command.CommandText);
                 _MyLogControlEventos.ErrorFormat("Error {0}", msg.ToString());
                 throw;
             }
             catch (Exception er)
             {
                 StringBuilder msg = new StringBuilder();
                 msg.AppendFormat(Utilitarios.CreateGenericErrorExceptionDetail(er));
                 _MyLogControlEventos.ErrorFormat("Error {0}", msg.ToString());
                 throw;
             }
         }
GetHuespedByFilter()
List<Huesped> UTN.Winform.AppAirBnB.Layers.DAL.DALHuesped.GetHuespedByFilter (string pDescripcion)
Implements UTN.Winform.AppAirBnB.Layers.Interface.IDALHuesped.
Definition at line 129 of file DALHuesped.cs.
References UTN.Winform.AppAirBnB.Layers.Entities.Huesped.Apellido1, UTN.Winform.AppAirBnB.Layers.Entities.Huesped.Apellido2, UTN.Winform.AppAirBnB.Layers.Entities.Huesped.Correo, UTN.Winform.AppAirBnB.Layers.Persistencia.FactoryConexion.CreateConnection(), UTN.Winform.AppAirBnB.Layers.Persistencia.FactoryDataBase.CreateDataBase(), UTN.Winform.AppAirBnB.Util.Utilitarios.CreateGenericErrorExceptionDetail(), UTN.Winform.AppAirBnB.Util.Utilitarios.CreateSQLExceptionsErrorDetails(), UTN.Winform.AppAirBnB.Layers.Persistencia.IDataBase.ExecuteReader(), UTN.Winform.AppAirBnB.Layers.Entities.Huesped.ID, UTN.Winform.AppAirBnB.Layers.Entities.Huesped.IDPais, UTN.Winform.AppAirBnB.Layers.Entities.Usuario.Login, UTN.Winform.AppAirBnB.Layers.Entities.Huesped.Nombre, UTN.Winform.AppAirBnB.Layers.Entities.Usuario.Password, and UTN.Winform.AppAirBnB.Layers.Entities.Huesped.Telefono.
         {
             DataSet ds = null;
             List<Huesped> lista = new List<Huesped>();
             SqlCommand command = new SqlCommand();
             try
             {
                 string sql = @" select * from  Huesped1 WITH (NOLOCK) Where Nombre+Apellido1+Apellido2 like @filtro ";
                 command.Parameters.AddWithValue("@filtro", pDescripcion);
                 command.CommandText = sql;
                 command.CommandType = CommandType.Text;
                 using (IDataBase db = FactoryDataBase.CreateDataBase(FactoryConexion.CreateConnection(_Usuario.Login, _Usuario.Password)))
                 {
                     ds = db.ExecuteReader(command, "query");
                 }
                 // Si devolvió filas
                 if (ds.Tables[0].Rows.Count > 0)
                 {
                     // Iterar en todas las filas y Mapearlas
                     foreach (DataRow dr in ds.Tables[0].Rows)
                     {
                         Huesped oHuesped = new Huesped();
                         oHuesped.ID = (int)dr["ID"];
                         oHuesped.Nombre = dr["Nombre"].ToString();
                         oHuesped.Apellido1 = dr["Apellido1"].ToString();
                         oHuesped.Apellido2 = dr["Apellido2"].ToString();
                         oHuesped.Telefono = dr["Telefono"].ToString();
                         oHuesped.Correo = dr["Correo"].ToString();
                         oHuesped.IDPais = (int)dr["IDPais"];
                         lista.Add(oHuesped);
                     }
                 }
                 return lista;
             }
             catch (SqlException sqlError)
             {
                 StringBuilder msg = new StringBuilder();
                 msg.AppendFormat(Utilitarios.CreateSQLExceptionsErrorDetails(sqlError));
                 msg.AppendFormat("SQL             {0}\n", command.CommandText);
                 _MyLogControlEventos.ErrorFormat("Error {0}", msg.ToString());
                 throw;
             }
             catch (Exception er)
             {
                 StringBuilder msg = new StringBuilder();
                 msg.AppendFormat(Utilitarios.CreateGenericErrorExceptionDetail(er));
                 _MyLogControlEventos.ErrorFormat("Error {0}", msg.ToString());
                 throw;
             }
         }
GetHuespedById()
Huesped UTN.Winform.AppAirBnB.Layers.DAL.DALHuesped.GetHuespedById (double pIdHuesped)
Implements UTN.Winform.AppAirBnB.Layers.Interface.IDALHuesped.
Definition at line 187 of file DALHuesped.cs.
References UTN.Winform.AppAirBnB.Layers.Entities.Huesped.Apellido1, UTN.Winform.AppAirBnB.Layers.Entities.Huesped.Apellido2, UTN.Winform.AppAirBnB.Layers.Entities.Huesped.Correo, UTN.Winform.AppAirBnB.Layers.Persistencia.FactoryConexion.CreateConnection(), UTN.Winform.AppAirBnB.Layers.Persistencia.FactoryDataBase.CreateDataBase(), UTN.Winform.AppAirBnB.Util.Utilitarios.CreateGenericErrorExceptionDetail(), UTN.Winform.AppAirBnB.Util.Utilitarios.CreateSQLExceptionsErrorDetails(), UTN.Winform.AppAirBnB.Layers.Persistencia.IDataBase.ExecuteReader(), UTN.Winform.AppAirBnB.Layers.Entities.Huesped.ID, UTN.Winform.AppAirBnB.Layers.Entities.Huesped.IDPais, UTN.Winform.AppAirBnB.Layers.Entities.Usuario.Login, UTN.Winform.AppAirBnB.Layers.Entities.Huesped.Nombre, UTN.Winform.AppAirBnB.Layers.Entities.Usuario.Password, and UTN.Winform.AppAirBnB.Layers.Entities.Huesped.Telefono.
         {
             DataSet ds = null;
             Huesped oHuesped = new Huesped();
             SqlCommand command = new SqlCommand();
             string sql = @"select * from [Huesped] where ID = @ID";
             try
             {
                 command.Parameters.AddWithValue("@ID", pIdHuesped);
                 command.CommandText = sql;
                 command.CommandType = CommandType.Text;
                 using (IDataBase db = FactoryDataBase.CreateDataBase(FactoryConexion.CreateConnection(_Usuario.Login, _Usuario.Password)))
                 {
                     ds = db.ExecuteReader(command, "query");
                 }
                 // Si devolvió filas
                 if (ds.Tables[0].Rows.Count > 0)
                 {
                     // Iterar en todas las filas y Mapearlas
                     foreach (DataRow dr in ds.Tables[0].Rows)
                     {
                         oHuesped.ID = (int)dr["ID"];
                         oHuesped.Nombre = dr["Nombre"].ToString();
                         oHuesped.Apellido1 = dr["Apellido1"].ToString();
                         oHuesped.Apellido2 = dr["Apellido2"].ToString();
                         oHuesped.Telefono = dr["Telefono"].ToString();
                         oHuesped.Correo = dr["Correo"].ToString();
                         oHuesped.IDPais = (int)dr["IDPais"];
                     }
                 }
                 return oHuesped;
             }
             catch (SqlException sqlError)
             {
                 StringBuilder msg = new StringBuilder();
                 msg.AppendFormat(Utilitarios.CreateSQLExceptionsErrorDetails(sqlError));
                 msg.AppendFormat("SQL             {0}\n", command.CommandText);
                 _MyLogControlEventos.ErrorFormat("Error {0}", msg.ToString());
                 throw;
             }
             catch (Exception er)
             {
                 StringBuilder msg = new StringBuilder();
                 msg.AppendFormat(Utilitarios.CreateGenericErrorExceptionDetail(er));
                 _MyLogControlEventos.ErrorFormat("Error {0}", msg.ToString());
                 throw;
             }
         }
SaveHuesped()
Huesped UTN.Winform.AppAirBnB.Layers.DAL.DALHuesped.SaveHuesped (Huesped oHuesped)
Implements UTN.Winform.AppAirBnB.Layers.Interface.IDALHuesped.
Definition at line 243 of file DALHuesped.cs.
References UTN.Winform.AppAirBnB.Layers.Entities.Huesped.Apellido1, UTN.Winform.AppAirBnB.Layers.Entities.Huesped.Apellido2, UTN.Winform.AppAirBnB.Layers.Entities.Huesped.Correo, UTN.Winform.AppAirBnB.Layers.Persistencia.FactoryConexion.CreateConnection(), UTN.Winform.AppAirBnB.Layers.Persistencia.FactoryDataBase.CreateDataBase(), UTN.Winform.AppAirBnB.Util.Utilitarios.CreateGenericErrorExceptionDetail(), UTN.Winform.AppAirBnB.Util.Utilitarios.CreateSQLExceptionsErrorDetails(), UTN.Winform.AppAirBnB.Layers.Persistencia.IDataBase.ExecuteNonQuery(), UTN.Winform.AppAirBnB.Layers.Entities.Huesped.ID, UTN.Winform.AppAirBnB.Layers.Entities.Huesped.IDPais, UTN.Winform.AppAirBnB.Layers.Entities.Usuario.Login, UTN.Winform.AppAirBnB.Layers.Entities.Huesped.Nombre, UTN.Winform.AppAirBnB.Layers.Entities.Usuario.Password, and UTN.Winform.AppAirBnB.Layers.Entities.Huesped.Telefono.
         {
             Huesped _Huesped = null;
             string sql = @"usp_INSERT_Huesped";
             SqlCommand cmd = new SqlCommand();
             double rows = 0;
             try
             {
                 cmd.Parameters.AddWithValue("@ID", oHuesped.ID);
                 cmd.Parameters.AddWithValue("@Nombre", oHuesped.Nombre);
                 cmd.Parameters.AddWithValue("@Apellido1", oHuesped.Apellido1);
                 cmd.Parameters.AddWithValue("@Apellido2", oHuesped.Apellido2);
                 cmd.Parameters.AddWithValue("@Telefono", oHuesped.Telefono);
                 cmd.Parameters.AddWithValue("@Correo", oHuesped.Correo);
                 cmd.Parameters.AddWithValue("@IDPais", oHuesped.IDPais);
                 cmd.CommandText = sql;
                 cmd.CommandType = CommandType.StoredProcedure;
                 using (IDataBase db = FactoryDataBase.CreateDataBase(FactoryConexion.CreateConnection(_Usuario.Login, _Usuario.Password)))
                 {
                     rows = db.ExecuteNonQuery(cmd, IsolationLevel.ReadCommitted);
                 }
                 // Si devuelve filas quiere decir que se salvo entonces extraerlo
                 if (rows > 0)
                     _Huesped = GetHuespedById(oHuesped.ID);
                 return _Huesped;
             }
             catch (SqlException sqlError)
             {
                 StringBuilder msg = new StringBuilder();
                 msg.AppendFormat(Utilitarios.CreateSQLExceptionsErrorDetails(sqlError));
                 msg.AppendFormat("SQL             {0}\n", cmd.CommandText);
                 _MyLogControlEventos.ErrorFormat("Error {0}", msg.ToString());
                 throw;
             }
             catch (Exception er)
             {
                 StringBuilder msg = new StringBuilder();
                 msg.AppendFormat(Utilitarios.CreateGenericErrorExceptionDetail(er));
                 _MyLogControlEventos.ErrorFormat("Error {0}", msg.ToString());
                 throw;
             }
         }
UpdateHuesped()
Huesped UTN.Winform.AppAirBnB.Layers.DAL.DALHuesped.UpdateHuesped (Huesped pHuesped)
Implements UTN.Winform.AppAirBnB.Layers.Interface.IDALHuesped.
Definition at line 296 of file DALHuesped.cs.
References UTN.Winform.AppAirBnB.Layers.Entities.Huesped.Apellido1, UTN.Winform.AppAirBnB.Layers.Entities.Huesped.Apellido2, UTN.Winform.AppAirBnB.Layers.Entities.Huesped.Correo, UTN.Winform.AppAirBnB.Layers.Persistencia.FactoryConexion.CreateConnection(), UTN.Winform.AppAirBnB.Layers.Persistencia.FactoryDataBase.CreateDataBase(), UTN.Winform.AppAirBnB.Util.Utilitarios.CreateGenericErrorExceptionDetail(), UTN.Winform.AppAirBnB.Util.Utilitarios.CreateSQLExceptionsErrorDetails(), UTN.Winform.AppAirBnB.Layers.Persistencia.IDataBase.ExecuteNonQuery(), UTN.Winform.AppAirBnB.Layers.Entities.Huesped.ID, UTN.Winform.AppAirBnB.Layers.Entities.Huesped.IDPais, UTN.Winform.AppAirBnB.Layers.Entities.Usuario.Login, UTN.Winform.AppAirBnB.Layers.Entities.Huesped.Nombre, UTN.Winform.AppAirBnB.Layers.Entities.Usuario.Password, and UTN.Winform.AppAirBnB.Layers.Entities.Huesped.Telefono.
         {
             Huesped _Huesped = null;
             string sql = @"usp_UPDATE_Huesped";
             SqlCommand cmd = new SqlCommand();
             double rows = 0;
             try
             {
                 cmd.Parameters.AddWithValue("@ID", pHuesped.ID);
                 cmd.Parameters.AddWithValue("@Nombre", pHuesped.Nombre);
                 cmd.Parameters.AddWithValue("@Apellido1", pHuesped.Apellido1);
                 cmd.Parameters.AddWithValue("@Apellido2", pHuesped.Apellido2);
                 cmd.Parameters.AddWithValue("@Telefono", pHuesped.Telefono);
                 cmd.Parameters.AddWithValue("@Correo", pHuesped.Correo);
                 cmd.Parameters.AddWithValue("@IDPais", pHuesped.IDPais);
                 cmd.CommandText = sql;
                 cmd.CommandType = CommandType.StoredProcedure;
                 using (IDataBase db = FactoryDataBase.CreateDataBase(FactoryConexion.CreateConnection(_Usuario.Login, _Usuario.Password)))
                 {
                     rows = db.ExecuteNonQuery(cmd, IsolationLevel.ReadCommitted);
                 }
                 // Si devuelve filas quiere decir que se salvo entonces extraerlo
                 if (rows > 0)
                     _Huesped = GetHuespedById(pHuesped.ID);
                 return _Huesped;
             }
             catch (SqlException sqlError)
             {
                 StringBuilder msg = new StringBuilder();
                 msg.AppendFormat(Utilitarios.CreateSQLExceptionsErrorDetails(sqlError));
                 msg.AppendFormat("SQL             {0}\n", cmd.CommandText);
                 _MyLogControlEventos.ErrorFormat("Error {0}", msg.ToString());
                 throw;
             }
             catch (Exception er)
             {
                 StringBuilder msg = new StringBuilder();
                 msg.AppendFormat(Utilitarios.CreateGenericErrorExceptionDetail(er));
                 _MyLogControlEventos.ErrorFormat("Error {0}", msg.ToString());
                 throw;
             }
         }
Member Data Documentation
_MyLogControlEventos
readonly ILog UTN.Winform.AppAirBnB.Layers.DAL.DALHuesped._MyLogControlEventos = LogManager.GetLogger("MyControlEventos") static private
Definition at line 20 of file DALHuesped.cs.
_Usuario
Usuario UTN.Winform.AppAirBnB.Layers.DAL.DALHuesped._Usuario = new Usuario() private
Definition at line 22 of file DALHuesped.cs.
The documentation for this class was generated from the following file:
C:/Users/JorgeMario/Desktop/Proyecto Programado Cuatrimestre I 2018 v4/AppAirBnB/AppAirBnB/Layers/DAL/DALHuesped.cs