AppAirBnB: UTN.Winform.AppAirBnB.Layers.BLL.BLLSysUserRolDTO Class Reference
UTN.Winform.AppAirBnB.Layers.BLL.BLLSysUserRolDTO Class Reference
Public Member Functions
bool DeleteSysUser (string pId)
List< SysUserRolDTO > GetAllSysUser ()
List< SysUser > GetSysUserByFilter (string pDescripcion)
SysUser GetSysUserById (double pId)
SysUser SaveSysUser (SysUser pSysUser)
Detailed Description
Definition at line 13 of file BLLSysUserRolDTO.cs.
Member Function Documentation
DeleteSysUser()
bool UTN.Winform.AppAirBnB.Layers.BLL.BLLSysUserRolDTO.DeleteSysUser (string pId)
Implements UTN.Winform.AppAirBnB.Layers.Interface.IBLLSysUserRolDTO.
Definition at line 16 of file BLLSysUserRolDTO.cs.
References UTN.Winform.AppAirBnB.Layers.Interface.IDALSysUserRolDTO.DeleteSysUser().
         {
             IDALSysUserRolDTO _IDALSysUserRolDTO = new DALSysUserRolDTO();
             return _IDALSysUserRolDTO.DeleteSysUser(pId);
         }
GetAllSysUser()
List<SysUserRolDTO> UTN.Winform.AppAirBnB.Layers.BLL.BLLSysUserRolDTO.GetAllSysUser ()
Implements UTN.Winform.AppAirBnB.Layers.Interface.IBLLSysUserRolDTO.
Definition at line 22 of file BLLSysUserRolDTO.cs.
References UTN.Winform.AppAirBnB.Layers.Interface.IDALSysUserRolDTO.GetAllSysUser().
         {
             IDALSysUserRolDTO _IDALSysUserRolDTO = new DALSysUserRolDTO();
             return _IDALSysUserRolDTO.GetAllSysUser();
         }
GetSysUserByFilter()
List<SysUser> UTN.Winform.AppAirBnB.Layers.BLL.BLLSysUserRolDTO.GetSysUserByFilter (string pDescripcion)
Implements UTN.Winform.AppAirBnB.Layers.Interface.IBLLSysUserRolDTO.
Definition at line 29 of file BLLSysUserRolDTO.cs.
References UTN.Winform.AppAirBnB.Layers.Interface.IDALSysUserRolDTO.GetSysUserByFilter().
         {
             IDALSysUserRolDTO _IDALSysUserRolDTO = new DALSysUserRolDTO();
             return _IDALSysUserRolDTO.GetSysUserByFilter(pDescripcion);
         }
GetSysUserById()
SysUser UTN.Winform.AppAirBnB.Layers.BLL.BLLSysUserRolDTO.GetSysUserById (double pId)
Implements UTN.Winform.AppAirBnB.Layers.Interface.IBLLSysUserRolDTO.
Definition at line 35 of file BLLSysUserRolDTO.cs.
References UTN.Winform.AppAirBnB.Layers.Interface.IDALSysUserRolDTO.GetSysUserById().
         {
             IDALSysUserRolDTO _IDALSysUserRolDTO = new DALSysUserRolDTO();
             return _IDALSysUserRolDTO.GetSysUserById(pId);
         }
SaveSysUser()
SysUser UTN.Winform.AppAirBnB.Layers.BLL.BLLSysUserRolDTO.SaveSysUser (SysUser pSysUser)
Implements UTN.Winform.AppAirBnB.Layers.Interface.IBLLSysUserRolDTO.
Definition at line 41 of file BLLSysUserRolDTO.cs.
References UTN.Winform.AppAirBnB.Layers.Interface.IDALSysUserRolDTO.GetSysUserById(), UTN.Winform.AppAirBnB.Layers.Entities.SysUser.IDUser, UTN.Winform.AppAirBnB.Layers.Interface.IDALSysUserRolDTO.SaveSysUser(), and UTN.Winform.AppAirBnB.Layers.Interface.IDALSysUserRolDTO.UpdateSysUser().
         {
             IDALSysUserRolDTO _IDALSysUserRolDTO = new DALSysUserRolDTO();
             SysUser oSysUser = null;
             if (_IDALSysUserRolDTO.GetSysUserById(pSysUser.IDUser) == null)
                 oSysUser = _IDALSysUserRolDTO.SaveSysUser(pSysUser);
             else
                 oSysUser = _IDALSysUserRolDTO.UpdateSysUser(pSysUser);
             return oSysUser;
         }
The documentation for this class was generated from the following file:
C:/Users/JorgeMario/Desktop/Proyecto Programado Cuatrimestre I 2018 v4/AppAirBnB/AppAirBnB/Layers/BLL/BLLSysUserRolDTO.cs