AppAirBnB: UTN.Winform.AppAirBnB.Layers.BLL.BLLReservacion Class Reference
UTN.Winform.AppAirBnB.Layers.BLL.BLLReservacion Class Reference
Public Member Functions
int GetNextNumeroReserva ()
int GetCurrentNumeroReserva ()
void SaveReserva (Reservacion pReserva)
List< Reservacion > GetAllReservacion ()
Reservacion GetReserva (double pNumeroReserva)
bool DeleteReserva (double pId)
Detailed Description
Definition at line 12 of file BLLReservacion.cs.
Member Function Documentation
DeleteReserva()
bool UTN.Winform.AppAirBnB.Layers.BLL.BLLReservacion.DeleteReserva (double pId)
Implements UTN.Winform.AppAirBnB.Layers.Interface.IBLLReservacion.
Definition at line 49 of file BLLReservacion.cs.
References UTN.Winform.AppAirBnB.Layers.Interface.IDALReservacion.DeleteReserva().
         {
             IDALReservacion _IDALReservacion = new DALReservacion();
             return _IDALReservacion.DeleteReserva(pId);
         }
GetAllReservacion()
List<Reservacion> UTN.Winform.AppAirBnB.Layers.BLL.BLLReservacion.GetAllReservacion ()
Implements UTN.Winform.AppAirBnB.Layers.Interface.IBLLReservacion.
Definition at line 35 of file BLLReservacion.cs.
References UTN.Winform.AppAirBnB.Layers.Interface.IDALReservacion.GetAllReservacion().
         {
             IDALReservacion _IDALReservacion = new DALReservacion();
             return _IDALReservacion.GetAllReservacion();
         }
GetCurrentNumeroReserva()
int UTN.Winform.AppAirBnB.Layers.BLL.BLLReservacion.GetCurrentNumeroReserva ()
Implements UTN.Winform.AppAirBnB.Layers.Interface.IBLLReservacion.
Definition at line 21 of file BLLReservacion.cs.
References UTN.Winform.AppAirBnB.Layers.Interface.IDALReservacion.GetCurrentNumeroReserva().
         {
             IDALReservacion _DALReservacion = new DALReservacion();
             return _DALReservacion.GetCurrentNumeroReserva();
         }
GetNextNumeroReserva()
int UTN.Winform.AppAirBnB.Layers.BLL.BLLReservacion.GetNextNumeroReserva ()
Implements UTN.Winform.AppAirBnB.Layers.Interface.IBLLReservacion.
Definition at line 15 of file BLLReservacion.cs.
References UTN.Winform.AppAirBnB.Layers.Interface.IDALReservacion.GetNextNumeroReserva().
         {
             IDALReservacion _DALReservacion = new DALReservacion();
             return _DALReservacion.GetNextNumeroReserva();
         }
GetReserva()
Reservacion UTN.Winform.AppAirBnB.Layers.BLL.BLLReservacion.GetReserva (double pNumeroReserva)
Implements UTN.Winform.AppAirBnB.Layers.Interface.IBLLReservacion.
Definition at line 41 of file BLLReservacion.cs.
References UTN.Winform.AppAirBnB.Layers.Interface.IDALReservacion.GetReserva().
         {
             IDALReservacion _IDALReservacion = new DALReservacion();
             return _IDALReservacion.GetReserva(pNumeroReserva);
         }
SaveReserva()
void UTN.Winform.AppAirBnB.Layers.BLL.BLLReservacion.SaveReserva (Reservacion pReserva)
Implements UTN.Winform.AppAirBnB.Layers.Interface.IBLLReservacion.
Definition at line 27 of file BLLReservacion.cs.
References UTN.Winform.AppAirBnB.Layers.Interface.IDALReservacion.SaveReserva().
         {
             IDALReservacion _DALReservacion = new DALReservacion();
             _DALReservacion.SaveReserva(pReserva);
         }
The documentation for this class was generated from the following file:
C:/Users/JorgeMario/Desktop/Proyecto Programado Cuatrimestre I 2018 v4/AppAirBnB/AppAirBnB/Layers/BLL/BLLReservacion.cs