AppAirBnB: UTN.Winform.AppAirBnB.Layers.BLL.BLLEncFactura Class Reference
UTN.Winform.AppAirBnB.Layers.BLL.BLLEncFactura Class Reference
Public Member Functions
int GetCurrentNumeroFactura ()
EncFactura GetFactura (double pNumeroFactura)
int GetNextNumeroFactura ()
EncFactura SaveFactura (EncFactura pFactura)
Detailed Description
Definition at line 12 of file BLLEncFactura.cs.
Member Function Documentation
GetCurrentNumeroFactura()
int UTN.Winform.AppAirBnB.Layers.BLL.BLLEncFactura.GetCurrentNumeroFactura ()
Implements UTN.Winform.AppAirBnB.Layers.Interface.IBLLEncFactura.
Definition at line 15 of file BLLEncFactura.cs.
References UTN.Winform.AppAirBnB.Layers.Interface.IDALEncFactura.GetCurrentNumeroFactura().
         {
             IDALEncFactura _DALFactura = new DALEncFactura();
             return _DALFactura.GetCurrentNumeroFactura();
         }
GetFactura()
EncFactura UTN.Winform.AppAirBnB.Layers.BLL.BLLEncFactura.GetFactura (double pNumeroFactura)
Implements UTN.Winform.AppAirBnB.Layers.Interface.IBLLEncFactura.
Definition at line 21 of file BLLEncFactura.cs.
References UTN.Winform.AppAirBnB.Layers.Interface.IDALEncFactura.GetFactura().
         {
             IDALEncFactura _DALFactura = new DALEncFactura();
             return _DALFactura.GetFactura(pNumeroFactura);
         }
GetNextNumeroFactura()
int UTN.Winform.AppAirBnB.Layers.BLL.BLLEncFactura.GetNextNumeroFactura ()
Implements UTN.Winform.AppAirBnB.Layers.Interface.IBLLEncFactura.
Definition at line 27 of file BLLEncFactura.cs.
References UTN.Winform.AppAirBnB.Layers.Interface.IDALEncFactura.GetNextNumeroFactura().
         {
             IDALEncFactura _DALFactura = new DALEncFactura();
             return _DALFactura.GetNextNumeroFactura();
         }
SaveFactura()
EncFactura UTN.Winform.AppAirBnB.Layers.BLL.BLLEncFactura.SaveFactura (EncFactura pFactura)
Implements UTN.Winform.AppAirBnB.Layers.Interface.IBLLEncFactura.
Definition at line 33 of file BLLEncFactura.cs.
References UTN.Winform.AppAirBnB.Layers.Interface.IDALEncFactura.SaveFactura().
         {
             IDALEncFactura _IDALEncFactura = new DALEncFactura();
             return _IDALEncFactura.SaveFactura(pFactura);
         }
The documentation for this class was generated from the following file:
C:/Users/JorgeMario/Desktop/Proyecto Programado Cuatrimestre I 2018 v4/AppAirBnB/AppAirBnB/Layers/BLL/BLLEncFactura.cs