AppAirBnB: UTN.Winform.AppAirBnB.Layers.DAL.DALEncFactura Class Reference
UTN.Winform.AppAirBnB.Layers.DAL.DALEncFactura Class Reference
Public Member Functions
DALEncFactura ()
EncFactura SaveFactura (EncFactura pFactura)
int GetNextNumeroFactura ()
Extraer un consecutivo para asignar el numero de factura Investigue como crear secuencias en SQLServer http://technet.microsoft.com/es-es/library/ff878091.aspx CREATE SEQUENCE SecuenciaNoFactura START WITH 1 INCREMENT BY 1 ;
int GetCurrentNumeroFactura ()
EncFactura GetFactura (double pNumeroFactura)
Private Attributes
Usuario _Usuario = new Usuario()
Static Private Attributes
static readonly ILog _MyLogControlEventos = LogManager.GetLogger("MyControlEventos")
Detailed Description
Definition at line 18 of file DALEncFactura.cs.
Constructor & Destructor Documentation
DALEncFactura()
UTN.Winform.AppAirBnB.Layers.DAL.DALEncFactura.DALEncFactura ()
Definition at line 22 of file DALEncFactura.cs.
References UTN.Winform.AppAirBnB.Properties.Settings.Default, UTN.Winform.AppAirBnB.Layers.Entities.Usuario.Login, UTN.Winform.AppAirBnB.Properties.Settings.Login, UTN.Winform.AppAirBnB.Layers.Entities.Usuario.Password, and UTN.Winform.AppAirBnB.Properties.Settings.Password.
         {
             _Usuario.Login = Settings.Default.Login;
             _Usuario.Password = Settings.Default.Password;
         }
Member Function Documentation
GetCurrentNumeroFactura()
int UTN.Winform.AppAirBnB.Layers.DAL.DALEncFactura.GetCurrentNumeroFactura ()
Implements UTN.Winform.AppAirBnB.Layers.Interface.IDALEncFactura.
Definition at line 184 of file DALEncFactura.cs.
References UTN.Winform.AppAirBnB.Layers.Persistencia.FactoryConexion.CreateConnection(), UTN.Winform.AppAirBnB.Layers.Persistencia.FactoryDataBase.CreateDataBase(), UTN.Winform.AppAirBnB.Util.Utilitarios.CreateGenericErrorExceptionDetail(), UTN.Winform.AppAirBnB.Util.Utilitarios.CreateSQLExceptionsErrorDetails(), UTN.Winform.AppAirBnB.Layers.Persistencia.IDataBase.ExecuteReader(), UTN.Winform.AppAirBnB.Layers.Entities.Usuario.Login, and UTN.Winform.AppAirBnB.Layers.Entities.Usuario.Password.
         {
             DataSet ds = null;
             IDbCommand command = new SqlCommand();
             int numeroFactura = 0;
             string sql = @"SELECT current_value FROM sys.sequences WHERE name = 'SequenceNoFactura'  ";
             DataTable dt = null;
             try
             {
                 command.CommandText = sql;
                 command.CommandType = CommandType.Text;
                 using (IDataBase db = FactoryDataBase.CreateDataBase(FactoryConexion.CreateConnection(_Usuario.Login, _Usuario.Password)))
                 {
                     ds = db.ExecuteReader(command, "query");
                 }
                 // Extraer la tabla
                 dt = ds.Tables[0];
                 //Extraer el valor que viene en el DataTable
                 numeroFactura = int.Parse(dt.Rows[0][0].ToString());
                 return numeroFactura;
             }
             catch (SqlException sqlError)
             {
                 StringBuilder msg = new StringBuilder();
                 msg.AppendFormat(Utilitarios.CreateSQLExceptionsErrorDetails(sqlError));
                 msg.AppendFormat("SQL             {0}\n", command.CommandText);
                 _MyLogControlEventos.ErrorFormat("Error {0}", msg.ToString());
                 throw;
             }
             catch (Exception er)
             {
                 StringBuilder msg = new StringBuilder();
                 msg.AppendFormat(Utilitarios.CreateGenericErrorExceptionDetail(er));
                 _MyLogControlEventos.ErrorFormat("Error {0}", msg.ToString());
                 throw;
             }
         }
GetFactura()
EncFactura UTN.Winform.AppAirBnB.Layers.DAL.DALEncFactura.GetFactura (double pNumeroFactura)
Implements UTN.Winform.AppAirBnB.Layers.Interface.IDALEncFactura.
Definition at line 229 of file DALEncFactura.cs.
References UTN.Winform.AppAirBnB.Layers.Entities.DetFactura._EncFactura, UTN.Winform.AppAirBnB.Layers.Entities.DetFactura._Impuesto, UTN.Winform.AppAirBnB.Layers.Entities.DetFactura._Reservacion, UTN.Winform.AppAirBnB.Layers.Entities.EncFactura.AddDetalle(), UTN.Winform.AppAirBnB.Layers.Persistencia.FactoryConexion.CreateConnection(), UTN.Winform.AppAirBnB.Layers.Persistencia.FactoryDataBase.CreateDataBase(), UTN.Winform.AppAirBnB.Util.Utilitarios.CreateGenericErrorExceptionDetail(), UTN.Winform.AppAirBnB.Util.Utilitarios.CreateSQLExceptionsErrorDetails(), UTN.Winform.AppAirBnB.Layers.Persistencia.IDataBase.ExecuteReader(), UTN.Winform.AppAirBnB.Layers.Interface.IDALEncFactura.GetFactura(), UTN.Winform.AppAirBnB.Layers.Interface.IBLLImpuesto.GetImpuesto(), UTN.Winform.AppAirBnB.Layers.Interface.IDALReservacion.GetReserva(), UTN.Winform.AppAirBnB.Layers.Interface.IDALTarjeta.GetTarjetaById(), UTN.Winform.AppAirBnB.Layers.Entities.Usuario.Login, UTN.Winform.AppAirBnB.Layers.Entities.DetFactura.Numero, UTN.Winform.AppAirBnB.Layers.Entities.Usuario.Password, UTN.Winform.AppAirBnB.Layers.Entities.DetFactura.Precio, and UTN.Winform.AppAirBnB.Layers.Entities.Tarjeta.ToString().
         {
             EncFactura oFacturaEncabezado = new EncFactura();
             DataSet ds = null;
             IDALHuesped _DALHuesped = new DALHuesped();
             IDALTarjeta _DALTarjeta = new DALTarjeta();
             IDALReservacion _DALReservacion = new DALReservacion();
             IDALEncFactura _DALEncFactura = new DALEncFactura();
             IBLLImpuesto _BLLImpuestotest = new BLLImpuesto();
             SqlCommand command = new SqlCommand();
             string sql = @"  ";
             sql = @"usp_SELECT_EncFactura_ByID";
             try
             {
                 command.Parameters.AddWithValue("@IDFactura", pNumeroFactura);
                 command.CommandText = sql;
                 command.CommandType = CommandType.StoredProcedure;
                 using (IDataBase db = FactoryDataBase.CreateDataBase(FactoryConexion.CreateConnection(_Usuario.Login, _Usuario.Password)))
                 {
                     ds = db.ExecuteReader(command, "query");
                 }
                 // Si devolvió filas
                 if (ds.Tables[0].Rows.Count > 0)
                 {
                     DataRow dr = ds.Tables[0].Rows[0];
                     oFacturaEncabezado = new EncFactura()
                     {
                         IDFactura = double.Parse(dr["IDFactura"].ToString()),
                         _Tarjeta = _DALTarjeta.GetTarjetaById(int.Parse(dr["IDTarjeta"].ToString())),
                         Fecha = DateTime.Parse(dr["Fecha"].ToString()),
                         EstadoFact = dr["EstadoFact"].ToString()
                     };
                     foreach (var item in ds.Tables[0].Rows)
                     {
                         DetFactura oFacturaDetalle = new DetFactura();
                         oFacturaDetalle._EncFactura = _DALEncFactura.GetFactura(pNumeroFactura);
                         oFacturaDetalle.Numero = int.Parse(dr["Numero"].ToString());
                         oFacturaDetalle.Precio = double.Parse(dr["Precio"].ToString());
                         oFacturaDetalle._Impuesto = _BLLImpuestotest.GetImpuesto();
                         // Enumerar la secuencia
                         oFacturaDetalle._Reservacion = _DALReservacion.GetReserva(pNumeroFactura);
                         // Agregar
                         oFacturaEncabezado.AddDetalle(oFacturaDetalle);
                     }
                 }
                 return oFacturaEncabezado;
             }
             catch (SqlException sqlError)
             {
                 StringBuilder msg = new StringBuilder();
                 msg.AppendFormat(Utilitarios.CreateSQLExceptionsErrorDetails(sqlError));
                 msg.AppendFormat("SQL             {0}\n", command.CommandText);
                 _MyLogControlEventos.ErrorFormat("Error {0}", msg.ToString());
                 throw;
             }
             catch (Exception er)
             {
                 StringBuilder msg = new StringBuilder();
                 msg.AppendFormat(Utilitarios.CreateGenericErrorExceptionDetail(er));
                 _MyLogControlEventos.ErrorFormat("Error {0}", msg.ToString());
                 throw;
             }
         }
GetNextNumeroFactura()
int UTN.Winform.AppAirBnB.Layers.DAL.DALEncFactura.GetNextNumeroFactura ()
Extraer un consecutivo para asignar el numero de factura Investigue como crear secuencias en SQLServer http://technet.microsoft.com/es-es/library/ff878091.aspx CREATE SEQUENCE SecuenciaNoFactura START WITH 1 INCREMENT BY 1 ;
Returns
Num. de factura
Implements UTN.Winform.AppAirBnB.Layers.Interface.IDALEncFactura.
Definition at line 140 of file DALEncFactura.cs.
References UTN.Winform.AppAirBnB.Layers.Persistencia.FactoryConexion.CreateConnection(), UTN.Winform.AppAirBnB.Layers.Persistencia.FactoryDataBase.CreateDataBase(), UTN.Winform.AppAirBnB.Util.Utilitarios.CreateGenericErrorExceptionDetail(), UTN.Winform.AppAirBnB.Util.Utilitarios.CreateSQLExceptionsErrorDetails(), UTN.Winform.AppAirBnB.Layers.Persistencia.IDataBase.ExecuteReader(), UTN.Winform.AppAirBnB.Layers.Entities.Usuario.Login, and UTN.Winform.AppAirBnB.Layers.Entities.Usuario.Password.
         {
             DataSet ds = null;
             IDbCommand command = new SqlCommand();
             int numeroFactura = 0;
             string sql = @"SELECT NEXT VALUE FOR SequenceNoFactura";
             DataTable dt = null;
             try
             {
                 command.CommandText = sql;
                 command.CommandType = CommandType.Text;
                 using (IDataBase db = FactoryDataBase.CreateDataBase(FactoryConexion.CreateConnection(_Usuario.Login, _Usuario.Password)))
                 {
                     ds = db.ExecuteReader(command, "query");
                 }
                 // Extraer la tabla
                 dt = ds.Tables[0];
                 //Extraer el valor que viene en el DataTable
                 numeroFactura = int.Parse(dt.Rows[0][0].ToString());
                 return numeroFactura;
             }
             catch (SqlException sqlError)
             {
                 StringBuilder msg = new StringBuilder();
                 msg.AppendFormat(Utilitarios.CreateSQLExceptionsErrorDetails(sqlError));
                 msg.AppendFormat("SQL             {0}\n", command.CommandText);
                 _MyLogControlEventos.ErrorFormat("Error {0}", msg.ToString());
                 throw;
             }
             catch (Exception er)
             {
                 StringBuilder msg = new StringBuilder();
                 msg.AppendFormat(Utilitarios.CreateGenericErrorExceptionDetail(er));
                 _MyLogControlEventos.ErrorFormat("Error {0}", msg.ToString());
                 throw;
             }
         }
SaveFactura()
EncFactura UTN.Winform.AppAirBnB.Layers.DAL.DALEncFactura.SaveFactura (EncFactura pFactura)
Implements UTN.Winform.AppAirBnB.Layers.Interface.IDALEncFactura.
Definition at line 27 of file DALEncFactura.cs.
References UTN.Winform.AppAirBnB.Layers.Entities.DetFactura._Impuesto, UTN.Winform.AppAirBnB.Layers.Entities.EncFactura._ListaFacturaDetalle, UTN.Winform.AppAirBnB.Layers.Entities.DetFactura._Reservacion, UTN.Winform.AppAirBnB.Layers.Entities.EncFactura._Tarjeta, UTN.Winform.AppAirBnB.Layers.Persistencia.FactoryConexion.CreateConnection(), UTN.Winform.AppAirBnB.Layers.Persistencia.FactoryDataBase.CreateDataBase(), UTN.Winform.AppAirBnB.Util.Utilitarios.CreateGenericErrorExceptionDetail(), UTN.Winform.AppAirBnB.Util.Utilitarios.CreateSQLExceptionsErrorDetails(), UTN.Winform.AppAirBnB.Layers.Entities.EncFactura.EstadoFact, UTN.Winform.AppAirBnB.Layers.Persistencia.IDataBase.ExecuteNonQuery(), UTN.Winform.AppAirBnB.Layers.Entities.Reservacion.ID, UTN.Winform.AppAirBnB.Layers.Entities.Tarjeta.ID, UTN.Winform.AppAirBnB.Layers.Entities.EncFactura.IDFactura, UTN.Winform.AppAirBnB.Layers.Entities.Usuario.Login, UTN.Winform.AppAirBnB.Layers.Entities.DetFactura.Numero, UTN.Winform.AppAirBnB.Layers.Entities.Usuario.Password, UTN.Winform.AppAirBnB.Layers.Entities.Impuesto.Porcentaje, and UTN.Winform.AppAirBnB.Layers.Entities.Reservacion.Subtotal.
         {
             EncFactura oFacturaEncabezado = new EncFactura();
             IBLLTarjeta _BLLTarjeta = new BLLTarjeta();
             string sqlEncabezado = string.Empty;
             string sqlDetalle = string.Empty;
             string sqlHabitacion = string.Empty;
             SqlCommand cmdFacturaEncabezado = new SqlCommand();
             SqlCommand cmdFacturaDetalle = new SqlCommand();
             SqlCommand cmdHabitacion = new SqlCommand();
             List<IDbCommand> listaCommands = new List<IDbCommand>();
             double rows = 0;
             sqlEncabezado = @"usp_INSERT_EncFactura";
             try
             {
                 // Encabezado de factura
                 cmdFacturaEncabezado.Parameters.AddWithValue("@IDFactura", pFactura.IDFactura);
                 cmdFacturaEncabezado.Parameters.AddWithValue("@IDTarjeta", pFactura._Tarjeta.ID);
                 cmdFacturaEncabezado.Parameters.AddWithValue("@Fecha", DateTime.Now);
                 cmdFacturaEncabezado.Parameters.AddWithValue("@EstadoFact", pFactura.EstadoFact);
                 cmdFacturaEncabezado.CommandText = sqlEncabezado;
                 cmdFacturaEncabezado.CommandType = CommandType.StoredProcedure;
                 // Agregar a la lista de commands
                 listaCommands.Add(cmdFacturaEncabezado);
                 // Detalle de factura
                 // Guardar el detalle de la factura y a la vez rebajar el saldo del producto en Electronico
                 foreach (DetFactura pFacturaDetalle in pFactura._ListaFacturaDetalle)
                 {
                     sqlDetalle = @"usp_INSERT_DetFactura";
                     cmdFacturaDetalle = new SqlCommand();
                     cmdFacturaDetalle.Parameters.AddWithValue("@IDFactura", GetCurrentNumeroFactura());
                     cmdFacturaDetalle.Parameters.AddWithValue("@Numero", pFacturaDetalle.Numero);
                     cmdFacturaDetalle.Parameters.AddWithValue("@Precio", pFacturaDetalle._Reservacion.Subtotal);
                     cmdFacturaDetalle.Parameters.AddWithValue("@Impuesto", pFacturaDetalle._Impuesto.Porcentaje);
                     cmdFacturaDetalle.Parameters.AddWithValue("@IDReservacion", pFacturaDetalle._Reservacion.ID);
                     cmdFacturaDetalle.CommandText = sqlDetalle;
                     cmdFacturaDetalle.CommandType = CommandType.StoredProcedure;
                     // Agregar a la lista de comandos
                     listaCommands.Add(cmdFacturaDetalle);
                     // Cambiar
                     //cmdHabitacion = new SqlCommand();
                     //cmdHabitacion.Parameters.AddWithValue("@NUM", pFacturaDetalle._Reservacion._Habitacion.NUM);
                     //cmdHabitacion.Parameters.AddWithValue("@Estado", 1);
                     //sqlHabitacion = @"usp_UPDATE_Habitacion";
                     //cmdHabitacion.CommandText = sqlHabitacion;
                     //cmdHabitacion.CommandType = CommandType.StoredProcedure;
                     //listaCommands.Add(cmdHabitacion);
                 }
                 using (IDataBase db = FactoryDataBase.CreateDataBase(FactoryConexion.CreateConnection(_Usuario.Login, _Usuario.Password)))
                 {
                     rows = db.ExecuteNonQuery(listaCommands, IsolationLevel.ReadCommitted);
                 }
                 // Si devuelve filas quiere decir que se salvo entonces extraerlo
                 if (rows == 0)
                 {
                     throw new Exception("No se pudo  correctamente la factura");
                 }
                 else
                 {
                     //oFacturaEncabezado = GetFactura(pFactura.IDFactura);
                 }
                 return oFacturaEncabezado;
             }
             catch (SqlException sqlError)
             {
                 StringBuilder msg = new StringBuilder();
                 msg.AppendFormat(Utilitarios.CreateSQLExceptionsErrorDetails(sqlError));
                 msg.AppendFormat("SQL             {0}\n", cmdFacturaEncabezado.CommandText);
                 msg.AppendFormat("SQL             {0}\n", cmdFacturaDetalle.CommandText);
                 msg.AppendFormat("SQL             {0}\n", cmdHabitacion.CommandText);
                 _MyLogControlEventos.ErrorFormat("Error {0}", msg.ToString());
                 throw;
             }
             catch (Exception er)
             {
                 StringBuilder msg = new StringBuilder();
                 msg.AppendFormat(Utilitarios.CreateGenericErrorExceptionDetail(er));
                 _MyLogControlEventos.ErrorFormat("Error {0}", msg.ToString());
                 throw;
             }
         }
Member Data Documentation
_MyLogControlEventos
readonly ILog UTN.Winform.AppAirBnB.Layers.DAL.DALEncFactura._MyLogControlEventos = LogManager.GetLogger("MyControlEventos") static private
Definition at line 20 of file DALEncFactura.cs.
_Usuario
Usuario UTN.Winform.AppAirBnB.Layers.DAL.DALEncFactura._Usuario = new Usuario() private
Definition at line 21 of file DALEncFactura.cs.
The documentation for this class was generated from the following file:
C:/Users/JorgeMario/Desktop/Proyecto Programado Cuatrimestre I 2018 v4/AppAirBnB/AppAirBnB/Layers/DAL/DALEncFactura.cs