AppAirBnB: UTN.Winform.AppAirBnB.Layers.DAL.DALReservacion Class Reference
UTN.Winform.AppAirBnB.Layers.DAL.DALReservacion Class Reference
Public Member Functions
DALReservacion ()
void SaveReserva (Reservacion pReserva)
int GetNextNumeroReserva ()
int GetCurrentNumeroReserva ()
Reservacion GetReserva (double pNumeroReserva)
List< Reservacion > GetAllReservacion ()
bool DeleteReserva (double pId)
Private Attributes
Usuario _Usuario = new Usuario()
Static Private Attributes
static readonly ILog _MyLogControlEventos = LogManager.GetLogger("MyControlEventos")
Detailed Description
Definition at line 17 of file DALReservacion.cs.
Constructor & Destructor Documentation
DALReservacion()
UTN.Winform.AppAirBnB.Layers.DAL.DALReservacion.DALReservacion ()
Definition at line 23 of file DALReservacion.cs.
References UTN.Winform.AppAirBnB.Properties.Settings.Default, UTN.Winform.AppAirBnB.Layers.Entities.Usuario.Login, UTN.Winform.AppAirBnB.Properties.Settings.Login, UTN.Winform.AppAirBnB.Layers.Entities.Usuario.Password, and UTN.Winform.AppAirBnB.Properties.Settings.Password.
         {
             _Usuario.Login = Settings.Default.Login;
             _Usuario.Password = Settings.Default.Password;
         }
Member Function Documentation
DeleteReserva()
bool UTN.Winform.AppAirBnB.Layers.DAL.DALReservacion.DeleteReserva (double pId)
string sql = "Delete from Cliente Where (IdCliente =) ";
Implements UTN.Winform.AppAirBnB.Layers.Interface.IDALReservacion.
Definition at line 338 of file DALReservacion.cs.
References UTN.Winform.AppAirBnB.Layers.Persistencia.FactoryConexion.CreateConnection(), UTN.Winform.AppAirBnB.Layers.Persistencia.FactoryDataBase.CreateDataBase(), UTN.Winform.AppAirBnB.Util.Utilitarios.CreateGenericErrorExceptionDetail(), UTN.Winform.AppAirBnB.Util.Utilitarios.CreateSQLExceptionsErrorDetails(), UTN.Winform.AppAirBnB.Layers.Persistencia.IDataBase.ExecuteNonQuery(), UTN.Winform.AppAirBnB.Layers.Entities.Usuario.Login, and UTN.Winform.AppAirBnB.Layers.Entities.Usuario.Password.
         {
             bool retorno = false;
             double rows = 0d;
             SqlCommand command = new SqlCommand();
             try
             {
                 string sql = "usp_DELETE_Reservacion_ByID";
                 command.Parameters.AddWithValue("@ID", pId);
                 command.CommandText = sql;
                 command.CommandType = CommandType.StoredProcedure;
                 using (IDataBase db = FactoryDataBase.CreateDataBase(FactoryConexion.CreateConnection(_Usuario.Login, _Usuario.Password)))
                 {
                     rows = db.ExecuteNonQuery(command, IsolationLevel.ReadCommitted);
                 }
                 // Si devuelve filas quiere decir que se salvo entonces extraerlo
                 if (rows > 0)
                     retorno = true;
                 return retorno;
             }
             catch (SqlException sqlError)
             {
                 StringBuilder msg = new StringBuilder();
                 msg.AppendFormat(Utilitarios.CreateSQLExceptionsErrorDetails(sqlError));
                 msg.AppendFormat("SQL             {0}\n", command.CommandText);
                 _MyLogControlEventos.ErrorFormat("Error {0}", msg.ToString());
                 throw;
             }
             catch (Exception er)
             {
                 StringBuilder msg = new StringBuilder();
                 msg.AppendFormat(Utilitarios.CreateGenericErrorExceptionDetail(er));
                 _MyLogControlEventos.ErrorFormat("Error {0}", msg.ToString());
                 throw;
             }
         }
GetAllReservacion()
List<Reservacion> UTN.Winform.AppAirBnB.Layers.DAL.DALReservacion.GetAllReservacion ()
Implements UTN.Winform.AppAirBnB.Layers.Interface.IDALReservacion.
Definition at line 272 of file DALReservacion.cs.
References UTN.Winform.AppAirBnB.Layers.Persistencia.FactoryConexion.CreateConnection(), UTN.Winform.AppAirBnB.Layers.Persistencia.FactoryDataBase.CreateDataBase(), UTN.Winform.AppAirBnB.Util.Utilitarios.CreateGenericErrorExceptionDetail(), UTN.Winform.AppAirBnB.Util.Utilitarios.CreateSQLExceptionsErrorDetails(), UTN.Winform.AppAirBnB.Layers.Persistencia.IDataBase.ExecuteReader(), UTN.Winform.AppAirBnB.Layers.Interface.IDALHabitacion.GetHabitacionById(), UTN.Winform.AppAirBnB.Layers.Interface.IDALHuesped.GetHuespedById(), UTN.Winform.AppAirBnB.Layers.Entities.Usuario.Login, and UTN.Winform.AppAirBnB.Layers.Entities.Usuario.Password.
         {
             DataSet ds = null;
             List<Reservacion> lista = new List<Reservacion>();
             SqlCommand command = new SqlCommand();
             IDALHabitacion _DALHabitacion = new DALHabitacion();
             IDALHuesped _DALHuesped = new DALHuesped();
             string sql = @"usp_SELECT_Reservacion_All";
             try
             {
                 command.CommandText = sql;
                 command.CommandType = CommandType.StoredProcedure;
                 using (IDataBase db = FactoryDataBase.CreateDataBase(FactoryConexion.CreateConnection(_Usuario.Login, _Usuario.Password)))
                 {
                     ds = db.ExecuteReader(command, "query");
                 }
                 // Si devolvió filas
                 if (ds.Tables[0].Rows.Count > 0)
                 {
                     // Iterar en todas las filas y Mapearlas
                     foreach (DataRow dr in ds.Tables[0].Rows)
                     {
                         Reservacion oReservacion = new Reservacion()
{
                             ID = double.Parse(dr["ID"].ToString()),
                             _Huesped = _DALHuesped.GetHuespedById(double.Parse(dr["IDHuesped"].ToString())),
                             _Habitacion = _DALHabitacion.GetHabitacionById(double.Parse(dr["NUMHabitacion"].ToString())),
                             CheckIN = (DateTime)dr["CheckIN"],
                             CheckOUT = (DateTime)dr["CheckOUT"],
                             CantDias = (int)dr["CantDias"],
                             Subtotal = double.Parse(dr["Subtotal"].ToString())
                         };
                         lista.Add(oReservacion);
                     }
                 }
                 return lista;
             }
             catch (SqlException sqlError)
             {
                 StringBuilder msg = new StringBuilder();
                 msg.AppendFormat(Utilitarios.CreateSQLExceptionsErrorDetails(sqlError));
                 msg.AppendFormat("SQL             {0}\n", command.CommandText);
                 _MyLogControlEventos.ErrorFormat("Error {0}", msg.ToString());
                 throw;
             }
             catch (Exception er)
             {
                 StringBuilder msg = new StringBuilder();
                 msg.AppendFormat(Utilitarios.CreateGenericErrorExceptionDetail(er));
                 _MyLogControlEventos.ErrorFormat("Error {0}", msg.ToString());
                 throw;
             }
         }
GetCurrentNumeroReserva()
int UTN.Winform.AppAirBnB.Layers.DAL.DALReservacion.GetCurrentNumeroReserva ()
Implements UTN.Winform.AppAirBnB.Layers.Interface.IDALReservacion.
Definition at line 151 of file DALReservacion.cs.
References UTN.Winform.AppAirBnB.Layers.Persistencia.FactoryConexion.CreateConnection(), UTN.Winform.AppAirBnB.Layers.Persistencia.FactoryDataBase.CreateDataBase(), UTN.Winform.AppAirBnB.Util.Utilitarios.CreateGenericErrorExceptionDetail(), UTN.Winform.AppAirBnB.Util.Utilitarios.CreateSQLExceptionsErrorDetails(), UTN.Winform.AppAirBnB.Layers.Persistencia.IDataBase.ExecuteReader(), UTN.Winform.AppAirBnB.Layers.Entities.Usuario.Login, and UTN.Winform.AppAirBnB.Layers.Entities.Usuario.Password.
         {
             DataSet ds = null;
             IDbCommand command = new SqlCommand();
             int numeroFactura = 0;
             string sql = @"SELECT current_value FROM sys.sequences WHERE name = 'SequenceNoReserva'  ";
             DataTable dt = null;
             try
             {
                 command.CommandText = sql;
                 command.CommandType = CommandType.Text;
                 using (IDataBase db = FactoryDataBase.CreateDataBase(FactoryConexion.CreateConnection(_Usuario.Login, _Usuario.Password)))
                 {
                     ds = db.ExecuteReader(command, "query");
                 }
                 // Extraer la tabla
                 dt = ds.Tables[0];
                 //Extraer el valor que viene en el DataTable
                 numeroFactura = int.Parse(dt.Rows[0][0].ToString());
                 return numeroFactura;
             }
             catch (SqlException sqlError)
             {
                 StringBuilder msg = new StringBuilder();
                 msg.AppendFormat(Utilitarios.CreateSQLExceptionsErrorDetails(sqlError));
                 msg.AppendFormat("SQL             {0}\n", command.CommandText);
                 _MyLogControlEventos.ErrorFormat("Error {0}", msg.ToString());
                 throw;
             }
             catch (Exception er)
             {
                 StringBuilder msg = new StringBuilder();
                 msg.AppendFormat(Utilitarios.CreateGenericErrorExceptionDetail(er));
                 _MyLogControlEventos.ErrorFormat("Error {0}", msg.ToString());
                 throw;
             }
         }
GetNextNumeroReserva()
int UTN.Winform.AppAirBnB.Layers.DAL.DALReservacion.GetNextNumeroReserva ()
Implements UTN.Winform.AppAirBnB.Layers.Interface.IDALReservacion.
Definition at line 107 of file DALReservacion.cs.
References UTN.Winform.AppAirBnB.Layers.Persistencia.FactoryConexion.CreateConnection(), UTN.Winform.AppAirBnB.Layers.Persistencia.FactoryDataBase.CreateDataBase(), UTN.Winform.AppAirBnB.Util.Utilitarios.CreateGenericErrorExceptionDetail(), UTN.Winform.AppAirBnB.Util.Utilitarios.CreateSQLExceptionsErrorDetails(), UTN.Winform.AppAirBnB.Layers.Persistencia.IDataBase.ExecuteReader(), UTN.Winform.AppAirBnB.Layers.Entities.Usuario.Login, and UTN.Winform.AppAirBnB.Layers.Entities.Usuario.Password.
         {
             DataSet ds = null;
             IDbCommand command = new SqlCommand();
             int numeroReserva = 0;
             string sql = @"SELECT NEXT VALUE FOR SequenceNoReserva";
             DataTable dt = null;
             try
             {
                 command.CommandText = sql;
                 command.CommandType = CommandType.Text;
                 using (IDataBase db = FactoryDataBase.CreateDataBase(FactoryConexion.CreateConnection(_Usuario.Login, _Usuario.Password)))
                 {
                     ds = db.ExecuteReader(command, "query");
                 }
                 // Extraer la tabla
                 dt = ds.Tables[0];
                 //Extraer el valor que viene en el DataTable
                 numeroReserva = int.Parse(dt.Rows[0][0].ToString());
                 return numeroReserva;
             }
             catch (SqlException sqlError)
             {
                 StringBuilder msg = new StringBuilder();
                 msg.AppendFormat(Utilitarios.CreateSQLExceptionsErrorDetails(sqlError));
                 msg.AppendFormat("SQL             {0}\n", command.CommandText);
                 _MyLogControlEventos.ErrorFormat("Error {0}", msg.ToString());
                 throw;
             }
             catch (Exception er)
             {
                 StringBuilder msg = new StringBuilder();
                 msg.AppendFormat(Utilitarios.CreateGenericErrorExceptionDetail(er));
                 _MyLogControlEventos.ErrorFormat("Error {0}", msg.ToString());
                 throw;
             }
         }
GetReserva()
Reservacion UTN.Winform.AppAirBnB.Layers.DAL.DALReservacion.GetReserva (double pNumeroReserva)
Implements UTN.Winform.AppAirBnB.Layers.Interface.IDALReservacion.
Definition at line 196 of file DALReservacion.cs.
References UTN.Winform.AppAirBnB.Layers.Entities.Reservacion._Habitacion, UTN.Winform.AppAirBnB.Layers.Entities.Reservacion._Huesped, UTN.Winform.AppAirBnB.Layers.Entities.Reservacion.CantDias, UTN.Winform.AppAirBnB.Layers.Entities.Reservacion.CheckIN, UTN.Winform.AppAirBnB.Layers.Entities.Reservacion.CheckOUT, UTN.Winform.AppAirBnB.Layers.Persistencia.FactoryConexion.CreateConnection(), UTN.Winform.AppAirBnB.Layers.Persistencia.FactoryDataBase.CreateDataBase(), UTN.Winform.AppAirBnB.Util.Utilitarios.CreateGenericErrorExceptionDetail(), UTN.Winform.AppAirBnB.Util.Utilitarios.CreateSQLExceptionsErrorDetails(), UTN.Winform.AppAirBnB.Layers.Persistencia.IDataBase.ExecuteReader(), UTN.Winform.AppAirBnB.Layers.Interface.IDALHabitacion.GetHabitacionById(), UTN.Winform.AppAirBnB.Layers.Interface.IDALHuesped.GetHuespedById(), UTN.Winform.AppAirBnB.Layers.Entities.Reservacion.ID, UTN.Winform.AppAirBnB.Layers.Entities.Usuario.Login, UTN.Winform.AppAirBnB.Layers.Entities.Usuario.Password, and UTN.Winform.AppAirBnB.Layers.Entities.Reservacion.Subtotal.
         {
             Reservacion oReservacion = new Reservacion();
             DataSet ds = null;
             IDALHabitacion _DALHabitacion = new DALHabitacion();
             IDALHuesped _DALHuesped = new DALHuesped();
             SqlCommand command = new SqlCommand();
             string sql = @" ";
             sql = @"select * from [Reservacion] where ID = @ID";
             try
             {
                 command.CommandText = sql;
                 command.CommandType = CommandType.Text;
                 command.Parameters.AddWithValue("@ID", pNumeroReserva);
                 using (IDataBase db = FactoryDataBase.CreateDataBase(FactoryConexion.CreateConnection(_Usuario.Login, _Usuario.Password)))
                 {
                     ds = db.ExecuteReader(command, "query");
                 }
                 // Si devolvió filas
                 if (ds.Tables[0].Rows.Count > 0)
                 {
                     DataRow dr = ds.Tables[0].Rows[0];
                     oReservacion = new Reservacion()
                     {
                         ID = (int)dr["ID"],
                         _Huesped = _DALHuesped.GetHuespedById(double.Parse(dr["IDHuesped"].ToString())),
                         _Habitacion = _DALHabitacion.GetHabitacionById(double.Parse(dr["NUMHabitacion"].ToString())),
                         CheckIN = (DateTime)(dr["CheckIN"]),
                         CheckOUT = (DateTime)(dr["CheckIN"]),
                         CantDias = (int)dr["CantDias"],
                         Subtotal = double.Parse(dr["Subtotal"].ToString())
                     };
                     foreach (var item in ds.Tables[0].Rows)
                     {
                         oReservacion.ID = double.Parse(dr["ID"].ToString());
                         oReservacion._Huesped = _DALHuesped.GetHuespedById(double.Parse(dr["IDHuesped"].ToString()));
                         oReservacion._Habitacion = _DALHabitacion.GetHabitacionById(double.Parse(dr["NUMHabitacion"].ToString()));
                         oReservacion.CheckIN = (DateTime)(dr["CheckIN"]);
                         oReservacion.CheckOUT = (DateTime)(dr["CheckOUT"]);
                         oReservacion.CantDias = double.Parse(dr["CantDias"].ToString());
                         oReservacion.Subtotal = double.Parse(dr["Subtotal"].ToString());
                     }
                 }
                 return oReservacion;
             }
             catch (SqlException sqlError)
             {
                 StringBuilder msg = new StringBuilder();
                 msg.AppendFormat(Utilitarios.CreateSQLExceptionsErrorDetails(sqlError));
                 msg.AppendFormat("SQL             {0}\n", command.CommandText);
                 _MyLogControlEventos.ErrorFormat("Error {0}", msg.ToString());
                 throw;
             }
             catch (Exception er)
             {
                 StringBuilder msg = new StringBuilder();
                 msg.AppendFormat(Utilitarios.CreateGenericErrorExceptionDetail(er));
                 _MyLogControlEventos.ErrorFormat("Error {0}", msg.ToString());
                 throw;
             }
         }
SaveReserva()
void UTN.Winform.AppAirBnB.Layers.DAL.DALReservacion.SaveReserva (Reservacion pReserva)
Implements UTN.Winform.AppAirBnB.Layers.Interface.IDALReservacion.
Definition at line 31 of file DALReservacion.cs.
References UTN.Winform.AppAirBnB.Layers.Entities.Reservacion._Habitacion, UTN.Winform.AppAirBnB.Layers.Entities.Reservacion._Huesped, UTN.Winform.AppAirBnB.Layers.Entities.Reservacion.CantDias, UTN.Winform.AppAirBnB.Layers.Entities.Reservacion.CheckIN, UTN.Winform.AppAirBnB.Layers.Entities.Reservacion.CheckOUT, UTN.Winform.AppAirBnB.Layers.Persistencia.FactoryConexion.CreateConnection(), UTN.Winform.AppAirBnB.Layers.Persistencia.FactoryDataBase.CreateDataBase(), UTN.Winform.AppAirBnB.Util.Utilitarios.CreateGenericErrorExceptionDetail(), UTN.Winform.AppAirBnB.Util.Utilitarios.CreateSQLExceptionsErrorDetails(), UTN.Winform.AppAirBnB.Layers.Persistencia.IDataBase.ExecuteNonQuery(), UTN.Winform.AppAirBnB.Layers.Entities.Reservacion.ID, UTN.Winform.AppAirBnB.Layers.Entities.Huesped.ID, UTN.Winform.AppAirBnB.Layers.Entities.Usuario.Login, UTN.Winform.AppAirBnB.Layers.Entities.Habitacion.NUM, UTN.Winform.AppAirBnB.Layers.Entities.Usuario.Password, and UTN.Winform.AppAirBnB.Layers.Entities.Reservacion.Subtotal.
         {
             string sqlReserva = string.Empty;
             SqlCommand cmdReservacion = new SqlCommand();
             SqlCommand cmdHabitacion = new SqlCommand();
             List<IDbCommand> listaCommands = new List<IDbCommand>();
             double rows = 0;
             //pReserva.CheckIN = (DateTime)System.Data.SqlTypes.SqlDateTime.MinValue;
             //pReserva.CheckOUT = (DateTime)System.Data.SqlTypes.SqlDateTime.MaxValue;
             sqlReserva = @"usp_INSERT_Reservacion";
             cmdReservacion.CommandType = CommandType.StoredProcedure;
             try
             {
                 // Encabezado de factura
                 cmdReservacion.Parameters.AddWithValue("@ID", pReserva.ID);
                 cmdReservacion.Parameters.AddWithValue("@IDHuesped", pReserva._Huesped.ID);
                 cmdReservacion.Parameters.AddWithValue("@NUMHabitacion", pReserva._Habitacion.NUM);
                 cmdReservacion.Parameters.AddWithValue("@CheckIN", pReserva.CheckIN);
                 cmdReservacion.Parameters.AddWithValue("@CheckOUT", pReserva.CheckOUT);
                 cmdReservacion.Parameters.AddWithValue("@CantDias", pReserva.CantDias);
                 cmdReservacion.Parameters.AddWithValue("@Subtotal", pReserva.Subtotal);
                 cmdReservacion.CommandText = sqlReserva;
                 // Agregar a la lista de commands
                 listaCommands.Add(cmdReservacion);
                 using (IDataBase db = FactoryDataBase.CreateDataBase(FactoryConexion.CreateConnection(_Usuario.Login, _Usuario.Password)))
                 {
                     rows = db.ExecuteNonQuery(listaCommands, IsolationLevel.ReadCommitted);
                 }
                 // Si devuelve filas quiere decir que se salvo entonces extraerlo
                 if (rows == 0)
                 {
                     throw new Exception("No se pudo guardar correctamente la Reserva");
                 }
             }
             catch (SqlException sqlError)
             {
                 StringBuilder msg = new StringBuilder();
                 msg.AppendFormat(Utilitarios.CreateSQLExceptionsErrorDetails(sqlError));
                 msg.AppendFormat("SQL             {0}\n", cmdReservacion.CommandText);
                 _MyLogControlEventos.ErrorFormat("Error {0}", msg.ToString());
                 throw;
             }
             catch (Exception er)
             {
                 StringBuilder msg = new StringBuilder();
                 msg.AppendFormat(Utilitarios.CreateGenericErrorExceptionDetail(er));
                 _MyLogControlEventos.ErrorFormat("Error {0}", msg.ToString());
                 throw;
             }
         }
Member Data Documentation
_MyLogControlEventos
readonly ILog UTN.Winform.AppAirBnB.Layers.DAL.DALReservacion._MyLogControlEventos = LogManager.GetLogger("MyControlEventos") static private
Definition at line 21 of file DALReservacion.cs.
_Usuario
Usuario UTN.Winform.AppAirBnB.Layers.DAL.DALReservacion._Usuario = new Usuario() private
Definition at line 22 of file DALReservacion.cs.
The documentation for this class was generated from the following file:
C:/Users/JorgeMario/Desktop/Proyecto Programado Cuatrimestre I 2018 v4/AppAirBnB/AppAirBnB/Layers/DAL/DALReservacion.cs