AppAirBnB: UTN.Winform.AppAirBnB.Layers.Entities.EncFactura Class Reference
UTN.Winform.AppAirBnB.Layers.Entities.EncFactura Class Reference
Public Member Functions
void AddDetalle (DetFactura pFacturaDetalle)
double GetSubTotal ()
double GetImpuesto ()
Properties
double IDFactura [get, set]
Tarjeta _Tarjeta [get, set]
DateTime Fecha [get, set]
string EstadoFact [get, set]
List< DetFactura > _ListaFacturaDetalle = new List<DetFactura>() [get]
Detailed Description
Definition at line 10 of file EncFactura.cs.
Member Function Documentation
AddDetalle()
void UTN.Winform.AppAirBnB.Layers.Entities.EncFactura.AddDetalle (DetFactura pFacturaDetalle)
Definition at line 20 of file EncFactura.cs.
Referenced by UTN.Winform.AppAirBnB.Layers.UI.Procesos.frmFacturacion.btnAgregar_Click(), UTN.Winform.AppAirBnB.Layers.DAL.DALEncFactura.GetFactura(), and UTN.Winform.AppAirBnB.Layers.UI.Procesos.frmFacturacion.toolStripBtnFacturar_Click().
         {
             _ListaFacturaDetalle.Add(pFacturaDetalle);
         }
GetImpuesto()
double UTN.Winform.AppAirBnB.Layers.Entities.EncFactura.GetImpuesto ()
Definition at line 30 of file EncFactura.cs.
Referenced by UTN.Winform.AppAirBnB.Layers.UI.Procesos.frmFacturacion.toolStripBtnFacturar_Click().
         {
             return _ListaFacturaDetalle.Sum(p => p._Impuesto.Porcentaje) /100 * GetSubTotal();
         }
GetSubTotal()
double UTN.Winform.AppAirBnB.Layers.Entities.EncFactura.GetSubTotal ()
Definition at line 25 of file EncFactura.cs.
Referenced by UTN.Winform.AppAirBnB.Layers.UI.Procesos.frmFacturacion.toolStripBtnFacturar_Click().
         {
             return _ListaFacturaDetalle.Sum(p => p._Reservacion.CantDias * p.Precio);
         }
Property Documentation
_ListaFacturaDetalle
List<DetFactura> UTN.Winform.AppAirBnB.Layers.Entities.EncFactura._ListaFacturaDetalle = new List<DetFactura>() get
Definition at line 18 of file EncFactura.cs.
Referenced by UTN.Winform.AppAirBnB.Layers.UI.Procesos.frmFacturacion.btnAgregar_Click(), UTN.Winform.AppAirBnB.Layers.DAL.DALEncFactura.SaveFactura(), and UTN.Winform.AppAirBnB.Layers.UI.Procesos.frmFacturacion.toolStripBtnFacturar_Click().
 { get; } = new List<DetFactura>();
_Tarjeta
Tarjeta UTN.Winform.AppAirBnB.Layers.Entities.EncFactura._Tarjeta get set
Definition at line 14 of file EncFactura.cs.
Referenced by UTN.Winform.AppAirBnB.Layers.DAL.DALEncFactura.SaveFactura().
 { get; set; }
EstadoFact
string UTN.Winform.AppAirBnB.Layers.Entities.EncFactura.EstadoFact get set
Definition at line 16 of file EncFactura.cs.
Referenced by UTN.Winform.AppAirBnB.Layers.DAL.DALEncFactura.SaveFactura().
 { get; set; }
Fecha
DateTime UTN.Winform.AppAirBnB.Layers.Entities.EncFactura.Fecha get set
Definition at line 15 of file EncFactura.cs.
 { get; set; }
IDFactura
double UTN.Winform.AppAirBnB.Layers.Entities.EncFactura.IDFactura get set
Definition at line 13 of file EncFactura.cs.
Referenced by UTN.Winform.AppAirBnB.Layers.DAL.DALEncFactura.SaveFactura().
 { get; set; }
The documentation for this class was generated from the following file:
C:/Users/JorgeMario/Desktop/Proyecto Programado Cuatrimestre I 2018 v4/AppAirBnB/AppAirBnB/Layers/Entities/EncFactura.cs