AppAirBnB: UTN.Winform.AppAirBnB.Layers.Persistencia.FactoryConexion Class Reference
UTN.Winform.AppAirBnB.Layers.Persistencia.FactoryConexion Class Reference
Static Public Member Functions
static string CreateConnection (String pUsuario, String pContrasena)
static string CreateConnection (string pUsuario, String pContrasena, string pConexion)
Detailed Description
Definition at line 10 of file FactoryConexion.cs.
Member Function Documentation
CreateConnection() [1/2]
static string UTN.Winform.AppAirBnB.Layers.Persistencia.FactoryConexion.CreateConnection (String pUsuario, String pContrasena) static
Definition at line 14 of file FactoryConexion.cs.
Referenced by UTN.Winform.AppAirBnB.Layers.DAL.DALSeguridad.CreateUser(), UTN.Winform.AppAirBnB.Layers.DAL.DALHabitacion.DeleteHabitacion(), UTN.Winform.AppAirBnB.Layers.DAL.DALHuesped.DeleteHuesped(), UTN.Winform.AppAirBnB.Layers.DAL.DALReservacion.DeleteReserva(), UTN.Winform.AppAirBnB.Layers.DAL.DALSysUserRolDTO.DeleteSysUser(), UTN.Winform.AppAirBnB.Layers.DAL.DALHabitacion.GetAllHabitacion(), UTN.Winform.AppAirBnB.Layers.DAL.DALHuesped.GetAllHuesped(), UTN.Winform.AppAirBnB.Layers.DAL.DALPais.GetAllPais(), UTN.Winform.AppAirBnB.Layers.DAL.DALReservacion.GetAllReservacion(), UTN.Winform.AppAirBnB.Layers.DAL.DALSysUserRolDTO.GetAllSysUser(), UTN.Winform.AppAirBnB.Layers.DAL.DALTarjeta.GetAllTarjeta(), UTN.Winform.AppAirBnB.Layers.DAL.DALEncFactura.GetCurrentNumeroFactura(), UTN.Winform.AppAirBnB.Layers.DAL.DALReservacion.GetCurrentNumeroReserva(), UTN.Winform.AppAirBnB.Layers.DAL.DALSeguridad.GetDataBases(), UTN.Winform.AppAirBnB.Layers.DAL.DALEncFactura.GetFactura(), UTN.Winform.AppAirBnB.Layers.DAL.DALHabitacion.GetHabitacionById(), UTN.Winform.AppAirBnB.Layers.DAL.DALHuesped.GetHuespedByFilter(), UTN.Winform.AppAirBnB.Layers.DAL.DALHuesped.GetHuespedById(), UTN.Winform.AppAirBnB.Layers.DAL.DALImpuesto.GetImpuesto(), UTN.Winform.AppAirBnB.Layers.DAL.DALSeguridad.GetLogins(), UTN.Winform.AppAirBnB.Layers.DAL.DALSeguridad.GetLoginsXDataBase(), UTN.Winform.AppAirBnB.Layers.DAL.DALEncFactura.GetNextNumeroFactura(), UTN.Winform.AppAirBnB.Layers.DAL.DALReservacion.GetNextNumeroReserva(), UTN.Winform.AppAirBnB.Layers.DAL.DALReservacion.GetReserva(), UTN.Winform.AppAirBnB.Layers.DAL.DALSysUserRolDTO.GetSysUserByFilter(), UTN.Winform.AppAirBnB.Layers.DAL.DALSysUserRolDTO.GetSysUserById(), UTN.Winform.AppAirBnB.Layers.DAL.DALTarjeta.GetTarjetaById(), UTN.Winform.AppAirBnB.Layers.DAL.DALLogin.Login(), UTN.Winform.AppAirBnB.Layers.DAL.DALEncFactura.SaveFactura(), UTN.Winform.AppAirBnB.Layers.DAL.DALHabitacion.SaveHabitacion(), UTN.Winform.AppAirBnB.Layers.DAL.DALHuesped.SaveHuesped(), UTN.Winform.AppAirBnB.Layers.DAL.DALReservacion.SaveReserva(), UTN.Winform.AppAirBnB.Layers.DAL.DALSysUserRolDTO.SaveSysUser(), UTN.Winform.AppAirBnB.Layers.DAL.DALHabitacion.UpdateHabitacion(), UTN.Winform.AppAirBnB.Layers.DAL.DALHuesped.UpdateHuesped(), and UTN.Winform.AppAirBnB.Layers.DAL.DALSysUserRolDTO.UpdateSysUser().
         {
             StringBuilder conexion = new StringBuilder();
             bool existe = false;
             // Validacion de la conexion
             if (ConfigurationManager.ConnectionStrings.Count == 0)
             {
                 throw new Exception("No existen registradas ConnectionStrings en el archivo app.confi, revise!");
             }
             for (int i = 0; i < ConfigurationManager.ConnectionStrings.Count - 1; i++)
             {
                 if (ConfigurationManager.ConnectionStrings[i].Name.Equals("default", StringComparison.InvariantCultureIgnoreCase))
                     existe = true;
             }
             if (!existe)
             {
                 throw new Exception("No existe registrada en ConnectionStrings del app.config el Key default!");
             }
             // Lee la conexion default
             conexion.AppendFormat("{0}", ConfigurationManager.ConnectionStrings["default"].ConnectionString);
             // Agrega al usuario
             conexion.AppendFormat("User Id={0};Password={1}", pUsuario, pContrasena);
             return conexion.ToString();
         }
CreateConnection() [2/2]
static string UTN.Winform.AppAirBnB.Layers.Persistencia.FactoryConexion.CreateConnection (string pUsuario, String pContrasena, string pConexion) static
Definition at line 45 of file FactoryConexion.cs.
         {
             StringBuilder conexion = new StringBuilder();
             bool existe = false;
             // Validacion de la conexion
             if (ConfigurationManager.ConnectionStrings.Count == 0)
             {
                 throw new Exception("No existen registradas ConnectionStrings en el archivo app.confi, revise!");
             }
             for (int i = 0; i < ConfigurationManager.ConnectionStrings.Count - 1; i++)
             {
                 if (ConfigurationManager.ConnectionStrings[i].Name.Equals(pConexion, StringComparison.InvariantCultureIgnoreCase))
                     existe = true;
             }
             if (!existe)
             {
                 throw new Exception("No existe registrada en ConnectionStrings del app.config el Key default!");
             }
             // Lee la conexion default
             conexion.AppendFormat("{0}", ConfigurationManager.ConnectionStrings[pConexion].ConnectionString);
             // Agrega al usuario
             conexion.AppendFormat("User Id={0};Password={1}", pUsuario, pContrasena);
             return conexion.ToString();
         }
The documentation for this class was generated from the following file:
C:/Users/JorgeMario/Desktop/Proyecto Programado Cuatrimestre I 2018 v4/AppAirBnB/AppAirBnB/Layers/Persistencia/FactoryConexion.cs