AppAirBnB: UTN.Winform.AppAirBnB.Layers.DAL.DALSeguridad Class Reference
UTN.Winform.AppAirBnB.Layers.DAL.DALSeguridad Class Reference
Public Member Functions
DALSeguridad ()
IEnumerable< string > GetDataBases ()
Retorna todas las Bases de Datos
void CreateUser (string pUsuario, string pContrasena, string pBaseDatos)
Crea un usuario dependiendo de la Base de Datos
IEnumerable< string > GetLoginsXDataBase (string pBaseDatos)
Extraer los usuarios por Base de Datos
IEnumerable< string > GetLogins ()
Private Attributes
Usuario _Usuario = new Usuario()
Static Private Attributes
static readonly ILog _MyLogControlEventos = LogManager.GetLogger("MyControlEventos")
Detailed Description
Definition at line 16 of file DALSeguridad.cs.
Constructor & Destructor Documentation
DALSeguridad()
UTN.Winform.AppAirBnB.Layers.DAL.DALSeguridad.DALSeguridad ()
Definition at line 22 of file DALSeguridad.cs.
References UTN.Winform.AppAirBnB.Properties.Settings.Default, UTN.Winform.AppAirBnB.Layers.Entities.Usuario.Login, UTN.Winform.AppAirBnB.Properties.Settings.Login, UTN.Winform.AppAirBnB.Layers.Entities.Usuario.Password, and UTN.Winform.AppAirBnB.Properties.Settings.Password.
         {
             _Usuario.Login = Settings.Default.Login;
             _Usuario.Password = Settings.Default.Password;
         }
Member Function Documentation
CreateUser()
void UTN.Winform.AppAirBnB.Layers.DAL.DALSeguridad.CreateUser (string pUsuario, string pContrasena, string pBaseDatos)
Crea un usuario dependiendo de la Base de Datos
Parameters
pUsuario Usuario
pContrasena Contrasena
pBaseDatos Base de Datos
Implements UTN.Winform.AppAirBnB.Layers.Interface.IDALSeguridad.
Definition at line 83 of file DALSeguridad.cs.
References UTN.Winform.AppAirBnB.Layers.Persistencia.FactoryConexion.CreateConnection(), UTN.Winform.AppAirBnB.Layers.Persistencia.FactoryDataBase.CreateDataBase(), UTN.Winform.AppAirBnB.Layers.Persistencia.IDataBase.ExecuteNonQuery(), UTN.Winform.AppAirBnB.Layers.Entities.Usuario.Login, and UTN.Winform.AppAirBnB.Layers.Entities.Usuario.Password.
         {
             StringBuilder sql = new StringBuilder();
             SqlCommand command = new SqlCommand();
             try
             {
                 sql.AppendFormat("CREATE LOGIN [{0}] WITH PASSWORD=N'{1}', DEFAULT_DATABASE=[{2}],CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF ",
                                   pUsuario, pContrasena, pBaseDatos);
                 sql.AppendFormat("EXEC master..sp_addsrvrolemember @loginame = N'{0}', @rolename = N'sysadmin'   ", pUsuario);
                 sql.AppendFormat("USE [{0}]  ", pBaseDatos);
                 sql.AppendFormat("CREATE USER [{0}] FOR LOGIN [{1}]  ", pUsuario, pUsuario);
                 command.CommandText = sql.ToString();
                 using (IDataBase db = FactoryDataBase.CreateDataBase(FactoryConexion.CreateConnection(_Usuario.Login, _Usuario.Password)))
                 {
                     // Note ExecuteNonQuery NO LLEVA TRANSACCION!!!
                     db.ExecuteNonQuery(command);
                 }
             }
             catch (SqlException sqlError)
             {
                 StringBuilder msg = new StringBuilder();
                 //msg.AppendFormat(Utilitarios.CreateSQLExceptionsErrorDetails(sqlError));
                 msg.AppendFormat("SQL             {0}\n", command.CommandText);
                 _MyLogControlEventos.ErrorFormat("Error {0}", msg.ToString());
                 throw;
             }
             catch (Exception er)
             {
                 StringBuilder msg = new StringBuilder();
                //msg.AppendFormat(Utilitarios.CreateGenericErrorExceptionDetail(er));
                 _MyLogControlEventos.ErrorFormat("Error {0}", msg.ToString());
                 throw;
             }
         }
GetDataBases()
IEnumerable<string> UTN.Winform.AppAirBnB.Layers.DAL.DALSeguridad.GetDataBases ()
Retorna todas las Bases de Datos
Returns
List<string>
Implements UTN.Winform.AppAirBnB.Layers.Interface.IDALSeguridad.
Definition at line 32 of file DALSeguridad.cs.
References UTN.Winform.AppAirBnB.Layers.Persistencia.FactoryConexion.CreateConnection(), UTN.Winform.AppAirBnB.Layers.Persistencia.FactoryDataBase.CreateDataBase(), UTN.Winform.AppAirBnB.Layers.Persistencia.IDataBase.ExecuteReader(), UTN.Winform.AppAirBnB.Layers.Entities.Usuario.Login, and UTN.Winform.AppAirBnB.Layers.Entities.Usuario.Password.
         {
             SqlCommand command = new SqlCommand();
             DataSet ds = null;
             string sql = @"  select * from sys.databases  ";
             List<string> lista = new List<string>();
             try
             {
                 command.CommandText = sql;
                 command.CommandType = CommandType.Text;
                 using (IDataBase db = FactoryDataBase.CreateDataBase(FactoryConexion.CreateConnection(_Usuario.Login, _Usuario.Password)))
                 {
                     ds = db.ExecuteReader(command, "query");
                 }
                 foreach (DataRow row in ds.Tables[0].Rows)
                 {
                     lista.Add(row[0].ToString());
                 }
                 return lista;
             }
             catch (SqlException sqlError)
             {
                 StringBuilder msg = new StringBuilder();
                 //msg.AppendFormat(Utilitarios.CreateSQLExceptionsErrorDetails(sqlError));
                 msg.AppendFormat("SQL             {0}\n", command.CommandText);
                 _MyLogControlEventos.ErrorFormat("Error {0}", msg.ToString());
                 throw;
             }
             catch (Exception er)
             {
                 StringBuilder msg = new StringBuilder();
                 //msg.AppendFormat(Utilitarios.CreateGenericErrorExceptionDetail(er));
                 _MyLogControlEventos.ErrorFormat("Error {0}", msg.ToString());
                 throw;
             }
         }
GetLogins()
IEnumerable<string> UTN.Winform.AppAirBnB.Layers.DAL.DALSeguridad.GetLogins ()
Implements UTN.Winform.AppAirBnB.Layers.Interface.IDALSeguridad.
Definition at line 175 of file DALSeguridad.cs.
References UTN.Winform.AppAirBnB.Layers.Persistencia.FactoryConexion.CreateConnection(), UTN.Winform.AppAirBnB.Layers.Persistencia.FactoryDataBase.CreateDataBase(), UTN.Winform.AppAirBnB.Layers.Persistencia.IDataBase.ExecuteReader(), UTN.Winform.AppAirBnB.Layers.Entities.Usuario.Login, and UTN.Winform.AppAirBnB.Layers.Entities.Usuario.Password.
         {
             SqlCommand command = new SqlCommand();
             DataSet ds = null;
             string sql = @"   select name from sys.syslogins  ";
             List<string> lista = new List<string>();
             try
             {
                 command.CommandText = sql;
                 command.CommandType = CommandType.Text;
                 using (IDataBase db = FactoryDataBase.CreateDataBase(FactoryConexion.CreateConnection(_Usuario.Login, _Usuario.Password)))
                 {
                     ds = db.ExecuteReader(command, "query");
                 }
                 foreach (DataRow row in ds.Tables[0].Rows)
                 {
                     lista.Add(row[0].ToString());
                 }
                 return lista;
             }
             catch (SqlException sqlError)
             {
                 StringBuilder msg = new StringBuilder();
                 //msg.AppendFormat(Utilitarios.CreateSQLExceptionsErrorDetails(sqlError));
                 msg.AppendFormat("SQL             {0}\n", command.CommandText);
                 _MyLogControlEventos.ErrorFormat("Error {0}", msg.ToString());
                 throw;
             }
             catch (Exception er)
             {
                 StringBuilder msg = new StringBuilder();
                 //msg.AppendFormat(Utilitarios.CreateGenericErrorExceptionDetail(er));
                 _MyLogControlEventos.ErrorFormat("Error {0}", msg.ToString());
                 throw;
             }
         }
GetLoginsXDataBase()
IEnumerable<string> UTN.Winform.AppAirBnB.Layers.DAL.DALSeguridad.GetLoginsXDataBase (string pBaseDatos)
Extraer los usuarios por Base de Datos
Parameters
pBaseDatos
Returns
Implements UTN.Winform.AppAirBnB.Layers.Interface.IDALSeguridad.
Definition at line 130 of file DALSeguridad.cs.
References UTN.Winform.AppAirBnB.Layers.Persistencia.FactoryConexion.CreateConnection(), UTN.Winform.AppAirBnB.Layers.Persistencia.FactoryDataBase.CreateDataBase(), UTN.Winform.AppAirBnB.Layers.Persistencia.IDataBase.ExecuteReader(), UTN.Winform.AppAirBnB.Layers.Entities.Usuario.Login, and UTN.Winform.AppAirBnB.Layers.Entities.Usuario.Password.
         {
             SqlCommand command = new SqlCommand();
             DataSet ds = null;
             string sql = @"   select name from sys.syslogins where dbname =  @basedatos  ";
             List<string> lista = new List<string>();
             try
             {
                 command.Parameters.AddWithValue("@basedatos", pBaseDatos);
                 command.CommandText = sql;
                 command.CommandType = CommandType.Text;
                 using (IDataBase db = FactoryDataBase.CreateDataBase(FactoryConexion.CreateConnection(_Usuario.Login, _Usuario.Password)))
                 {
                     ds = db.ExecuteReader(command, "query");
                 }
                 foreach (DataRow row in ds.Tables[0].Rows)
                 {
                     lista.Add(row[0].ToString());
                 }
                 return lista;
             }
             catch (SqlException sqlError)
             {
                 StringBuilder msg = new StringBuilder();
                // msg.AppendFormat(Utilitarios.CreateSQLExceptionsErrorDetails(sqlError));
                 msg.AppendFormat("SQL             {0}\n", command.CommandText);
                 _MyLogControlEventos.ErrorFormat("Error {0}", msg.ToString());
                 throw;
             }
             catch (Exception er)
             {
                 StringBuilder msg = new StringBuilder();
                 //msg.AppendFormat(Utilitarios.CreateGenericErrorExceptionDetail(er));
                 _MyLogControlEventos.ErrorFormat("Error {0}", msg.ToString());
                 throw;
             }
         }
Member Data Documentation
_MyLogControlEventos
readonly ILog UTN.Winform.AppAirBnB.Layers.DAL.DALSeguridad._MyLogControlEventos = LogManager.GetLogger("MyControlEventos") static private
Definition at line 19 of file DALSeguridad.cs.
_Usuario
Usuario UTN.Winform.AppAirBnB.Layers.DAL.DALSeguridad._Usuario = new Usuario() private
Definition at line 21 of file DALSeguridad.cs.
The documentation for this class was generated from the following file:
C:/Users/JorgeMario/Desktop/Proyecto Programado Cuatrimestre I 2018 v4/AppAirBnB/AppAirBnB/Layers/DAL/DALSeguridad.cs