AppAirBnB: UTN.Winform.AppAirBnB.Layers.DAL.DALHabitacion Class Reference
UTN.Winform.AppAirBnB.Layers.DAL.DALHabitacion Class Reference
Public Member Functions
DALHabitacion ()
bool DeleteHabitacion (double pId)
List< HabitacionDTO > GetAllHabitacion ()
Habitacion GetHabitacionById (double pId)
Habitacion SaveHabitacion (Habitacion pHabitacion)
Habitacion UpdateHabitacion (Habitacion pHabitacion)
Private Attributes
Usuario _Usuario = new Usuario()
Detailed Description
Definition at line 17 of file DALHabitacion.cs.
Constructor & Destructor Documentation
DALHabitacion()
UTN.Winform.AppAirBnB.Layers.DAL.DALHabitacion.DALHabitacion ()
Definition at line 22 of file DALHabitacion.cs.
References UTN.Winform.AppAirBnB.Properties.Settings.Default, UTN.Winform.AppAirBnB.Layers.Entities.Usuario.Login, UTN.Winform.AppAirBnB.Properties.Settings.Login, UTN.Winform.AppAirBnB.Layers.Entities.Usuario.Password, and UTN.Winform.AppAirBnB.Properties.Settings.Password.
         {
             _Usuario.Login = Settings.Default.Login;
             _Usuario.Password = Settings.Default.Password;
         }
Member Function Documentation
DeleteHabitacion()
bool UTN.Winform.AppAirBnB.Layers.DAL.DALHabitacion.DeleteHabitacion (double pId)
Implements UTN.Winform.AppAirBnB.Layers.Interface.IDALHabitacion.
Definition at line 28 of file DALHabitacion.cs.
References UTN.Winform.AppAirBnB.Layers.Persistencia.FactoryConexion.CreateConnection(), UTN.Winform.AppAirBnB.Layers.Persistencia.FactoryDataBase.CreateDataBase(), UTN.Winform.AppAirBnB.Util.Utilitarios.CreateGenericErrorExceptionDetail(), UTN.Winform.AppAirBnB.Util.Utilitarios.CreateSQLExceptionsErrorDetails(), UTN.Winform.AppAirBnB.Layers.Persistencia.IDataBase.ExecuteNonQuery(), UTN.Winform.AppAirBnB.Layers.Entities.Usuario.Login, and UTN.Winform.AppAirBnB.Layers.Entities.Usuario.Password.
         {
             double rows = 0;
             // Crear el SQL
             string sql = @"usp_DELETE_Habitacion_ByID";
             SqlCommand command = new SqlCommand();
             try
             {
                 // Pasar parámetros
                 command.Parameters.AddWithValue("@NUM", pId);
                 command.CommandText = sql;
                 command.CommandType = CommandType.StoredProcedure;
                 // Ejecutar
                 using (IDataBase db = FactoryDataBase.CreateDataBase(FactoryConexion.CreateConnection(_Usuario.Login, _Usuario.Password)))
                 {
                     rows = db.ExecuteNonQuery(command, IsolationLevel.ReadCommitted);
                 }
                 return rows > 0;
             }
             catch (SqlException sqlError)
             {
                 StringBuilder msg = new StringBuilder();
                 msg.AppendFormat(Utilitarios.CreateSQLExceptionsErrorDetails(sqlError));
                 msg.AppendFormat("SQL             {0}\n", command.CommandText);
                 //_MyLogControlEventos.ErrorFormat("Error {0}", msg.ToString());
                 throw;
             }
             catch (Exception er)
             {
                 StringBuilder msg = new StringBuilder();
                 msg.AppendFormat(Utilitarios.CreateGenericErrorExceptionDetail(er));
                 //_MyLogControlEventos.ErrorFormat("Error {0}", msg.ToString());
                 throw;
             }
         }
GetAllHabitacion()
List<HabitacionDTO> UTN.Winform.AppAirBnB.Layers.DAL.DALHabitacion.GetAllHabitacion ()
Implements UTN.Winform.AppAirBnB.Layers.Interface.IDALHabitacion.
Definition at line 69 of file DALHabitacion.cs.
References UTN.Winform.AppAirBnB.Layers.Persistencia.FactoryConexion.CreateConnection(), UTN.Winform.AppAirBnB.Layers.Persistencia.FactoryDataBase.CreateDataBase(), UTN.Winform.AppAirBnB.Util.Utilitarios.CreateGenericErrorExceptionDetail(), UTN.Winform.AppAirBnB.Util.Utilitarios.CreateSQLExceptionsErrorDetails(), UTN.Winform.AppAirBnB.Layers.Persistencia.IDataBase.ExecuteReader(), UTN.Winform.AppAirBnB.Layers.Entities.Usuario.Login, and UTN.Winform.AppAirBnB.Layers.Entities.Usuario.Password.
         {
             DataSet ds = null;
             List<HabitacionDTO> lista = new List<HabitacionDTO>();
             SqlCommand command = new SqlCommand();
             string sql = @"usp_SELECT_Habitacion_All";
             try
             {
                 command.CommandText = sql;
                 command.CommandType = CommandType.StoredProcedure;
                 using (IDataBase db = FactoryDataBase.CreateDataBase(FactoryConexion.CreateConnection(_Usuario.Login, _Usuario.Password)))
                 {
                     ds = db.ExecuteReader(command, "query");
                 }
                 // Si devolvió filas
                 if (ds.Tables[0].Rows.Count > 0)
                 {
                     // Iterar en todas las filas y Mapearlas
                     foreach (DataRow dr in ds.Tables[0].Rows)
                     {
                         HabitacionDTO oHabitacionDTO = new HabitacionDTO()
{
                             NUM = double.Parse(dr["NUM"].ToString()),
                             Descripcion = dr["Descripcion"].ToString(),
                             Foto = (byte[])dr["Foto"],
                             Estado = (int)dr["Estado"],
                             Precio = double.Parse(dr["Precio"].ToString())
                         };
                         lista.Add(oHabitacionDTO);
                     }
                 }
                 return lista;
             }
             catch (SqlException sqlError)
             {
                 StringBuilder msg = new StringBuilder();
                 msg.AppendFormat(Utilitarios.CreateSQLExceptionsErrorDetails(sqlError));
                 msg.AppendFormat("SQL             {0}\n", command.CommandText);
                 //_MyLogControlEventos.ErrorFormat("Error {0}", msg.ToString());
                 throw;
             }
             catch (Exception er)
             {
                 StringBuilder msg = new StringBuilder();
                 msg.AppendFormat(Utilitarios.CreateGenericErrorExceptionDetail(er));
                 //_MyLogControlEventos.ErrorFormat("Error {0}", msg.ToString());
                 throw;
             }
         }
GetHabitacionById()
Habitacion UTN.Winform.AppAirBnB.Layers.DAL.DALHabitacion.GetHabitacionById (double pId)
Implements UTN.Winform.AppAirBnB.Layers.Interface.IDALHabitacion.
Definition at line 126 of file DALHabitacion.cs.
References UTN.Winform.AppAirBnB.Layers.Persistencia.FactoryConexion.CreateConnection(), UTN.Winform.AppAirBnB.Layers.Persistencia.FactoryDataBase.CreateDataBase(), UTN.Winform.AppAirBnB.Util.Utilitarios.CreateGenericErrorExceptionDetail(), UTN.Winform.AppAirBnB.Util.Utilitarios.CreateSQLExceptionsErrorDetails(), UTN.Winform.AppAirBnB.Layers.Persistencia.IDataBase.ExecuteReader(), UTN.Winform.AppAirBnB.Layers.Entities.Usuario.Login, UTN.Winform.AppAirBnB.Layers.Entities.Usuario.Password, and UTN.Winform.AppAirBnB.Layers.Entities.Habitacion.ToString().
         {
             DataSet ds = null;
             Habitacion oHabitacion = null;
             string sql = @"Select * from [Habitacion] where NUM = @NUM";
             SqlCommand command = new SqlCommand();
             try
             {
                 command.Parameters.AddWithValue("@NUM", pId);
                 command.CommandText = sql;
                 command.CommandType = CommandType.Text;
                 using (IDataBase db = FactoryDataBase.CreateDataBase(FactoryConexion.CreateConnection(_Usuario.Login, _Usuario.Password)))
                 {
                     ds = db.ExecuteReader(command, "query");
                 }
                 // Si retornó valores
                 if (ds.Tables[0].Rows.Count > 0)
                 {
                     //Extraer la primera fila, como se buscó por Id entonces solo una debe devolver
                     DataRow dr = ds.Tables[0].Rows[0];
                     oHabitacion = new Habitacion()
                     {
                         NUM = double.Parse(dr["NUM"].ToString()),
                         Descripcion = dr["Descripcion"].ToString(),
                         Foto = (byte[])dr["Foto"],
                         Estado = (int)dr["Estado"],
                         Precio = double.Parse(dr["Precio"].ToString())
                     };
                 }
                 return oHabitacion;
             }
             catch (SqlException sqlError)
             {
                 StringBuilder msg = new StringBuilder();
                 msg.AppendFormat(Utilitarios.CreateSQLExceptionsErrorDetails(sqlError));
                 msg.AppendFormat("SQL             {0}\n", command.CommandText);
                 //_MyLogControlEventos.ErrorFormat("Error {0}", msg.ToString());
                 throw;
             }
             catch (Exception er)
             {
                 StringBuilder msg = new StringBuilder();
                 msg.AppendFormat(Utilitarios.CreateGenericErrorExceptionDetail(er));
                 //_MyLogControlEventos.ErrorFormat("Error {0}", msg.ToString());
                 throw;
             }
         }
SaveHabitacion()
Habitacion UTN.Winform.AppAirBnB.Layers.DAL.DALHabitacion.SaveHabitacion (Habitacion pHabitacion)
Implements UTN.Winform.AppAirBnB.Layers.Interface.IDALHabitacion.
Definition at line 183 of file DALHabitacion.cs.
References UTN.Winform.AppAirBnB.Layers.Persistencia.FactoryConexion.CreateConnection(), UTN.Winform.AppAirBnB.Layers.Persistencia.FactoryDataBase.CreateDataBase(), UTN.Winform.AppAirBnB.Util.Utilitarios.CreateGenericErrorExceptionDetail(), UTN.Winform.AppAirBnB.Util.Utilitarios.CreateSQLExceptionsErrorDetails(), UTN.Winform.AppAirBnB.Layers.Entities.Habitacion.Descripcion, UTN.Winform.AppAirBnB.Layers.Entities.Habitacion.Estado, UTN.Winform.AppAirBnB.Layers.Persistencia.IDataBase.ExecuteNonQuery(), UTN.Winform.AppAirBnB.Layers.Entities.Habitacion.Foto, UTN.Winform.AppAirBnB.Layers.Entities.Usuario.Login, UTN.Winform.AppAirBnB.Layers.Entities.Habitacion.NUM, UTN.Winform.AppAirBnB.Layers.Entities.Usuario.Password, and UTN.Winform.AppAirBnB.Layers.Entities.Habitacion.Precio.
         {
             Habitacion oHabitacion = null;
             string sql = @"usp_INSERT_Habitacion";
             SqlCommand command = new SqlCommand();
             double rows = 0;
             try
             {
                 // Pasar parámetros
                 command.Parameters.AddWithValue("@NUM", pHabitacion.NUM);
                 command.Parameters.AddWithValue("@Descripcion", pHabitacion.Descripcion);
                 command.Parameters.AddWithValue("@Foto", pHabitacion.Foto.ToArray());
                 command.Parameters.AddWithValue("Estado", pHabitacion.Estado);
                 command.Parameters.AddWithValue("Precio", pHabitacion.Precio);
                 command.CommandText = sql;
                 command.CommandType = CommandType.StoredProcedure;
                 using (IDataBase db = FactoryDataBase.CreateDataBase(FactoryConexion.CreateConnection(_Usuario.Login, _Usuario.Password)))
                 {
                     rows = db.ExecuteNonQuery(command, IsolationLevel.ReadCommitted);
                 }
                 // Si devuelve filas quiere decir que se salvo entonces extraerlo
                 if (rows > 0)
                     oHabitacion = GetHabitacionById(pHabitacion.NUM);
                 return oHabitacion;
             }
             catch (SqlException sqlError)
             {
                 StringBuilder msg = new StringBuilder();
                 msg.AppendFormat(Utilitarios.CreateSQLExceptionsErrorDetails(sqlError));
                 msg.AppendFormat("SQL             {0}\n", command.CommandText);
                 //_MyLogControlEventos.ErrorFormat("Error {0}", msg.ToString());
                 throw;
             }
             catch (Exception er)
             {
                 StringBuilder msg = new StringBuilder();
                 msg.AppendFormat(Utilitarios.CreateGenericErrorExceptionDetail(er));
                 //_MyLogControlEventos.ErrorFormat("Error {0}", msg.ToString());
                 throw;
             }
         }
UpdateHabitacion()
Habitacion UTN.Winform.AppAirBnB.Layers.DAL.DALHabitacion.UpdateHabitacion (Habitacion pHabitacion)
Implements UTN.Winform.AppAirBnB.Layers.Interface.IDALHabitacion.
Definition at line 235 of file DALHabitacion.cs.
References UTN.Winform.AppAirBnB.Layers.Persistencia.FactoryConexion.CreateConnection(), UTN.Winform.AppAirBnB.Layers.Persistencia.FactoryDataBase.CreateDataBase(), UTN.Winform.AppAirBnB.Util.Utilitarios.CreateGenericErrorExceptionDetail(), UTN.Winform.AppAirBnB.Util.Utilitarios.CreateSQLExceptionsErrorDetails(), UTN.Winform.AppAirBnB.Layers.Entities.Habitacion.Descripcion, UTN.Winform.AppAirBnB.Layers.Entities.Habitacion.Estado, UTN.Winform.AppAirBnB.Layers.Persistencia.IDataBase.ExecuteNonQuery(), UTN.Winform.AppAirBnB.Layers.Entities.Habitacion.Foto, UTN.Winform.AppAirBnB.Layers.Entities.Usuario.Login, UTN.Winform.AppAirBnB.Layers.Entities.Habitacion.NUM, UTN.Winform.AppAirBnB.Layers.Entities.Usuario.Password, and UTN.Winform.AppAirBnB.Layers.Entities.Habitacion.Precio.
         {
             Habitacion oHabitacion = null;
             string sql = @"usp_UPDATE_Habitacion";
             SqlCommand command = new SqlCommand();
             double rows = 0;
             try
             {
                 // Pasar parámetros
                 command.Parameters.AddWithValue("@NUM", pHabitacion.NUM);
                 command.Parameters.AddWithValue("@Descripcion", pHabitacion.Descripcion);
                 command.Parameters.AddWithValue("@Foto", pHabitacion.Foto.ToArray());
                 command.Parameters.AddWithValue("Estado", pHabitacion.Estado);
                 command.Parameters.AddWithValue("Precio", pHabitacion.Precio);
                 command.CommandText = sql;
                 command.CommandType = CommandType.StoredProcedure;
                 using (IDataBase db = FactoryDataBase.CreateDataBase(FactoryConexion.CreateConnection(_Usuario.Login, _Usuario.Password)))
                 {
                     rows = db.ExecuteNonQuery(command, IsolationLevel.ReadCommitted);
                 }
                 // Si devuelve filas quiere decir que se salvo entonces extraerlo
                 if (rows > 0)
                     oHabitacion = GetHabitacionById(pHabitacion.NUM);
                 return oHabitacion;
             }
             catch (SqlException sqlError)
             {
                 StringBuilder msg = new StringBuilder();
                 msg.AppendFormat(Utilitarios.CreateSQLExceptionsErrorDetails(sqlError));
                 msg.AppendFormat("SQL             {0}\n", command.CommandText);
                 //_MyLogControlEventos.ErrorFormat("Error {0}", msg.ToString());
                 throw;
             }
             catch (Exception er)
             {
                 StringBuilder msg = new StringBuilder();
                 msg.AppendFormat(Utilitarios.CreateGenericErrorExceptionDetail(er));
                 //_MyLogControlEventos.ErrorFormat("Error {0}", msg.ToString());
                 throw;
             }
         }
Member Data Documentation
_Usuario
Usuario UTN.Winform.AppAirBnB.Layers.DAL.DALHabitacion._Usuario = new Usuario() private
Definition at line 21 of file DALHabitacion.cs.
The documentation for this class was generated from the following file:
C:/Users/JorgeMario/Desktop/Proyecto Programado Cuatrimestre I 2018 v4/AppAirBnB/AppAirBnB/Layers/DAL/DALHabitacion.cs