AppAirBnB: UTN.Winform.AppAirBnB.Layers.Persistencia.FactoryDataBase Class Reference
UTN.Winform.AppAirBnB.Layers.Persistencia.FactoryDataBase Class Reference
Static Public Member Functions
static IDataBase CreateDataBase (string pStringConnection)
Detailed Description
Definition at line 11 of file FactoryDataBase.cs.
Member Function Documentation
CreateDataBase()
static IDataBase UTN.Winform.AppAirBnB.Layers.Persistencia.FactoryDataBase.CreateDataBase (string pStringConnection) static
Definition at line 13 of file FactoryDataBase.cs.
References UTN.Winform.AppAirBnB.Layers.Persistencia.IDataBase._Conexion.
Referenced by UTN.Winform.AppAirBnB.Layers.DAL.DALSeguridad.CreateUser(), UTN.Winform.AppAirBnB.Layers.DAL.DALHabitacion.DeleteHabitacion(), UTN.Winform.AppAirBnB.Layers.DAL.DALHuesped.DeleteHuesped(), UTN.Winform.AppAirBnB.Layers.DAL.DALReservacion.DeleteReserva(), UTN.Winform.AppAirBnB.Layers.DAL.DALSysUserRolDTO.DeleteSysUser(), UTN.Winform.AppAirBnB.Layers.DAL.DALHabitacion.GetAllHabitacion(), UTN.Winform.AppAirBnB.Layers.DAL.DALHuesped.GetAllHuesped(), UTN.Winform.AppAirBnB.Layers.DAL.DALPais.GetAllPais(), UTN.Winform.AppAirBnB.Layers.DAL.DALReservacion.GetAllReservacion(), UTN.Winform.AppAirBnB.Layers.DAL.DALSysUserRolDTO.GetAllSysUser(), UTN.Winform.AppAirBnB.Layers.DAL.DALTarjeta.GetAllTarjeta(), UTN.Winform.AppAirBnB.Layers.DAL.DALEncFactura.GetCurrentNumeroFactura(), UTN.Winform.AppAirBnB.Layers.DAL.DALReservacion.GetCurrentNumeroReserva(), UTN.Winform.AppAirBnB.Layers.DAL.DALSeguridad.GetDataBases(), UTN.Winform.AppAirBnB.Layers.DAL.DALEncFactura.GetFactura(), UTN.Winform.AppAirBnB.Layers.DAL.DALHabitacion.GetHabitacionById(), UTN.Winform.AppAirBnB.Layers.DAL.DALHuesped.GetHuespedByFilter(), UTN.Winform.AppAirBnB.Layers.DAL.DALHuesped.GetHuespedById(), UTN.Winform.AppAirBnB.Layers.DAL.DALImpuesto.GetImpuesto(), UTN.Winform.AppAirBnB.Layers.DAL.DALSeguridad.GetLogins(), UTN.Winform.AppAirBnB.Layers.DAL.DALSeguridad.GetLoginsXDataBase(), UTN.Winform.AppAirBnB.Layers.DAL.DALEncFactura.GetNextNumeroFactura(), UTN.Winform.AppAirBnB.Layers.DAL.DALReservacion.GetNextNumeroReserva(), UTN.Winform.AppAirBnB.Layers.DAL.DALReservacion.GetReserva(), UTN.Winform.AppAirBnB.Layers.DAL.DALSysUserRolDTO.GetSysUserByFilter(), UTN.Winform.AppAirBnB.Layers.DAL.DALSysUserRolDTO.GetSysUserById(), UTN.Winform.AppAirBnB.Layers.DAL.DALTarjeta.GetTarjetaById(), UTN.Winform.AppAirBnB.Layers.DAL.DALLogin.Login(), UTN.Winform.AppAirBnB.Layers.DAL.DALEncFactura.SaveFactura(), UTN.Winform.AppAirBnB.Layers.DAL.DALHabitacion.SaveHabitacion(), UTN.Winform.AppAirBnB.Layers.DAL.DALHuesped.SaveHuesped(), UTN.Winform.AppAirBnB.Layers.DAL.DALReservacion.SaveReserva(), UTN.Winform.AppAirBnB.Layers.DAL.DALSysUserRolDTO.SaveSysUser(), UTN.Winform.AppAirBnB.Layers.DAL.DALHabitacion.UpdateHabitacion(), UTN.Winform.AppAirBnB.Layers.DAL.DALHuesped.UpdateHuesped(), and UTN.Winform.AppAirBnB.Layers.DAL.DALSysUserRolDTO.UpdateSysUser().
         {
             IDbConnection conexion = null;
             try
             {
                 IDataBase db = new DataBase();
                 conexion = new SqlConnection(pStringConnection);
                 conexion.Open();
                 db._Conexion = conexion;
                 if (conexion.State != ConnectionState.Open)
                 {
                     throw new Exception("No se pudo abrir la Base de Datos, revise los parámetros de conexión! ");
                 }
                 return db;
             }
             catch (Exception)
             {
                 throw;
             }
         }
The documentation for this class was generated from the following file:
C:/Users/JorgeMario/Desktop/Proyecto Programado Cuatrimestre I 2018 v4/AppAirBnB/AppAirBnB/Layers/Persistencia/FactoryDataBase.cs