AppAirBnB: UTN.Winform.AppAirBnB.Layers.UI.Procesos.frmFacturacion Class Reference
UTN.Winform.AppAirBnB.Layers.UI.Procesos.frmFacturacion Class Reference
Public Member Functions
frmFacturacion ()
Protected Member Functions
override void Dispose (bool disposing)
Clean up any resources being used.
Private Member Functions
void txtClienteId_MouseClick (object sender, MouseEventArgs e)
void CargarDatos ()
void frmFacturacion_Load (object sender, EventArgs e)
void toolStripBtnNuevo_Click (object sender, EventArgs e)
void toolStripBtnFacturar_Click (object sender, EventArgs e)
void EstadoHabitaciones ()
void toolStripBtnSalir_Click (object sender, EventArgs e)
void CargarTarjeta ()
void btnAgregar_Click (object sender, EventArgs e)
void txtIdHuesped_TextChanged (object sender, EventArgs e)
void btnBuscarReserva_Click (object sender, EventArgs e)
void InitializeComponent ()
Required method for Designer support - do not modify the contents of this method with the code editor.
Private Attributes
Reservacion _Reservacion = null
EncFactura _FacturaEncabezado = null
double cont = 0
System.ComponentModel.IContainer components = null
Required designer variable.
System.Windows.Forms.ToolStrip tspBarraSuperior
System.Windows.Forms.ToolStripButton toolStripBtnNuevo
System.Windows.Forms.ToolStripButton toolStripBtnSalir
System.Windows.Forms.StatusStrip sttBarraInferior
System.Windows.Forms.SplitContainer splitContainer1
System.Windows.Forms.GroupBox groupBox1
System.Windows.Forms.TableLayoutPanel tlpAgrupamiento
System.Windows.Forms.Label label3
System.Windows.Forms.Label label2
System.Windows.Forms.Label label4
System.Windows.Forms.TextBox txtNumeroTarjeta
System.Windows.Forms.ComboBox cmbTarjeta
System.Windows.Forms.Label label1
System.Windows.Forms.Label label11
System.Windows.Forms.TextBox txtNumeroFactura
System.Windows.Forms.RadioButton rdbCredito
System.Windows.Forms.TableLayoutPanel tableLayoutPanel2
System.Windows.Forms.Label label8
System.Windows.Forms.Label label9
System.Windows.Forms.Label label10
System.Windows.Forms.TextBox txtSubtotal
System.Windows.Forms.TextBox txtImpuesto
System.Windows.Forms.TextBox txtTotal
System.Windows.Forms.GroupBox groupBox2
System.Windows.Forms.DataGridView dgvDetalleFactura
System.Windows.Forms.RadioButton rdbContado
System.Windows.Forms.TableLayoutPanel tableLayoutPanel3
System.Windows.Forms.Label label7
System.Windows.Forms.TextBox txtPrecio
System.Windows.Forms.Button btnBuscarReserva
System.Windows.Forms.MaskedTextBox mskIDReserva
System.Windows.Forms.Button btnAgregar
System.Windows.Forms.Label label5
System.Windows.Forms.ComboBox cmbEstado
System.Windows.Forms.ErrorProvider erpError
System.Windows.Forms.Label label13
System.Windows.Forms.TextBox txtNUMDetalle
System.Windows.Forms.DataGridViewTextBoxColumn NoFactura
System.Windows.Forms.DataGridViewTextBoxColumn Detalle
System.Windows.Forms.DataGridViewTextBoxColumn Precio
System.Windows.Forms.DataGridViewTextBoxColumn IDReservacion
System.Windows.Forms.DataGridViewTextBoxColumn NumTarjeta
System.Windows.Forms.DataGridViewTextBoxColumn Fecha
System.Windows.Forms.DataGridViewTextBoxColumn Estado
System.Windows.Forms.Label label6
System.Windows.Forms.TextBox txtIdHuesped
System.Windows.Forms.Label label12
System.Windows.Forms.TextBox txtNumHabitacion
System.Windows.Forms.Label label14
System.Windows.Forms.Label label15
System.Windows.Forms.DateTimePicker dtpIn
System.Windows.Forms.DateTimePicker dtpOut
System.Windows.Forms.Label label16
System.Windows.Forms.TextBox txtCantDias
System.Windows.Forms.TextBox Subtotal
System.Windows.Forms.Label label17
System.Windows.Forms.ToolStripButton toolStripBtnFacturar
Static Private Attributes
static readonly ILog _MyLogControlEventos = log4net.LogManager.GetLogger("MyControlEventos")
Detailed Description
Definition at line 22 of file frmFacturacion.cs.
Constructor & Destructor Documentation
frmFacturacion()
UTN.Winform.AppAirBnB.Layers.UI.Procesos.frmFacturacion.frmFacturacion ()
Definition at line 31 of file frmFacturacion.cs.
         {
             InitializeComponent();
         }
Member Function Documentation
btnAgregar_Click()
void UTN.Winform.AppAirBnB.Layers.UI.Procesos.frmFacturacion.btnAgregar_Click (object sender, EventArgs e) private
Definition at line 283 of file frmFacturacion.cs.
References UTN.Winform.AppAirBnB.Layers.Entities.DetFactura._EncFactura, UTN.Winform.AppAirBnB.Layers.Entities.DetFactura._Impuesto, UTN.Winform.AppAirBnB.Layers.Entities.EncFactura._ListaFacturaDetalle, UTN.Winform.AppAirBnB.Layers.Entities.DetFactura._Reservacion, UTN.Winform.AppAirBnB.Layers.Entities.EncFactura.AddDetalle(), UTN.Winform.AppAirBnB.Layers.Entities.Reservacion.CheckOUT, UTN.Winform.AppAirBnB.Layers.Interface.IBLLEncFactura.GetCurrentNumeroFactura(), UTN.Winform.AppAirBnB.Layers.Interface.IBLLEncFactura.GetFactura(), UTN.Winform.AppAirBnB.Layers.Interface.IBLLImpuesto.GetImpuesto(), UTN.Winform.AppAirBnB.Layers.Interface.IBLLReservacion.GetReserva(), UTN.Winform.AppAirBnB.Layers.Interface.IBLLTarjeta.GetTarjetaById(), UTN.Winform.AppAirBnB.Layers.Entities.Reservacion.ID, UTN.Winform.AppAirBnB.Layers.Entities.DetFactura.Numero, UTN.Winform.AppAirBnB.Layers.Entities.DetFactura.Precio, and UTN.Winform.AppAirBnB.Layers.Entities.Tarjeta.ToString().
         {
             //IBLLImpuesto _BLLImpuesto = new BLLImpuesto();
             DetFactura oFacturaDetalle = new DetFactura();
             IBLLEncFactura _BLLFactura = new BLLEncFactura();
             IBLLReservacion _BLLReservacion = new BLLReservacion();
             IBLLTarjeta _BLLTarjeta = new BLLTarjeta();
             _FacturaEncabezado = new EncFactura();
             try
             {
                 erpError.Clear();
                 _FacturaEncabezado = new EncFactura()
                 {
                     IDFactura = _BLLFactura.GetCurrentNumeroFactura(),
                     _Tarjeta = _BLLTarjeta.GetTarjetaById(Double.Parse(this.txtNumeroTarjeta.Text)),
                     Fecha = DateTime.Now,
                     EstadoFact = this.cmbEstado.SelectedIndex.ToString()
                 };
                 if (_FacturaEncabezado == null)
                 {
                     MessageBox.Show("Debe agregar los datos del encabezado de la factura para continuar", "Error", MessageBoxButtons.OK, MessageBoxIcon.Error);
                     return;
                 }
                 // Validar que el Producto ya no se haya agregado
                 if (_FacturaEncabezado._ListaFacturaDetalle.Count > 0)
                 {
                     // Si ya se agrego no permitir agregarlo nuevamente
                     if (_FacturaEncabezado._ListaFacturaDetalle.FindAll(p => p._Reservacion.ID == double.Parse(this.mskIDReserva.Text)).Count > 0)
                     {
                         MessageBox.Show("La Reservacion ya fue agregado previamente.", "Error", MessageBoxButtons.OK, MessageBoxIcon.Error);
                         return;
                     }
                 }
                 oFacturaDetalle._EncFactura = _BLLFactura.GetFactura(Double.Parse(this.txtNumeroFactura.Text));
                 oFacturaDetalle._Reservacion = _BLLReservacion.GetReserva(Double.Parse(this.mskIDReserva.Text.ToString()));
                 oFacturaDetalle.Precio = Double.Parse(this.txtPrecio.Text.ToString());
                 // Calcular el Impuesto
                 IBLLImpuesto _BLLImpuestotest = new BLLImpuesto();
                 oFacturaDetalle._Impuesto = _BLLImpuestotest.GetImpuesto();//((double)_BLLImpuesto.GetImpuesto().Porcentaje / 100D) * oFacturaDetalle.Precio * 1;
                 // Enumerar la secuencia
                 oFacturaDetalle.Numero = _FacturaEncabezado._ListaFacturaDetalle.Count == 0 ?
                                                  1 : _FacturaEncabezado._ListaFacturaDetalle.Max(p => p.Numero) +1;
                 // Agregar
                 _FacturaEncabezado.AddDetalle(oFacturaDetalle);
                 if (oFacturaDetalle._Reservacion.CheckOUT.Day < this.dtpOut.Value.Day)
                 {
                     MessageBox.Show(
                         "  Ha sobrepasado la fecha para realizar su Check Out , por lo que se realizara un cobro equivalente a $50 adicional. Disculpe. "
                         , "Error", MessageBoxButtons.OK, MessageBoxIcon.Error);
                 }
                 this.txtNUMDetalle.Text = (cont++ +1) .ToString();
                 string[] lineaFactura = { _BLLFactura.GetCurrentNumeroFactura().ToString(),
                                         (cont).ToString(),
                                          oFacturaDetalle.Precio.ToString(),
                                          oFacturaDetalle._Reservacion.ID.ToString(),
                                          this.txtNumeroTarjeta.Text,
                                          DateTime.Now.ToString(),
                                          this.cmbEstado.SelectedItem.ToString()
                                          };
                 this.dgvDetalleFactura.Rows.Add(lineaFactura);
             }
             catch (Exception er)
             {
                 StringBuilder msg = new StringBuilder();
                 msg.AppendFormat("Message        {0}\n", er.Message);
                 msg.AppendFormat("Source         {0}\n", er.Source);
                 msg.AppendFormat("InnerException {0}\n", er.InnerException);
                 msg.AppendFormat("StackTrace     {0}\n", er.StackTrace);
                 msg.AppendFormat("TargetSite     {0}\n", er.TargetSite);
                 // Log error
                 _MyLogControlEventos.ErrorFormat("Error {0}", msg.ToString());
                 // Mensaje de Error
                 MessageBox.Show("Se ha producido el siguiente error " + er.Message, "Error", MessageBoxButtons.OK, MessageBoxIcon.Error);
             }
         }
btnBuscarReserva_Click()
void UTN.Winform.AppAirBnB.Layers.UI.Procesos.frmFacturacion.btnBuscarReserva_Click (object sender, EventArgs e) private
Definition at line 397 of file frmFacturacion.cs.
References UTN.Winform.AppAirBnB.Layers.Entities.Reservacion._Habitacion, UTN.Winform.AppAirBnB.Layers.Entities.Reservacion._Huesped, UTN.Winform.AppAirBnB.Layers.UI.Filtros.frmFiltroReserva._Reservacion, UTN.Winform.AppAirBnB.Layers.Entities.Reservacion.CantDias, UTN.Winform.AppAirBnB.Layers.Entities.Reservacion.CheckIN, UTN.Winform.AppAirBnB.Layers.Entities.Reservacion.CheckOUT, UTN.Winform.AppAirBnB.Layers.Entities.Huesped.ID, UTN.Winform.AppAirBnB.Layers.Entities.Reservacion.ID, UTN.Winform.AppAirBnB.Layers.Entities.Habitacion.NUM, UTN.Winform.AppAirBnB.Layers.Entities.Habitacion.Precio, and UTN.Winform.AppAirBnB.Layers.Entities.Reservacion.Subtotal.
         {
             frmFiltroReserva ofrmFiltroReserva = new frmFiltroReserva();
             Reservacion oReserva = null;
             try
             {
                 ofrmFiltroReserva.ShowDialog();
                 if (ofrmFiltroReserva.DialogResult == DialogResult.OK)
                 {
                     oReserva = ofrmFiltroReserva._Reservacion ;
                     mskIDReserva.Text = oReserva.ID.ToString();
                     this.txtIdHuesped.Text = oReserva._Huesped.ID.ToString();
                     this.txtNumHabitacion.Text = oReserva._Habitacion.NUM.ToString();
                     this.txtPrecio.Text = oReserva._Habitacion.Precio.ToString();
                     this.dtpIn.Value = oReserva.CheckIN;
                     this.dtpOut.Value = oReserva.CheckOUT;
                     this.txtCantDias.Text = oReserva.CantDias.ToString();
                     this.Subtotal.Text = oReserva.Subtotal.ToString();
                 }
             }
             catch (Exception er)
             {
                 StringBuilder msg = new StringBuilder();
                 msg.AppendFormat("Message        {0}\n", er.Message);
                 msg.AppendFormat("Source         {0}\n", er.Source);
                 msg.AppendFormat("InnerException {0}\n", er.InnerException);
                 msg.AppendFormat("StackTrace     {0}\n", er.StackTrace);
                 msg.AppendFormat("TargetSite     {0}\n", er.TargetSite);
                 // Log error
                 _MyLogControlEventos.ErrorFormat("Error {0}", msg.ToString());
                 // Mensaje de Error
                 MessageBox.Show("Se ha producido el siguiente error " + er.Message, "Error", MessageBoxButtons.OK, MessageBoxIcon.Error);
             }
         }
CargarDatos()
void UTN.Winform.AppAirBnB.Layers.UI.Procesos.frmFacturacion.CargarDatos () private
Definition at line 41 of file frmFacturacion.cs.
References UTN.Winform.AppAirBnB.Layers.Interface.IBLLEncFactura.GetCurrentNumeroFactura().
         {
             IBLLEncFactura _BLLFactura = new BLLEncFactura();
             // Configuracion del DataGridView para que se vea bien la imagen.
             dgvDetalleFactura.AutoGenerateColumns = false;
             this.txtNumeroFactura.Text = _BLLFactura.GetCurrentNumeroFactura().ToString();
             this.cmbEstado.SelectedIndex = 0;
         }
CargarTarjeta()
void UTN.Winform.AppAirBnB.Layers.UI.Procesos.frmFacturacion.CargarTarjeta () private
Definition at line 266 of file frmFacturacion.cs.
         {
             IBLLTarjeta _BLLTarjeta = new BLLTarjeta();
             foreach (var oTarjeta in _BLLTarjeta.GetAllTarjeta())
             {
                 this.cmbTarjeta.Items.Add(oTarjeta);
             }
             cmbTarjeta.SelectedIndex = 0;
             IBLLEncFactura _BLLFactura = new BLLEncFactura();
             //cmbEstado.SelectedIndex = 0;
             this.cmbEstado.Items.Add("Pendiente");
             this.cmbEstado.Items.Add("Cancelado");
         }
Dispose()
override void UTN.Winform.AppAirBnB.Layers.UI.Procesos.frmFacturacion.Dispose (bool disposing) protected
Clean up any resources being used.
Parameters
disposing true if managed resources should be disposed; otherwise, false.
Definition at line 14 of file frmFacturacion.Designer.cs.
         {
             if (disposing && (components != null))
             {
                 components.Dispose();
             }
             base.Dispose(disposing);
         }
EstadoHabitaciones()
void UTN.Winform.AppAirBnB.Layers.UI.Procesos.frmFacturacion.EstadoHabitaciones () private
Definition at line 225 of file frmFacturacion.cs.
References UTN.Winform.AppAirBnB.Layers.Entities.Habitacion.Descripcion, UTN.Winform.AppAirBnB.Layers.Entities.Habitacion.Estado, UTN.Winform.AppAirBnB.Layers.Entities.Habitacion.Foto, UTN.Winform.AppAirBnB.Layers.Interface.IBLLHabitacion.GetHabitacionById(), UTN.Winform.AppAirBnB.Layers.Entities.Habitacion.NUM, UTN.Winform.AppAirBnB.Layers.Entities.Habitacion.Precio, and UTN.Winform.AppAirBnB.Layers.Interface.IBLLHabitacion.SaveHabitacion().
         {
             IBLLHabitacion _BLLHabitacion = new BLLHabitacion();
             Habitacion oHabitacion = null;
             oHabitacion = new Habitacion();
             oHabitacion.NUM = double.Parse(this.txtNumHabitacion.Text);
             oHabitacion.Descripcion = _BLLHabitacion.GetHabitacionById(double.Parse(this.txtNumHabitacion.Text)).Descripcion;
             oHabitacion.Foto = _BLLHabitacion.GetHabitacionById(double.Parse(this.txtNumHabitacion.Text)).Foto;
             oHabitacion.Precio = _BLLHabitacion.GetHabitacionById(double.Parse(this.txtNumHabitacion.Text)).Precio;
             if (_BLLHabitacion.GetHabitacionById(double.Parse(this.txtNumHabitacion.Text)).Estado == 2 )
             {
                 oHabitacion.Estado = 1;
             }
             oHabitacion = _BLLHabitacion.SaveHabitacion(oHabitacion);
             //_BLLHabitacion.SaveHabitacion(oHabitacion);
         }
frmFacturacion_Load()
void UTN.Winform.AppAirBnB.Layers.UI.Procesos.frmFacturacion.frmFacturacion_Load (object sender, EventArgs e) private
Definition at line 58 of file frmFacturacion.cs.
         {
             IBLLReservacion _BLLReservacion = new BLLReservacion();
             try
             {
                 // Mostar Numero de factura
                 CargarTarjeta();
                 CargarDatos();
             }
             catch (Exception er)
             {
                 StringBuilder msg = new StringBuilder();
                 msg.AppendFormat("Message        {0}\n", er.Message);
                 msg.AppendFormat("Source         {0}\n", er.Source);
                 msg.AppendFormat("InnerException {0}\n", er.InnerException);
                 msg.AppendFormat("StackTrace     {0}\n", er.StackTrace);
                 msg.AppendFormat("TargetSite     {0}\n", er.TargetSite);
                 // Log error
                 _MyLogControlEventos.ErrorFormat("Error {0}", msg.ToString());
                 // Mensaje de Error
                 MessageBox.Show("Se ha producido el siguiente error " + er.Message, "Error", MessageBoxButtons.OK, MessageBoxIcon.Error);
             }
         }
InitializeComponent()
void UTN.Winform.AppAirBnB.Layers.UI.Procesos.frmFacturacion.InitializeComponent () private
Required method for Designer support - do not modify the contents of this method with the code editor.
Definition at line 29 of file frmFacturacion.Designer.cs.
         {
             this.components = new System.ComponentModel.Container();
             this.tspBarraSuperior = new System.Windows.Forms.ToolStrip();
             this.toolStripBtnNuevo = new System.Windows.Forms.ToolStripButton();
             this.toolStripBtnFacturar = new System.Windows.Forms.ToolStripButton();
             this.toolStripBtnSalir = new System.Windows.Forms.ToolStripButton();
             this.sttBarraInferior = new System.Windows.Forms.StatusStrip();
             this.splitContainer1 = new System.Windows.Forms.SplitContainer();
             this.groupBox1 = new System.Windows.Forms.GroupBox();
             this.tableLayoutPanel3 = new System.Windows.Forms.TableLayoutPanel();
             this.btnBuscarReserva = new System.Windows.Forms.Button();
             this.btnAgregar = new System.Windows.Forms.Button();
             this.label5 = new System.Windows.Forms.Label();
             this.mskIDReserva = new System.Windows.Forms.MaskedTextBox();
             this.label13 = new System.Windows.Forms.Label();
             this.txtNUMDetalle = new System.Windows.Forms.TextBox();
             this.label7 = new System.Windows.Forms.Label();
             this.txtPrecio = new System.Windows.Forms.TextBox();
             this.label6 = new System.Windows.Forms.Label();
             this.txtIdHuesped = new System.Windows.Forms.TextBox();
             this.label12 = new System.Windows.Forms.Label();
             this.txtNumHabitacion = new System.Windows.Forms.TextBox();
             this.label14 = new System.Windows.Forms.Label();
             this.label15 = new System.Windows.Forms.Label();
             this.dtpIn = new System.Windows.Forms.DateTimePicker();
             this.dtpOut = new System.Windows.Forms.DateTimePicker();
             this.label16 = new System.Windows.Forms.Label();
             this.txtCantDias = new System.Windows.Forms.TextBox();
             this.Subtotal = new System.Windows.Forms.TextBox();
             this.label17 = new System.Windows.Forms.Label();
             this.tlpAgrupamiento = new System.Windows.Forms.TableLayoutPanel();
             this.label3 = new System.Windows.Forms.Label();
             this.label2 = new System.Windows.Forms.Label();
             this.label4 = new System.Windows.Forms.Label();
             this.txtNumeroTarjeta = new System.Windows.Forms.TextBox();
             this.cmbTarjeta = new System.Windows.Forms.ComboBox();
             this.label1 = new System.Windows.Forms.Label();
             this.label11 = new System.Windows.Forms.Label();
             this.txtNumeroFactura = new System.Windows.Forms.TextBox();
             this.rdbCredito = new System.Windows.Forms.RadioButton();
             this.rdbContado = new System.Windows.Forms.RadioButton();
             this.cmbEstado = new System.Windows.Forms.ComboBox();
             this.tableLayoutPanel2 = new System.Windows.Forms.TableLayoutPanel();
             this.label8 = new System.Windows.Forms.Label();
             this.label9 = new System.Windows.Forms.Label();
             this.label10 = new System.Windows.Forms.Label();
             this.txtSubtotal = new System.Windows.Forms.TextBox();
             this.txtImpuesto = new System.Windows.Forms.TextBox();
             this.txtTotal = new System.Windows.Forms.TextBox();
             this.groupBox2 = new System.Windows.Forms.GroupBox();
             this.dgvDetalleFactura = new System.Windows.Forms.DataGridView();
             this.NoFactura = new System.Windows.Forms.DataGridViewTextBoxColumn();
             this.Detalle = new System.Windows.Forms.DataGridViewTextBoxColumn();
             this.Precio = new System.Windows.Forms.DataGridViewTextBoxColumn();
             this.IDReservacion = new System.Windows.Forms.DataGridViewTextBoxColumn();
             this.NumTarjeta = new System.Windows.Forms.DataGridViewTextBoxColumn();
             this.Fecha = new System.Windows.Forms.DataGridViewTextBoxColumn();
             this.Estado = new System.Windows.Forms.DataGridViewTextBoxColumn();
             this.erpError = new System.Windows.Forms.ErrorProvider(this.components);
             this.tspBarraSuperior.SuspendLayout();
             ((System.ComponentModel.ISupportInitialize)(this.splitContainer1)).BeginInit();
             this.splitContainer1.Panel1.SuspendLayout();
             this.splitContainer1.Panel2.SuspendLayout();
             this.splitContainer1.SuspendLayout();
             this.groupBox1.SuspendLayout();
             this.tableLayoutPanel3.SuspendLayout();
             this.tlpAgrupamiento.SuspendLayout();
             this.tableLayoutPanel2.SuspendLayout();
             this.groupBox2.SuspendLayout();
             ((System.ComponentModel.ISupportInitialize)(this.dgvDetalleFactura)).BeginInit();
             ((System.ComponentModel.ISupportInitialize)(this.erpError)).BeginInit();
             this.SuspendLayout();
             //
             // tspBarraSuperior
             //
             this.tspBarraSuperior.Items.AddRange(new System.Windows.Forms.ToolStripItem[] {
             this.toolStripBtnNuevo,
             this.toolStripBtnFacturar,
             this.toolStripBtnSalir});
             this.tspBarraSuperior.Location = new System.Drawing.Point(0, 0);
             this.tspBarraSuperior.Name = "tspBarraSuperior";
             this.tspBarraSuperior.Size = new System.Drawing.Size(1176, 55);
             this.tspBarraSuperior.TabIndex = 2;
             this.tspBarraSuperior.Text = "toolStrip1";
             //
             // toolStripBtnNuevo
             //
             this.toolStripBtnNuevo.Image = global::UTN.Winform.AppAirBnB.Properties.Resources._48_48_5fcb865b3ad895719c10c7bfe5771fa4_pen;
             this.toolStripBtnNuevo.ImageScaling = System.Windows.Forms.ToolStripItemImageScaling.None;
             this.toolStripBtnNuevo.ImageTransparentColor = System.Drawing.Color.Magenta;
             this.toolStripBtnNuevo.Name = "toolStripBtnNuevo";
             this.toolStripBtnNuevo.Size = new System.Drawing.Size(94, 52);
             this.toolStripBtnNuevo.Text = "Nuevo";
             this.toolStripBtnNuevo.Click += new System.EventHandler(this.toolStripBtnNuevo_Click);
             //
             // toolStripBtnFacturar
             //
             this.toolStripBtnFacturar.Image = global::UTN.Winform.AppAirBnB.Properties.Resources._48_48_2105a9c63eeaa7a280f82fb9c0ce8123_bulb;
             this.toolStripBtnFacturar.ImageScaling = System.Windows.Forms.ToolStripItemImageScaling.None;
             this.toolStripBtnFacturar.ImageTransparentColor = System.Drawing.Color.Magenta;
             this.toolStripBtnFacturar.Name = "toolStripBtnFacturar";
             this.toolStripBtnFacturar.Size = new System.Drawing.Size(102, 52);
             this.toolStripBtnFacturar.Text = "Facturar";
             this.toolStripBtnFacturar.Click += new System.EventHandler(this.toolStripBtnFacturar_Click);
             //
             // toolStripBtnSalir
             //
             this.toolStripBtnSalir.Image = global::UTN.Winform.AppAirBnB.Properties.Resources._48_48_10696bc060189f66efd1c9d2397cac66_bullseye;
             this.toolStripBtnSalir.ImageScaling = System.Windows.Forms.ToolStripItemImageScaling.None;
             this.toolStripBtnSalir.ImageTransparentColor = System.Drawing.Color.Magenta;
             this.toolStripBtnSalir.Name = "toolStripBtnSalir";
             this.toolStripBtnSalir.Size = new System.Drawing.Size(81, 52);
             this.toolStripBtnSalir.Text = "Salir";
             this.toolStripBtnSalir.Click += new System.EventHandler(this.toolStripBtnSalir_Click);
             //
             // sttBarraInferior
             //
             this.sttBarraInferior.Location = new System.Drawing.Point(0, 495);
             this.sttBarraInferior.Name = "sttBarraInferior";
             this.sttBarraInferior.Size = new System.Drawing.Size(1176, 22);
             this.sttBarraInferior.TabIndex = 3;
             this.sttBarraInferior.Text = "statusStrip1";
             //
             // splitContainer1
             //
             this.splitContainer1.Dock = System.Windows.Forms.DockStyle.Fill;
             this.splitContainer1.Location = new System.Drawing.Point(0, 55);
             this.splitContainer1.Name = "splitContainer1";
             //
             // splitContainer1.Panel1
             //
             this.splitContainer1.Panel1.Controls.Add(this.groupBox1);
             //
             // splitContainer1.Panel2
             //
             this.splitContainer1.Panel2.Controls.Add(this.tableLayoutPanel2);
             this.splitContainer1.Panel2.Controls.Add(this.groupBox2);
             this.splitContainer1.Size = new System.Drawing.Size(1176, 440);
             this.splitContainer1.SplitterDistance = 556;
             this.splitContainer1.TabIndex = 4;
             //
             // groupBox1
             //
             this.groupBox1.Controls.Add(this.tableLayoutPanel3);
             this.groupBox1.Controls.Add(this.tlpAgrupamiento);
             this.groupBox1.Location = new System.Drawing.Point(12, 3);
             this.groupBox1.Name = "groupBox1";
             this.groupBox1.Size = new System.Drawing.Size(521, 464);
             this.groupBox1.TabIndex = 7;
             this.groupBox1.TabStop = false;
             this.groupBox1.Text = "Facturacin";
             //
             // tableLayoutPanel3
             //
             this.tableLayoutPanel3.ColumnCount = 3;
             this.tableLayoutPanel3.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 37.9822F));
             this.tableLayoutPanel3.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 62.0178F));
             this.tableLayoutPanel3.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Absolute, 166F));
             this.tableLayoutPanel3.Controls.Add(this.btnBuscarReserva, 2, 0);
             this.tableLayoutPanel3.Controls.Add(this.btnAgregar, 2, 3);
             this.tableLayoutPanel3.Controls.Add(this.label5, 0, 1);
             this.tableLayoutPanel3.Controls.Add(this.mskIDReserva, 1, 1);
             this.tableLayoutPanel3.Controls.Add(this.label13, 0, 0);
             this.tableLayoutPanel3.Controls.Add(this.txtNUMDetalle, 1, 0);
             this.tableLayoutPanel3.Controls.Add(this.label7, 0, 3);
             this.tableLayoutPanel3.Controls.Add(this.txtPrecio, 1, 3);
             this.tableLayoutPanel3.Controls.Add(this.label6, 0, 4);
             this.tableLayoutPanel3.Controls.Add(this.txtIdHuesped, 1, 4);
             this.tableLayoutPanel3.Controls.Add(this.label12, 0, 5);
             this.tableLayoutPanel3.Controls.Add(this.txtNumHabitacion, 1, 5);
             this.tableLayoutPanel3.Controls.Add(this.label14, 0, 6);
             this.tableLayoutPanel3.Controls.Add(this.label15, 0, 7);
             this.tableLayoutPanel3.Controls.Add(this.dtpIn, 1, 6);
             this.tableLayoutPanel3.Controls.Add(this.dtpOut, 1, 7);
             this.tableLayoutPanel3.Controls.Add(this.label16, 0, 8);
             this.tableLayoutPanel3.Controls.Add(this.txtCantDias, 1, 8);
             this.tableLayoutPanel3.Controls.Add(this.Subtotal, 1, 9);
             this.tableLayoutPanel3.Controls.Add(this.label17, 0, 9);
             this.tableLayoutPanel3.Location = new System.Drawing.Point(16, 168);
             this.tableLayoutPanel3.Name = "tableLayoutPanel3";
             this.tableLayoutPanel3.RowCount = 10;
             this.tableLayoutPanel3.RowStyles.Add(new System.Windows.Forms.RowStyle());
             this.tableLayoutPanel3.RowStyles.Add(new System.Windows.Forms.RowStyle());
             this.tableLayoutPanel3.RowStyles.Add(new System.Windows.Forms.RowStyle());
             this.tableLayoutPanel3.RowStyles.Add(new System.Windows.Forms.RowStyle());
             this.tableLayoutPanel3.RowStyles.Add(new System.Windows.Forms.RowStyle());
             this.tableLayoutPanel3.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 20F));
             this.tableLayoutPanel3.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 32F));
             this.tableLayoutPanel3.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 29F));
             this.tableLayoutPanel3.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 24F));
             this.tableLayoutPanel3.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 11F));
             this.tableLayoutPanel3.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 20F));
             this.tableLayoutPanel3.Size = new System.Drawing.Size(493, 266);
             this.tableLayoutPanel3.TabIndex = 8;
             //
             // btnBuscarReserva
             //
             this.btnBuscarReserva.Location = new System.Drawing.Point(329, 3);
             this.btnBuscarReserva.Name = "btnBuscarReserva";
             this.tableLayoutPanel3.SetRowSpan(this.btnBuscarReserva, 2);
             this.btnBuscarReserva.Size = new System.Drawing.Size(110, 67);
             this.btnBuscarReserva.TabIndex = 1;
             this.btnBuscarReserva.Text = "Buscar";
             this.btnBuscarReserva.TextImageRelation = System.Windows.Forms.TextImageRelation.ImageBeforeText;
             this.btnBuscarReserva.UseVisualStyleBackColor = true;
             this.btnBuscarReserva.Click += new System.EventHandler(this.btnBuscarReserva_Click);
             //
             // btnAgregar
             //
             this.btnAgregar.Location = new System.Drawing.Point(329, 76);
             this.btnAgregar.Name = "btnAgregar";
             this.tableLayoutPanel3.SetRowSpan(this.btnAgregar, 2);
             this.btnAgregar.Size = new System.Drawing.Size(110, 57);
             this.btnAgregar.TabIndex = 7;
             this.btnAgregar.Text = "Agregar";
             this.btnAgregar.TextImageRelation = System.Windows.Forms.TextImageRelation.ImageBeforeText;
             this.btnAgregar.UseVisualStyleBackColor = true;
             this.btnAgregar.Click += new System.EventHandler(this.btnAgregar_Click);
             //
             // label5
             //
             this.label5.AutoSize = true;
             this.label5.Location = new System.Drawing.Point(3, 26);
             this.label5.Name = "label5";
             this.label5.Size = new System.Drawing.Size(81, 13);
             this.label5.TabIndex = 0;
             this.label5.Text = "ID Reservacion";
             //
             // mskIDReserva
             //
             this.mskIDReserva.Location = new System.Drawing.Point(127, 29);
             this.mskIDReserva.Mask = "99999999999";
             this.mskIDReserva.Name = "mskIDReserva";
             this.mskIDReserva.Size = new System.Drawing.Size(196, 20);
             this.mskIDReserva.TabIndex = 4;
             //
             // label13
             //
             this.label13.AutoSize = true;
             this.label13.Location = new System.Drawing.Point(3, 0);
             this.label13.Name = "label13";
             this.label13.Size = new System.Drawing.Size(80, 13);
             this.label13.TabIndex = 12;
             this.label13.Text = "Numero Detalle";
             //
             // txtNUMDetalle
             //
             this.txtNUMDetalle.Location = new System.Drawing.Point(127, 3);
             this.txtNUMDetalle.Name = "txtNUMDetalle";
             this.txtNUMDetalle.Size = new System.Drawing.Size(196, 20);
             this.txtNUMDetalle.TabIndex = 13;
             this.txtNUMDetalle.Text = "1";
             //
             // label7
             //
             this.label7.AutoSize = true;
             this.label7.Location = new System.Drawing.Point(3, 73);
             this.label7.Name = "label7";
             this.label7.Size = new System.Drawing.Size(37, 13);
             this.label7.TabIndex = 9;
             this.label7.Text = "Precio";
             //
             // txtPrecio
             //
             this.txtPrecio.Location = new System.Drawing.Point(127, 76);
             this.txtPrecio.Name = "txtPrecio";
             this.txtPrecio.Size = new System.Drawing.Size(196, 20);
             this.txtPrecio.TabIndex = 10;
             //
             // label6
             //
             this.label6.AutoSize = true;
             this.label6.Location = new System.Drawing.Point(3, 99);
             this.label6.Name = "label6";
             this.label6.Size = new System.Drawing.Size(61, 13);
             this.label6.TabIndex = 14;
             this.label6.Text = "IDHuesped";
             //
             // txtIdHuesped
             //
             this.txtIdHuesped.Location = new System.Drawing.Point(127, 102);
             this.txtIdHuesped.Name = "txtIdHuesped";
             this.txtIdHuesped.Size = new System.Drawing.Size(196, 20);
             this.txtIdHuesped.TabIndex = 15;
             //
             // label12
             //
             this.label12.AutoSize = true;
             this.label12.Location = new System.Drawing.Point(3, 136);
             this.label12.Name = "label12";
             this.label12.Size = new System.Drawing.Size(96, 13);
             this.label12.TabIndex = 16;
             this.label12.Text = "Numero habitacion";
             //
             // txtNumHabitacion
             //
             this.txtNumHabitacion.Location = new System.Drawing.Point(127, 139);
             this.txtNumHabitacion.Name = "txtNumHabitacion";
             this.txtNumHabitacion.Size = new System.Drawing.Size(196, 20);
             this.txtNumHabitacion.TabIndex = 17;
             //
             // label14
             //
             this.label14.AutoSize = true;
             this.label14.Location = new System.Drawing.Point(3, 156);
             this.label14.Name = "label14";
             this.label14.Size = new System.Drawing.Size(47, 13);
             this.label14.TabIndex = 18;
             this.label14.Text = "CheckIn";
             //
             // label15
             //
             this.label15.AutoSize = true;
             this.label15.Location = new System.Drawing.Point(3, 188);
             this.label15.Name = "label15";
             this.label15.Size = new System.Drawing.Size(55, 13);
             this.label15.TabIndex = 19;
             this.label15.Text = "CheckOut";
             //
             // dtpIn
             //
             this.dtpIn.Location = new System.Drawing.Point(127, 159);
             this.dtpIn.Name = "dtpIn";
             this.dtpIn.Size = new System.Drawing.Size(196, 20);
             this.dtpIn.TabIndex = 20;
             //
             // dtpOut
             //
             this.dtpOut.Location = new System.Drawing.Point(127, 191);
             this.dtpOut.Name = "dtpOut";
             this.dtpOut.Size = new System.Drawing.Size(196, 20);
             this.dtpOut.TabIndex = 21;
             //
             // label16
             //
             this.label16.AutoSize = true;
             this.label16.Location = new System.Drawing.Point(3, 217);
             this.label16.Name = "label16";
             this.label16.Size = new System.Drawing.Size(73, 13);
             this.label16.TabIndex = 22;
             this.label16.Text = "Cantidad Dias";
             //
             // txtCantDias
             //
             this.txtCantDias.Location = new System.Drawing.Point(127, 220);
             this.txtCantDias.Name = "txtCantDias";
             this.txtCantDias.Size = new System.Drawing.Size(196, 20);
             this.txtCantDias.TabIndex = 23;
             //
             // Subtotal
             //
             this.Subtotal.Location = new System.Drawing.Point(127, 244);
             this.Subtotal.Name = "Subtotal";
             this.Subtotal.Size = new System.Drawing.Size(196, 20);
             this.Subtotal.TabIndex = 24;
             //
             // label17
             //
             this.label17.AutoSize = true;
             this.label17.Location = new System.Drawing.Point(3, 241);
             this.label17.Name = "label17";
             this.label17.Size = new System.Drawing.Size(46, 13);
             this.label17.TabIndex = 25;
             this.label17.Text = "Subtotal";
             //
             // tlpAgrupamiento
             //
             this.tlpAgrupamiento.BackColor = System.Drawing.SystemColors.Control;
             this.tlpAgrupamiento.ColumnCount = 3;
             this.tlpAgrupamiento.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Absolute, 129F));
             this.tlpAgrupamiento.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Absolute, 208F));
             this.tlpAgrupamiento.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Absolute, 306F));
             this.tlpAgrupamiento.Controls.Add(this.label3, 0, 4);
             this.tlpAgrupamiento.Controls.Add(this.label2, 0, 3);
             this.tlpAgrupamiento.Controls.Add(this.label4, 0, 2);
             this.tlpAgrupamiento.Controls.Add(this.txtNumeroTarjeta, 1, 3);
             this.tlpAgrupamiento.Controls.Add(this.cmbTarjeta, 1, 2);
             this.tlpAgrupamiento.Controls.Add(this.label1, 0, 1);
             this.tlpAgrupamiento.Controls.Add(this.label11, 0, 0);
             this.tlpAgrupamiento.Controls.Add(this.txtNumeroFactura, 1, 0);
             this.tlpAgrupamiento.Controls.Add(this.rdbCredito, 2, 1);
             this.tlpAgrupamiento.Controls.Add(this.rdbContado, 1, 1);
             this.tlpAgrupamiento.Controls.Add(this.cmbEstado, 1, 4);
             this.tlpAgrupamiento.Location = new System.Drawing.Point(16, 29);
             this.tlpAgrupamiento.Name = "tlpAgrupamiento";
             this.tlpAgrupamiento.RowCount = 5;
             this.tlpAgrupamiento.RowStyles.Add(new System.Windows.Forms.RowStyle());
             this.tlpAgrupamiento.RowStyles.Add(new System.Windows.Forms.RowStyle());
             this.tlpAgrupamiento.RowStyles.Add(new System.Windows.Forms.RowStyle());
             this.tlpAgrupamiento.RowStyles.Add(new System.Windows.Forms.RowStyle());
             this.tlpAgrupamiento.RowStyles.Add(new System.Windows.Forms.RowStyle());
             this.tlpAgrupamiento.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 20F));
             this.tlpAgrupamiento.Size = new System.Drawing.Size(493, 139);
             this.tlpAgrupamiento.TabIndex = 2;
             //
             // label3
             //
             this.label3.AutoSize = true;
             this.label3.Location = new System.Drawing.Point(3, 102);
             this.label3.Name = "label3";
             this.label3.Size = new System.Drawing.Size(79, 13);
             this.label3.TabIndex = 2;
             this.label3.Text = "Estado Factura";
             //
             // label2
             //
             this.label2.AutoSize = true;
             this.label2.Location = new System.Drawing.Point(3, 76);
             this.label2.Name = "label2";
             this.label2.Size = new System.Drawing.Size(57, 13);
             this.label2.TabIndex = 1;
             this.label2.Text = "No Tarjeta";
             //
             // label4
             //
             this.label4.AutoSize = true;
             this.label4.Location = new System.Drawing.Point(3, 49);
             this.label4.Name = "label4";
             this.label4.Size = new System.Drawing.Size(40, 13);
             this.label4.TabIndex = 3;
             this.label4.Text = "Tarjeta";
             //
             // txtNumeroTarjeta
             //
             this.txtNumeroTarjeta.Location = new System.Drawing.Point(132, 79);
             this.txtNumeroTarjeta.Name = "txtNumeroTarjeta";
             this.txtNumeroTarjeta.Size = new System.Drawing.Size(200, 20);
             this.txtNumeroTarjeta.TabIndex = 6;
             //
             // cmbTarjeta
             //
             this.cmbTarjeta.FormattingEnabled = true;
             this.cmbTarjeta.Location = new System.Drawing.Point(132, 52);
             this.cmbTarjeta.Name = "cmbTarjeta";
             this.cmbTarjeta.Size = new System.Drawing.Size(200, 21);
             this.cmbTarjeta.TabIndex = 7;
             //
             // label1
             //
             this.label1.AutoSize = true;
             this.label1.Location = new System.Drawing.Point(3, 26);
             this.label1.Name = "label1";
             this.label1.Size = new System.Drawing.Size(56, 13);
             this.label1.TabIndex = 0;
             this.label1.Text = "Tipo Pago";
             //
             // label11
             //
             this.label11.AutoSize = true;
             this.label11.Location = new System.Drawing.Point(3, 0);
             this.label11.Name = "label11";
             this.label11.Size = new System.Drawing.Size(63, 13);
             this.label11.TabIndex = 11;
             this.label11.Text = "No. Factura";
             //
             // txtNumeroFactura
             //
             this.txtNumeroFactura.Location = new System.Drawing.Point(132, 3);
             this.txtNumeroFactura.Name = "txtNumeroFactura";
             this.txtNumeroFactura.ReadOnly = true;
             this.txtNumeroFactura.Size = new System.Drawing.Size(200, 20);
             this.txtNumeroFactura.TabIndex = 12;
             //
             // rdbCredito
             //
             this.rdbCredito.AutoSize = true;
             this.rdbCredito.Checked = true;
             this.rdbCredito.Location = new System.Drawing.Point(340, 29);
             this.rdbCredito.Name = "rdbCredito";
             this.tlpAgrupamiento.SetRowSpan(this.rdbCredito, 2);
             this.rdbCredito.Size = new System.Drawing.Size(58, 17);
             this.rdbCredito.TabIndex = 5;
             this.rdbCredito.TabStop = true;
             this.rdbCredito.Text = "Crdito";
             this.rdbCredito.UseVisualStyleBackColor = true;
             //
             // rdbContado
             //
             this.rdbContado.AutoSize = true;
             this.rdbContado.Enabled = false;
             this.rdbContado.Location = new System.Drawing.Point(132, 29);
             this.rdbContado.Name = "rdbContado";
             this.rdbContado.Size = new System.Drawing.Size(65, 17);
             this.rdbContado.TabIndex = 4;
             this.rdbContado.Text = "Contado";
             this.rdbContado.UseVisualStyleBackColor = true;
             //
             // cmbEstado
             //
             this.cmbEstado.FormattingEnabled = true;
             this.cmbEstado.Location = new System.Drawing.Point(132, 105);
             this.cmbEstado.Name = "cmbEstado";
             this.cmbEstado.Size = new System.Drawing.Size(200, 21);
             this.cmbEstado.TabIndex = 15;
             //
             // tableLayoutPanel2
             //
             this.tableLayoutPanel2.ColumnCount = 2;
             this.tableLayoutPanel2.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 34.68208F));
             this.tableLayoutPanel2.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 65.31792F));
             this.tableLayoutPanel2.Controls.Add(this.label8, 0, 0);
             this.tableLayoutPanel2.Controls.Add(this.label9, 0, 1);
             this.tableLayoutPanel2.Controls.Add(this.label10, 0, 2);
             this.tableLayoutPanel2.Controls.Add(this.txtSubtotal, 1, 0);
             this.tableLayoutPanel2.Controls.Add(this.txtImpuesto, 1, 1);
             this.tableLayoutPanel2.Controls.Add(this.txtTotal, 1, 2);
             this.tableLayoutPanel2.Location = new System.Drawing.Point(375, 352);
             this.tableLayoutPanel2.Name = "tableLayoutPanel2";
             this.tableLayoutPanel2.RowCount = 3;
             this.tableLayoutPanel2.RowStyles.Add(new System.Windows.Forms.RowStyle());
             this.tableLayoutPanel2.RowStyles.Add(new System.Windows.Forms.RowStyle());
             this.tableLayoutPanel2.RowStyles.Add(new System.Windows.Forms.RowStyle());
             this.tableLayoutPanel2.Size = new System.Drawing.Size(173, 81);
             this.tableLayoutPanel2.TabIndex = 10;
             //
             // label8
             //
             this.label8.AutoSize = true;
             this.label8.Location = new System.Drawing.Point(3, 0);
             this.label8.Name = "label8";
             this.label8.Size = new System.Drawing.Size(46, 13);
             this.label8.TabIndex = 0;
             this.label8.Text = "Subtotal";
             //
             // label9
             //
             this.label9.AutoSize = true;
             this.label9.Location = new System.Drawing.Point(3, 26);
             this.label9.Name = "label9";
             this.label9.Size = new System.Drawing.Size(50, 13);
             this.label9.TabIndex = 1;
             this.label9.Text = "Impuesto";
             //
             // label10
             //
             this.label10.AutoSize = true;
             this.label10.Location = new System.Drawing.Point(3, 52);
             this.label10.Name = "label10";
             this.label10.Size = new System.Drawing.Size(31, 13);
             this.label10.TabIndex = 2;
             this.label10.Text = "Total";
             //
             // txtSubtotal
             //
             this.txtSubtotal.Location = new System.Drawing.Point(62, 3);
             this.txtSubtotal.Name = "txtSubtotal";
             this.txtSubtotal.ReadOnly = true;
             this.txtSubtotal.Size = new System.Drawing.Size(108, 20);
             this.txtSubtotal.TabIndex = 3;
             this.txtSubtotal.TextAlign = System.Windows.Forms.HorizontalAlignment.Right;
             //
             // txtImpuesto
             //
             this.txtImpuesto.Location = new System.Drawing.Point(62, 29);
             this.txtImpuesto.Name = "txtImpuesto";
             this.txtImpuesto.ReadOnly = true;
             this.txtImpuesto.Size = new System.Drawing.Size(108, 20);
             this.txtImpuesto.TabIndex = 4;
             this.txtImpuesto.TextAlign = System.Windows.Forms.HorizontalAlignment.Right;
             //
             // txtTotal
             //
             this.txtTotal.Location = new System.Drawing.Point(62, 55);
             this.txtTotal.Name = "txtTotal";
             this.txtTotal.ReadOnly = true;
             this.txtTotal.Size = new System.Drawing.Size(108, 20);
             this.txtTotal.TabIndex = 5;
             this.txtTotal.TextAlign = System.Windows.Forms.HorizontalAlignment.Right;
             //
             // groupBox2
             //
             this.groupBox2.Controls.Add(this.dgvDetalleFactura);
             this.groupBox2.Location = new System.Drawing.Point(5, 16);
             this.groupBox2.Name = "groupBox2";
             this.groupBox2.Size = new System.Drawing.Size(555, 318);
             this.groupBox2.TabIndex = 9;
             this.groupBox2.TabStop = false;
             this.groupBox2.Text = "Detalle";
             //
             // dgvDetalleFactura
             //
             this.dgvDetalleFactura.AllowUserToAddRows = false;
             this.dgvDetalleFactura.AllowUserToDeleteRows = false;
             this.dgvDetalleFactura.ColumnHeadersHeightSizeMode = System.Windows.Forms.DataGridViewColumnHeadersHeightSizeMode.AutoSize;
             this.dgvDetalleFactura.Columns.AddRange(new System.Windows.Forms.DataGridViewColumn[] {
             this.NoFactura,
             this.Detalle,
             this.Precio,
             this.IDReservacion,
             this.NumTarjeta,
             this.Fecha,
             this.Estado});
             this.dgvDetalleFactura.Dock = System.Windows.Forms.DockStyle.Fill;
             this.dgvDetalleFactura.Location = new System.Drawing.Point(3, 16);
             this.dgvDetalleFactura.Name = "dgvDetalleFactura";
             this.dgvDetalleFactura.ReadOnly = true;
             this.dgvDetalleFactura.Size = new System.Drawing.Size(549, 299);
             this.dgvDetalleFactura.TabIndex = 5;
             //
             // NoFactura
             //
             this.NoFactura.DataPropertyName = "IDFactura";
             this.NoFactura.HeaderText = "NoFactura";
             this.NoFactura.Name = "NoFactura";
             this.NoFactura.ReadOnly = true;
             //
             // Detalle
             //
             this.Detalle.DataPropertyName = "Numero";
             this.Detalle.HeaderText = "Detalle";
             this.Detalle.Name = "Detalle";
             this.Detalle.ReadOnly = true;
             //
             // Precio
             //
             this.Precio.DataPropertyName = "Precio";
             this.Precio.HeaderText = "Precio";
             this.Precio.Name = "Precio";
             this.Precio.ReadOnly = true;
             //
             // IDReservacion
             //
             this.IDReservacion.DataPropertyName = "IDReservacion";
             this.IDReservacion.HeaderText = "IDReservacion";
             this.IDReservacion.Name = "IDReservacion";
             this.IDReservacion.ReadOnly = true;
             //
             // NumTarjeta
             //
             this.NumTarjeta.DataPropertyName = "IDTarjeta";
             this.NumTarjeta.HeaderText = "NumTarjeta";
             this.NumTarjeta.Name = "NumTarjeta";
             this.NumTarjeta.ReadOnly = true;
             //
             // Fecha
             //
             this.Fecha.DataPropertyName = "Fecha";
             this.Fecha.HeaderText = "Fecha";
             this.Fecha.Name = "Fecha";
             this.Fecha.ReadOnly = true;
             //
             // Estado
             //
             this.Estado.DataPropertyName = "EstadoFact";
             this.Estado.HeaderText = "Estado";
             this.Estado.Name = "Estado";
             this.Estado.ReadOnly = true;
             //
             // erpError
             //
             this.erpError.ContainerControl = this;
             //
             // frmFacturacion
             //
             this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
             this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
             this.ClientSize = new System.Drawing.Size(1176, 517);
             this.Controls.Add(this.splitContainer1);
             this.Controls.Add(this.sttBarraInferior);
             this.Controls.Add(this.tspBarraSuperior);
             this.Name = "frmFacturacion";
             this.Text = "Facturacion";
             this.WindowState = System.Windows.Forms.FormWindowState.Maximized;
             this.Load += new System.EventHandler(this.frmFacturacion_Load);
             this.tspBarraSuperior.ResumeLayout(false);
             this.tspBarraSuperior.PerformLayout();
             this.splitContainer1.Panel1.ResumeLayout(false);
             this.splitContainer1.Panel2.ResumeLayout(false);
             ((System.ComponentModel.ISupportInitialize)(this.splitContainer1)).EndInit();
             this.splitContainer1.ResumeLayout(false);
             this.groupBox1.ResumeLayout(false);
             this.tableLayoutPanel3.ResumeLayout(false);
             this.tableLayoutPanel3.PerformLayout();
             this.tlpAgrupamiento.ResumeLayout(false);
             this.tlpAgrupamiento.PerformLayout();
             this.tableLayoutPanel2.ResumeLayout(false);
             this.tableLayoutPanel2.PerformLayout();
             this.groupBox2.ResumeLayout(false);
             ((System.ComponentModel.ISupportInitialize)(this.dgvDetalleFactura)).EndInit();
             ((System.ComponentModel.ISupportInitialize)(this.erpError)).EndInit();
             this.ResumeLayout(false);
             this.PerformLayout();
         }
toolStripBtnFacturar_Click()
void UTN.Winform.AppAirBnB.Layers.UI.Procesos.frmFacturacion.toolStripBtnFacturar_Click (object sender, EventArgs e) private
Definition at line 114 of file frmFacturacion.cs.
References UTN.Winform.AppAirBnB.Layers.Entities.DetFactura._EncFactura, UTN.Winform.AppAirBnB.Layers.Entities.DetFactura._Impuesto, UTN.Winform.AppAirBnB.Layers.Entities.EncFactura._ListaFacturaDetalle, UTN.Winform.AppAirBnB.Layers.Entities.DetFactura._Reservacion, UTN.Winform.AppAirBnB.Layers.Entities.EncFactura.AddDetalle(), UTN.Winform.AppAirBnB.Layers.Interface.IBLLEncFactura.GetCurrentNumeroFactura(), UTN.Winform.AppAirBnB.Layers.Interface.IBLLEncFactura.GetFactura(), UTN.Winform.AppAirBnB.Layers.Interface.IBLLImpuesto.GetImpuesto(), UTN.Winform.AppAirBnB.Layers.Entities.EncFactura.GetImpuesto(), UTN.Winform.AppAirBnB.Layers.Interface.IBLLReservacion.GetReserva(), UTN.Winform.AppAirBnB.Layers.Entities.EncFactura.GetSubTotal(), UTN.Winform.AppAirBnB.Layers.Entities.DetFactura.Numero, UTN.Winform.AppAirBnB.Layers.Entities.DetFactura.Precio, UTN.Winform.AppAirBnB.Util.QuickResponse.QuickResponseGenerador(), UTN.Winform.AppAirBnB.Layers.Interface.IBLLEncFactura.SaveFactura(), and UTN.Winform.AppAirBnB.Layers.Entities.Tarjeta.ToString().
         {
             IBLLEncFactura _BLLFactura = new BLLEncFactura();
             IBLLTarjeta _BLLTarjeta = new BLLTarjeta();
             IBLLHuesped _BLLHuesped = new BLLHuesped();
             IBLLHabitacion _BLLHabitacion = new BLLHabitacion();
             IBLLImpuesto _BLLImpuesto = new BLLImpuesto();
             DetFactura oFacturaDetalle = new DetFactura();
             this.cmbEstado.SelectedIndex = 1;
             IBLLReservacion _BLLReservacion = new BLLReservacion();
             Tarjeta oTarjeta = new Tarjeta();
             string rutaImagen = @"c:\temp\qr.png";
             double numeroFactura = 0d;
             try
             {
                 _FacturaEncabezado = new EncFactura()
                 {
                     IDFactura = Double.Parse(this.txtNumeroFactura.Text),
                     _Tarjeta = cmbTarjeta.SelectedItem as Tarjeta,//_BLLTarjeta.GetTarjetaById(Double.Parse(this.txtNumeroTarjeta.Text)),
                     Fecha = DateTime.Now,
                     EstadoFact = this.cmbEstado.SelectedIndex.ToString(),
                 };
                 oFacturaDetalle._EncFactura = _BLLFactura.GetFactura(Double.Parse(this.txtNumeroFactura.Text));
                 oFacturaDetalle._Reservacion = _BLLReservacion.GetReserva(Double.Parse(this.mskIDReserva.Text.ToString()));
                 oFacturaDetalle.Precio = Double.Parse(this.txtPrecio.Text.ToString());
                 // Calcular el Impuesto
                 IBLLImpuesto _BLLImpuestotest = new BLLImpuesto();
                 oFacturaDetalle._Impuesto = _BLLImpuestotest.GetImpuesto();
                 // Enumerar la secuencia
                 oFacturaDetalle.Numero = _FacturaEncabezado._ListaFacturaDetalle.Count == 0 ?
                                                  1 : _FacturaEncabezado._ListaFacturaDetalle.Max(p => p.Numero) + 1;
                 ;
                 // Agregar
                 _FacturaEncabezado.AddDetalle(oFacturaDetalle);
                 if (_FacturaEncabezado == null)
                 {
                     MessageBox.Show("No hay datos por facturar", "Error", MessageBoxButtons.OK, MessageBoxIcon.Error);
                     return;
                 }
                 if (_FacturaEncabezado._ListaFacturaDetalle.Count == 0)
                 {
                     MessageBox.Show("No hay items en la factura ", "Error", MessageBoxButtons.OK, MessageBoxIcon.Error);
                     return;
                 }
                 this.txtSubtotal.Text = _FacturaEncabezado.GetSubTotal().ToString();
                 this.txtImpuesto.Text = _FacturaEncabezado.GetImpuesto().ToString();
                 this.txtTotal.Text = (_FacturaEncabezado.GetSubTotal() + (_FacturaEncabezado.GetImpuesto())).ToString();
                 _FacturaEncabezado = _BLLFactura.SaveFactura(_FacturaEncabezado);
                 numeroFactura = _BLLFactura.GetCurrentNumeroFactura();
                 EstadoHabitaciones();
                 if (_FacturaEncabezado == null)
                     MessageBox.Show("Error al crear factura!", "Error", MessageBoxButtons.OK, MessageBoxIcon.Error);
                 else
                     //toolStripBtnNuevo_Click(null, null);
                 // Si existe borrelo
                 if (File.Exists(rutaImagen))
                     File.Delete(rutaImagen);
                 // Crear imagen quickresponse
                 Image quickResponseImage = QuickResponse.QuickResponseGenerador(numeroFactura.ToString(), 53);
                 // Salvarla en c:\temp para luego ser leida
                 quickResponseImage.Save(rutaImagen, ImageFormat.Png);
             }
             catch (Exception er)
             {
                 StringBuilder msg = new StringBuilder();
                 msg.AppendFormat("Message        {0}\n", er.Message);
                 msg.AppendFormat("Source         {0}\n", er.Source);
                 msg.AppendFormat("InnerException {0}\n", er.InnerException);
                 msg.AppendFormat("StackTrace     {0}\n", er.StackTrace);
                 msg.AppendFormat("TargetSite     {0}\n", er.TargetSite);
                 // Log error
                 _MyLogControlEventos.ErrorFormat("Error {0}", msg.ToString());
                 // Mensaje de Error
                 MessageBox.Show("Se ha producido el siguiente error " + er.Message, "Error", MessageBoxButtons.OK, MessageBoxIcon.Error);
             }
         }
toolStripBtnNuevo_Click()
void UTN.Winform.AppAirBnB.Layers.UI.Procesos.frmFacturacion.toolStripBtnNuevo_Click (object sender, EventArgs e) private
Definition at line 88 of file frmFacturacion.cs.
References UTN.Winform.AppAirBnB.Layers.Interface.IBLLEncFactura.GetNextNumeroFactura().
         {
             IBLLEncFactura _BLLFactura = new BLLEncFactura();
             this.txtNumeroFactura.Text = _BLLFactura.GetNextNumeroFactura().ToString();
             this.txtNumeroTarjeta.Text = "";
             this.txtNumHabitacion.Text = "";
             this.txtNUMDetalle.Text = "1";
             this.txtImpuesto.Text = "";
             this.txtIdHuesped.Text = "";
             this.txtCantDias.Text = "";
             this.txtPrecio.Text = "";
             this.txtSubtotal.Text = "";
             this.txtTotal.Text = "";
             this.cmbEstado.SelectedIndex = 0;
             this.cmbTarjeta.SelectedIndex = 0;
             this.Subtotal.Text = "";
             this.mskIDReserva.Text = "";
             this.dgvDetalleFactura.Rows.Clear() ;
             this.dgvDetalleFactura.Refresh();
         }
toolStripBtnSalir_Click()
void UTN.Winform.AppAirBnB.Layers.UI.Procesos.frmFacturacion.toolStripBtnSalir_Click (object sender, EventArgs e) private
Definition at line 261 of file frmFacturacion.cs.
         {
             Close();
         }
txtClienteId_MouseClick()
void UTN.Winform.AppAirBnB.Layers.UI.Procesos.frmFacturacion.txtClienteId_MouseClick (object sender, MouseEventArgs e) private
Definition at line 36 of file frmFacturacion.cs.
         {
         }
txtIdHuesped_TextChanged()
void UTN.Winform.AppAirBnB.Layers.UI.Procesos.frmFacturacion.txtIdHuesped_TextChanged (object sender, EventArgs e) private
Definition at line 392 of file frmFacturacion.cs.
         {
         }
Member Data Documentation
_FacturaEncabezado
EncFactura UTN.Winform.AppAirBnB.Layers.UI.Procesos.frmFacturacion._FacturaEncabezado = null private
Definition at line 27 of file frmFacturacion.cs.
_MyLogControlEventos
readonly ILog UTN.Winform.AppAirBnB.Layers.UI.Procesos.frmFacturacion._MyLogControlEventos = log4net.LogManager.GetLogger("MyControlEventos") static private
Definition at line 24 of file frmFacturacion.cs.
_Reservacion
Reservacion UTN.Winform.AppAirBnB.Layers.UI.Procesos.frmFacturacion._Reservacion = null private
Definition at line 26 of file frmFacturacion.cs.
btnAgregar
System.Windows.Forms.Button UTN.Winform.AppAirBnB.Layers.UI.Procesos.frmFacturacion.btnAgregar private
Definition at line 748 of file frmFacturacion.Designer.cs.
btnBuscarReserva
System.Windows.Forms.Button UTN.Winform.AppAirBnB.Layers.UI.Procesos.frmFacturacion.btnBuscarReserva private
Definition at line 746 of file frmFacturacion.Designer.cs.
cmbEstado
System.Windows.Forms.ComboBox UTN.Winform.AppAirBnB.Layers.UI.Procesos.frmFacturacion.cmbEstado private
Definition at line 750 of file frmFacturacion.Designer.cs.
cmbTarjeta
System.Windows.Forms.ComboBox UTN.Winform.AppAirBnB.Layers.UI.Procesos.frmFacturacion.cmbTarjeta private
Definition at line 728 of file frmFacturacion.Designer.cs.
components
System.ComponentModel.IContainer UTN.Winform.AppAirBnB.Layers.UI.Procesos.frmFacturacion.components = null private
Required designer variable.
Definition at line 8 of file frmFacturacion.Designer.cs.
cont
double UTN.Winform.AppAirBnB.Layers.UI.Procesos.frmFacturacion.cont = 0 private
Definition at line 29 of file frmFacturacion.cs.
Detalle
System.Windows.Forms.DataGridViewTextBoxColumn UTN.Winform.AppAirBnB.Layers.UI.Procesos.frmFacturacion.Detalle private
Definition at line 755 of file frmFacturacion.Designer.cs.
dgvDetalleFactura
System.Windows.Forms.DataGridView UTN.Winform.AppAirBnB.Layers.UI.Procesos.frmFacturacion.dgvDetalleFactura private
Definition at line 741 of file frmFacturacion.Designer.cs.
dtpIn
System.Windows.Forms.DateTimePicker UTN.Winform.AppAirBnB.Layers.UI.Procesos.frmFacturacion.dtpIn private
Definition at line 767 of file frmFacturacion.Designer.cs.
dtpOut
System.Windows.Forms.DateTimePicker UTN.Winform.AppAirBnB.Layers.UI.Procesos.frmFacturacion.dtpOut private
Definition at line 768 of file frmFacturacion.Designer.cs.
erpError
System.Windows.Forms.ErrorProvider UTN.Winform.AppAirBnB.Layers.UI.Procesos.frmFacturacion.erpError private
Definition at line 751 of file frmFacturacion.Designer.cs.
Estado
System.Windows.Forms.DataGridViewTextBoxColumn UTN.Winform.AppAirBnB.Layers.UI.Procesos.frmFacturacion.Estado private
Definition at line 760 of file frmFacturacion.Designer.cs.
Fecha
System.Windows.Forms.DataGridViewTextBoxColumn UTN.Winform.AppAirBnB.Layers.UI.Procesos.frmFacturacion.Fecha private
Definition at line 759 of file frmFacturacion.Designer.cs.
groupBox1
System.Windows.Forms.GroupBox UTN.Winform.AppAirBnB.Layers.UI.Procesos.frmFacturacion.groupBox1 private
Definition at line 722 of file frmFacturacion.Designer.cs.
groupBox2
System.Windows.Forms.GroupBox UTN.Winform.AppAirBnB.Layers.UI.Procesos.frmFacturacion.groupBox2 private
Definition at line 740 of file frmFacturacion.Designer.cs.
IDReservacion
System.Windows.Forms.DataGridViewTextBoxColumn UTN.Winform.AppAirBnB.Layers.UI.Procesos.frmFacturacion.IDReservacion private
Definition at line 757 of file frmFacturacion.Designer.cs.
label1
System.Windows.Forms.Label UTN.Winform.AppAirBnB.Layers.UI.Procesos.frmFacturacion.label1 private
Definition at line 729 of file frmFacturacion.Designer.cs.
label10
System.Windows.Forms.Label UTN.Winform.AppAirBnB.Layers.UI.Procesos.frmFacturacion.label10 private
Definition at line 736 of file frmFacturacion.Designer.cs.
label11
System.Windows.Forms.Label UTN.Winform.AppAirBnB.Layers.UI.Procesos.frmFacturacion.label11 private
Definition at line 730 of file frmFacturacion.Designer.cs.
label12
System.Windows.Forms.Label UTN.Winform.AppAirBnB.Layers.UI.Procesos.frmFacturacion.label12 private
Definition at line 763 of file frmFacturacion.Designer.cs.
label13
System.Windows.Forms.Label UTN.Winform.AppAirBnB.Layers.UI.Procesos.frmFacturacion.label13 private
Definition at line 752 of file frmFacturacion.Designer.cs.
label14
System.Windows.Forms.Label UTN.Winform.AppAirBnB.Layers.UI.Procesos.frmFacturacion.label14 private
Definition at line 765 of file frmFacturacion.Designer.cs.
label15
System.Windows.Forms.Label UTN.Winform.AppAirBnB.Layers.UI.Procesos.frmFacturacion.label15 private
Definition at line 766 of file frmFacturacion.Designer.cs.
label16
System.Windows.Forms.Label UTN.Winform.AppAirBnB.Layers.UI.Procesos.frmFacturacion.label16 private
Definition at line 769 of file frmFacturacion.Designer.cs.
label17
System.Windows.Forms.Label UTN.Winform.AppAirBnB.Layers.UI.Procesos.frmFacturacion.label17 private
Definition at line 772 of file frmFacturacion.Designer.cs.
label2
System.Windows.Forms.Label UTN.Winform.AppAirBnB.Layers.UI.Procesos.frmFacturacion.label2 private
Definition at line 725 of file frmFacturacion.Designer.cs.
label3
System.Windows.Forms.Label UTN.Winform.AppAirBnB.Layers.UI.Procesos.frmFacturacion.label3 private
Definition at line 724 of file frmFacturacion.Designer.cs.
label4
System.Windows.Forms.Label UTN.Winform.AppAirBnB.Layers.UI.Procesos.frmFacturacion.label4 private
Definition at line 726 of file frmFacturacion.Designer.cs.
label5
System.Windows.Forms.Label UTN.Winform.AppAirBnB.Layers.UI.Procesos.frmFacturacion.label5 private
Definition at line 749 of file frmFacturacion.Designer.cs.
label6
System.Windows.Forms.Label UTN.Winform.AppAirBnB.Layers.UI.Procesos.frmFacturacion.label6 private
Definition at line 761 of file frmFacturacion.Designer.cs.
label7
System.Windows.Forms.Label UTN.Winform.AppAirBnB.Layers.UI.Procesos.frmFacturacion.label7 private
Definition at line 744 of file frmFacturacion.Designer.cs.
label8
System.Windows.Forms.Label UTN.Winform.AppAirBnB.Layers.UI.Procesos.frmFacturacion.label8 private
Definition at line 734 of file frmFacturacion.Designer.cs.
label9
System.Windows.Forms.Label UTN.Winform.AppAirBnB.Layers.UI.Procesos.frmFacturacion.label9 private
Definition at line 735 of file frmFacturacion.Designer.cs.
mskIDReserva
System.Windows.Forms.MaskedTextBox UTN.Winform.AppAirBnB.Layers.UI.Procesos.frmFacturacion.mskIDReserva private
Definition at line 747 of file frmFacturacion.Designer.cs.
NoFactura
System.Windows.Forms.DataGridViewTextBoxColumn UTN.Winform.AppAirBnB.Layers.UI.Procesos.frmFacturacion.NoFactura private
Definition at line 754 of file frmFacturacion.Designer.cs.
NumTarjeta
System.Windows.Forms.DataGridViewTextBoxColumn UTN.Winform.AppAirBnB.Layers.UI.Procesos.frmFacturacion.NumTarjeta private
Definition at line 758 of file frmFacturacion.Designer.cs.
Precio
System.Windows.Forms.DataGridViewTextBoxColumn UTN.Winform.AppAirBnB.Layers.UI.Procesos.frmFacturacion.Precio private
Definition at line 756 of file frmFacturacion.Designer.cs.
rdbContado
System.Windows.Forms.RadioButton UTN.Winform.AppAirBnB.Layers.UI.Procesos.frmFacturacion.rdbContado private
Definition at line 742 of file frmFacturacion.Designer.cs.
rdbCredito
System.Windows.Forms.RadioButton UTN.Winform.AppAirBnB.Layers.UI.Procesos.frmFacturacion.rdbCredito private
Definition at line 732 of file frmFacturacion.Designer.cs.
splitContainer1
System.Windows.Forms.SplitContainer UTN.Winform.AppAirBnB.Layers.UI.Procesos.frmFacturacion.splitContainer1 private
Definition at line 721 of file frmFacturacion.Designer.cs.
sttBarraInferior
System.Windows.Forms.StatusStrip UTN.Winform.AppAirBnB.Layers.UI.Procesos.frmFacturacion.sttBarraInferior private
Definition at line 720 of file frmFacturacion.Designer.cs.
Subtotal
System.Windows.Forms.TextBox UTN.Winform.AppAirBnB.Layers.UI.Procesos.frmFacturacion.Subtotal private
Definition at line 771 of file frmFacturacion.Designer.cs.
tableLayoutPanel2
System.Windows.Forms.TableLayoutPanel UTN.Winform.AppAirBnB.Layers.UI.Procesos.frmFacturacion.tableLayoutPanel2 private
Definition at line 733 of file frmFacturacion.Designer.cs.
tableLayoutPanel3
System.Windows.Forms.TableLayoutPanel UTN.Winform.AppAirBnB.Layers.UI.Procesos.frmFacturacion.tableLayoutPanel3 private
Definition at line 743 of file frmFacturacion.Designer.cs.
tlpAgrupamiento
System.Windows.Forms.TableLayoutPanel UTN.Winform.AppAirBnB.Layers.UI.Procesos.frmFacturacion.tlpAgrupamiento private
Definition at line 723 of file frmFacturacion.Designer.cs.
toolStripBtnFacturar
System.Windows.Forms.ToolStripButton UTN.Winform.AppAirBnB.Layers.UI.Procesos.frmFacturacion.toolStripBtnFacturar private
Definition at line 773 of file frmFacturacion.Designer.cs.
toolStripBtnNuevo
System.Windows.Forms.ToolStripButton UTN.Winform.AppAirBnB.Layers.UI.Procesos.frmFacturacion.toolStripBtnNuevo private
Definition at line 718 of file frmFacturacion.Designer.cs.
toolStripBtnSalir
System.Windows.Forms.ToolStripButton UTN.Winform.AppAirBnB.Layers.UI.Procesos.frmFacturacion.toolStripBtnSalir private
Definition at line 719 of file frmFacturacion.Designer.cs.
tspBarraSuperior
System.Windows.Forms.ToolStrip UTN.Winform.AppAirBnB.Layers.UI.Procesos.frmFacturacion.tspBarraSuperior private
Definition at line 717 of file frmFacturacion.Designer.cs.
txtCantDias
System.Windows.Forms.TextBox UTN.Winform.AppAirBnB.Layers.UI.Procesos.frmFacturacion.txtCantDias private
Definition at line 770 of file frmFacturacion.Designer.cs.
txtIdHuesped
System.Windows.Forms.TextBox UTN.Winform.AppAirBnB.Layers.UI.Procesos.frmFacturacion.txtIdHuesped private
Definition at line 762 of file frmFacturacion.Designer.cs.
txtImpuesto
System.Windows.Forms.TextBox UTN.Winform.AppAirBnB.Layers.UI.Procesos.frmFacturacion.txtImpuesto private
Definition at line 738 of file frmFacturacion.Designer.cs.
txtNUMDetalle
System.Windows.Forms.TextBox UTN.Winform.AppAirBnB.Layers.UI.Procesos.frmFacturacion.txtNUMDetalle private
Definition at line 753 of file frmFacturacion.Designer.cs.
txtNumeroFactura
System.Windows.Forms.TextBox UTN.Winform.AppAirBnB.Layers.UI.Procesos.frmFacturacion.txtNumeroFactura private
Definition at line 731 of file frmFacturacion.Designer.cs.
txtNumeroTarjeta
System.Windows.Forms.TextBox UTN.Winform.AppAirBnB.Layers.UI.Procesos.frmFacturacion.txtNumeroTarjeta private
Definition at line 727 of file frmFacturacion.Designer.cs.
txtNumHabitacion
System.Windows.Forms.TextBox UTN.Winform.AppAirBnB.Layers.UI.Procesos.frmFacturacion.txtNumHabitacion private
Definition at line 764 of file frmFacturacion.Designer.cs.
txtPrecio
System.Windows.Forms.TextBox UTN.Winform.AppAirBnB.Layers.UI.Procesos.frmFacturacion.txtPrecio private
Definition at line 745 of file frmFacturacion.Designer.cs.
txtSubtotal
System.Windows.Forms.TextBox UTN.Winform.AppAirBnB.Layers.UI.Procesos.frmFacturacion.txtSubtotal private
Definition at line 737 of file frmFacturacion.Designer.cs.
txtTotal
System.Windows.Forms.TextBox UTN.Winform.AppAirBnB.Layers.UI.Procesos.frmFacturacion.txtTotal private
Definition at line 739 of file frmFacturacion.Designer.cs.
The documentation for this class was generated from the following files:
C:/Users/JorgeMario/Desktop/Proyecto Programado Cuatrimestre I 2018 v4/AppAirBnB/AppAirBnB/Layers/UI/Procesos/frmFacturacion.cs
C:/Users/JorgeMario/Desktop/Proyecto Programado Cuatrimestre I 2018 v4/AppAirBnB/AppAirBnB/Layers/UI/Procesos/frmFacturacion.Designer.cs