AppAirBnB: UTN.Winform.AppAirBnB.Layers.Interface.IBLLSysUserRolDTO Interface Reference
UTN.Winform.AppAirBnB.Layers.Interface.IBLLSysUserRolDTO Interface Reference
Public Member Functions
SysUser SaveSysUser (SysUser pSysUser)
SysUser GetSysUserById (double pId)
List< SysUser > GetSysUserByFilter (string pDescripcion)
List< SysUserRolDTO > GetAllSysUser ()
bool DeleteSysUser (string pId)
Detailed Description
Definition at line 11 of file IBLLSysUserRolDTO.cs.
Member Function Documentation
DeleteSysUser()
bool UTN.Winform.AppAirBnB.Layers.Interface.IBLLSysUserRolDTO.DeleteSysUser (string pId)
Implemented in UTN.Winform.AppAirBnB.Layers.BLL.BLLSysUserRolDTO.
Referenced by UTN.Winform.AppAirBnB.Layers.UI.Seguridad.frmSeguridad.toolStripButton2_Click().
GetAllSysUser()
List<SysUserRolDTO> UTN.Winform.AppAirBnB.Layers.Interface.IBLLSysUserRolDTO.GetAllSysUser ()
Implemented in UTN.Winform.AppAirBnB.Layers.BLL.BLLSysUserRolDTO.
Referenced by UTN.Winform.AppAirBnB.Layers.UI.Seguridad.frmSeguridad.CargarDatos().
GetSysUserByFilter()
List<SysUser> UTN.Winform.AppAirBnB.Layers.Interface.IBLLSysUserRolDTO.GetSysUserByFilter (string pDescripcion)
Implemented in UTN.Winform.AppAirBnB.Layers.BLL.BLLSysUserRolDTO.
Referenced by UTN.Winform.AppAirBnB.Layers.UI.frmLogin.btnAceptar_Click(), and UTN.Winform.AppAirBnB.Layers.UI.frmPrincipal.frmPrincipal_Load().
GetSysUserById()
SysUser UTN.Winform.AppAirBnB.Layers.Interface.IBLLSysUserRolDTO.GetSysUserById (double pId)
Implemented in UTN.Winform.AppAirBnB.Layers.BLL.BLLSysUserRolDTO.
SaveSysUser()
SysUser UTN.Winform.AppAirBnB.Layers.Interface.IBLLSysUserRolDTO.SaveSysUser (SysUser pSysUser)
Implemented in UTN.Winform.AppAirBnB.Layers.BLL.BLLSysUserRolDTO.
Referenced by UTN.Winform.AppAirBnB.Layers.UI.Seguridad.frmSeguridad.toolStripBtnSalvarUsuario_Click().
The documentation for this interface was generated from the following file:
C:/Users/JorgeMario/Desktop/Proyecto Programado Cuatrimestre I 2018 v4/AppAirBnB/AppAirBnB/Layers/Interface/IBLLSysUserRolDTO.cs