AppAirBnB: UTN.Winform.AppAirBnB.Layers.Interface.IBLLImpuesto Interface Reference
UTN.Winform.AppAirBnB.Layers.Interface.IBLLImpuesto Interface Reference
Public Member Functions
Impuesto GetImpuesto ()
Detailed Description
Definition at line 10 of file IBLLImpuesto.cs.
Member Function Documentation
GetImpuesto()
Impuesto UTN.Winform.AppAirBnB.Layers.Interface.IBLLImpuesto.GetImpuesto ()
Implemented in UTN.Winform.AppAirBnB.Layers.BLL.BLLImpuesto.
Referenced by UTN.Winform.AppAirBnB.Layers.UI.Procesos.frmFacturacion.btnAgregar_Click(), UTN.Winform.AppAirBnB.Layers.DAL.DALEncFactura.GetFactura(), and UTN.Winform.AppAirBnB.Layers.UI.Procesos.frmFacturacion.toolStripBtnFacturar_Click().
The documentation for this interface was generated from the following file:
C:/Users/JorgeMario/Desktop/Proyecto Programado Cuatrimestre I 2018 v4/AppAirBnB/AppAirBnB/Layers/Interface/IBLLImpuesto.cs