AppAirBnB: UTN.Winform.AppAirBnB.Layers.Interface.IBLLHuesped Interface Reference
UTN.Winform.AppAirBnB.Layers.Interface.IBLLHuesped Interface Reference
Public Member Functions
List< Huesped > GetHuespedByFilter (string pDescripcion)
Huesped GetHuespedById (double pIdHuesped)
List< Huesped > GetAllHuesped ()
Huesped SaveHuesped (Huesped oHuesped)
bool DeleteHuesped (double pId)
Detailed Description
Definition at line 10 of file IBLLHuesped.cs.
Member Function Documentation
DeleteHuesped()
bool UTN.Winform.AppAirBnB.Layers.Interface.IBLLHuesped.DeleteHuesped (double pId)
Implemented in UTN.Winform.AppAirBnB.Layers.BLL.BLLHuesped.
Referenced by UTN.Winform.AppAirBnB.Layers.UI.Mantenimientos.frmMantenimientoHuesped.toolStripBtnBorrar_Click().
GetAllHuesped()
List<Huesped> UTN.Winform.AppAirBnB.Layers.Interface.IBLLHuesped.GetAllHuesped ()
Implemented in UTN.Winform.AppAirBnB.Layers.BLL.BLLHuesped.
Referenced by UTN.Winform.AppAirBnB.Layers.UI.Mantenimientos.frmMantenimientoHuesped.CargarDatos(), and UTN.Winform.AppAirBnB.Layers.UI.Filtros.frmFiltroHuesped.toolStripBtnBuscar_Click().
GetHuespedByFilter()
List<Huesped> UTN.Winform.AppAirBnB.Layers.Interface.IBLLHuesped.GetHuespedByFilter (string pDescripcion)
Implemented in UTN.Winform.AppAirBnB.Layers.BLL.BLLHuesped.
GetHuespedById()
Huesped UTN.Winform.AppAirBnB.Layers.Interface.IBLLHuesped.GetHuespedById (double pIdHuesped)
Implemented in UTN.Winform.AppAirBnB.Layers.BLL.BLLHuesped.
Referenced by UTN.Winform.AppAirBnB.Layers.UI.Procesos.frmReservacion.toolStripBtnReservar_Click().
SaveHuesped()
Huesped UTN.Winform.AppAirBnB.Layers.Interface.IBLLHuesped.SaveHuesped (Huesped oHuesped)
Implemented in UTN.Winform.AppAirBnB.Layers.BLL.BLLHuesped.
Referenced by UTN.Winform.AppAirBnB.Layers.UI.Mantenimientos.frmMantenimientoHuesped.btnAceptar_Click().
The documentation for this interface was generated from the following file:
C:/Users/JorgeMario/Desktop/Proyecto Programado Cuatrimestre I 2018 v4/AppAirBnB/AppAirBnB/Layers/Interface/IBLLHuesped.cs