AppAirBnB: UTN.Winform.AppAirBnB.Layers.Interface.IBLLEncFactura Interface Reference
UTN.Winform.AppAirBnB.Layers.Interface.IBLLEncFactura Interface Reference
Public Member Functions
EncFactura SaveFactura (EncFactura pFactura)
int GetNextNumeroFactura ()
int GetCurrentNumeroFactura ()
EncFactura GetFactura (double pNumeroFactura)
Detailed Description
Definition at line 10 of file IBLLEncFactura.cs.
Member Function Documentation
GetCurrentNumeroFactura()
int UTN.Winform.AppAirBnB.Layers.Interface.IBLLEncFactura.GetCurrentNumeroFactura ()
Implemented in UTN.Winform.AppAirBnB.Layers.BLL.BLLEncFactura.
Referenced by UTN.Winform.AppAirBnB.Layers.UI.Procesos.frmFacturacion.btnAgregar_Click(), UTN.Winform.AppAirBnB.Layers.UI.Procesos.frmFacturacion.CargarDatos(), and UTN.Winform.AppAirBnB.Layers.UI.Procesos.frmFacturacion.toolStripBtnFacturar_Click().
GetFactura()
EncFactura UTN.Winform.AppAirBnB.Layers.Interface.IBLLEncFactura.GetFactura (double pNumeroFactura)
Implemented in UTN.Winform.AppAirBnB.Layers.BLL.BLLEncFactura.
Referenced by UTN.Winform.AppAirBnB.Layers.UI.Procesos.frmFacturacion.btnAgregar_Click(), and UTN.Winform.AppAirBnB.Layers.UI.Procesos.frmFacturacion.toolStripBtnFacturar_Click().
GetNextNumeroFactura()
int UTN.Winform.AppAirBnB.Layers.Interface.IBLLEncFactura.GetNextNumeroFactura ()
Implemented in UTN.Winform.AppAirBnB.Layers.BLL.BLLEncFactura.
Referenced by UTN.Winform.AppAirBnB.Layers.UI.Procesos.frmFacturacion.toolStripBtnNuevo_Click().
SaveFactura()
EncFactura UTN.Winform.AppAirBnB.Layers.Interface.IBLLEncFactura.SaveFactura (EncFactura pFactura)
Implemented in UTN.Winform.AppAirBnB.Layers.BLL.BLLEncFactura.
Referenced by UTN.Winform.AppAirBnB.Layers.UI.Procesos.frmFacturacion.toolStripBtnFacturar_Click().
The documentation for this interface was generated from the following file:
C:/Users/JorgeMario/Desktop/Proyecto Programado Cuatrimestre I 2018 v4/AppAirBnB/AppAirBnB/Layers/Interface/IBLLEncFactura.cs