AppAirBnB: UTN.Winform.AppAirBnB.Layers.Interface.IBLLReservacion Interface Reference
UTN.Winform.AppAirBnB.Layers.Interface.IBLLReservacion Interface Reference
Public Member Functions
int GetNextNumeroReserva ()
int GetCurrentNumeroReserva ()
void SaveReserva (Reservacion pReserva)
List< Reservacion > GetAllReservacion ()
Reservacion GetReserva (double pNumeroReserva)
bool DeleteReserva (double pId)
Detailed Description
Definition at line 10 of file IBLLReservacion.cs.
Member Function Documentation
DeleteReserva()
bool UTN.Winform.AppAirBnB.Layers.Interface.IBLLReservacion.DeleteReserva (double pId)
Implemented in UTN.Winform.AppAirBnB.Layers.BLL.BLLReservacion.
Referenced by UTN.Winform.AppAirBnB.Layers.UI.Procesos.frmReservacion.toolStripButton1_Click().
GetAllReservacion()
List<Reservacion> UTN.Winform.AppAirBnB.Layers.Interface.IBLLReservacion.GetAllReservacion ()
Implemented in UTN.Winform.AppAirBnB.Layers.BLL.BLLReservacion.
Referenced by UTN.Winform.AppAirBnB.Layers.UI.Procesos.frmReservacion.CargarDatos(), and UTN.Winform.AppAirBnB.Layers.UI.Filtros.frmFiltroReserva.toolStripBtnBuscar_Click().
GetCurrentNumeroReserva()
int UTN.Winform.AppAirBnB.Layers.Interface.IBLLReservacion.GetCurrentNumeroReserva ()
Implemented in UTN.Winform.AppAirBnB.Layers.BLL.BLLReservacion.
Referenced by UTN.Winform.AppAirBnB.Layers.UI.Procesos.frmReservacion.frmReservacion_Load().
GetNextNumeroReserva()
int UTN.Winform.AppAirBnB.Layers.Interface.IBLLReservacion.GetNextNumeroReserva ()
Implemented in UTN.Winform.AppAirBnB.Layers.BLL.BLLReservacion.
Referenced by UTN.Winform.AppAirBnB.Layers.UI.Procesos.frmReservacion.toolStripBtnNuevo_Click().
GetReserva()
Reservacion UTN.Winform.AppAirBnB.Layers.Interface.IBLLReservacion.GetReserva (double pNumeroReserva)
Implemented in UTN.Winform.AppAirBnB.Layers.BLL.BLLReservacion.
Referenced by UTN.Winform.AppAirBnB.Layers.UI.Procesos.frmFacturacion.btnAgregar_Click(), and UTN.Winform.AppAirBnB.Layers.UI.Procesos.frmFacturacion.toolStripBtnFacturar_Click().
SaveReserva()
void UTN.Winform.AppAirBnB.Layers.Interface.IBLLReservacion.SaveReserva (Reservacion pReserva)
Implemented in UTN.Winform.AppAirBnB.Layers.BLL.BLLReservacion.
The documentation for this interface was generated from the following file:
C:/Users/JorgeMario/Desktop/Proyecto Programado Cuatrimestre I 2018 v4/AppAirBnB/AppAirBnB/Layers/Interface/IBLLReservacion.cs