AppAirBnB: UTN.Winform.AppAirBnB.Layers.Interface.IDALSysUserRolDTO Interface Reference
UTN.Winform.AppAirBnB.Layers.Interface.IDALSysUserRolDTO Interface Reference
Public Member Functions
SysUser SaveSysUser (SysUser pSysUser)
SysUser GetSysUserById (double pId)
List< SysUser > GetSysUserByFilter (string pDescripcion)
List< SysUserRolDTO > GetAllSysUser ()
bool DeleteSysUser (string pId)
SysUser UpdateSysUser (SysUser pSysUser)
Detailed Description
Definition at line 11 of file IDALSysUserRolDTO.cs.
Member Function Documentation
DeleteSysUser()
bool UTN.Winform.AppAirBnB.Layers.Interface.IDALSysUserRolDTO.DeleteSysUser (string pId)
Implemented in UTN.Winform.AppAirBnB.Layers.DAL.DALSysUserRolDTO.
Referenced by UTN.Winform.AppAirBnB.Layers.BLL.BLLSysUserRolDTO.DeleteSysUser().
GetAllSysUser()
List<SysUserRolDTO> UTN.Winform.AppAirBnB.Layers.Interface.IDALSysUserRolDTO.GetAllSysUser ()
Implemented in UTN.Winform.AppAirBnB.Layers.DAL.DALSysUserRolDTO.
Referenced by UTN.Winform.AppAirBnB.Layers.BLL.BLLSysUserRolDTO.GetAllSysUser().
GetSysUserByFilter()
List<SysUser> UTN.Winform.AppAirBnB.Layers.Interface.IDALSysUserRolDTO.GetSysUserByFilter (string pDescripcion)
Implemented in UTN.Winform.AppAirBnB.Layers.DAL.DALSysUserRolDTO.
Referenced by UTN.Winform.AppAirBnB.Layers.BLL.BLLSysUserRolDTO.GetSysUserByFilter().
GetSysUserById()
SysUser UTN.Winform.AppAirBnB.Layers.Interface.IDALSysUserRolDTO.GetSysUserById (double pId)
Implemented in UTN.Winform.AppAirBnB.Layers.DAL.DALSysUserRolDTO.
Referenced by UTN.Winform.AppAirBnB.Layers.BLL.BLLSysUserRolDTO.GetSysUserById(), and UTN.Winform.AppAirBnB.Layers.BLL.BLLSysUserRolDTO.SaveSysUser().
SaveSysUser()
SysUser UTN.Winform.AppAirBnB.Layers.Interface.IDALSysUserRolDTO.SaveSysUser (SysUser pSysUser)
Implemented in UTN.Winform.AppAirBnB.Layers.DAL.DALSysUserRolDTO.
Referenced by UTN.Winform.AppAirBnB.Layers.BLL.BLLSysUserRolDTO.SaveSysUser().
UpdateSysUser()
SysUser UTN.Winform.AppAirBnB.Layers.Interface.IDALSysUserRolDTO.UpdateSysUser (SysUser pSysUser)
Implemented in UTN.Winform.AppAirBnB.Layers.DAL.DALSysUserRolDTO.
Referenced by UTN.Winform.AppAirBnB.Layers.BLL.BLLSysUserRolDTO.SaveSysUser().
The documentation for this interface was generated from the following file:
C:/Users/JorgeMario/Desktop/Proyecto Programado Cuatrimestre I 2018 v4/AppAirBnB/AppAirBnB/Layers/Interface/IDALSysUserRolDTO.cs