AppAirBnB: UTN.Winform.AppAirBnB.Layers.Interface.IDALHabitacion Interface Reference
UTN.Winform.AppAirBnB.Layers.Interface.IDALHabitacion Interface Reference
Public Member Functions
List< HabitacionDTO > GetAllHabitacion ()
Habitacion GetHabitacionById (double pId)
Habitacion SaveHabitacion (Habitacion pHabitacion)
Habitacion UpdateHabitacion (Habitacion pHabitacion)
bool DeleteHabitacion (double pId)
Detailed Description
Definition at line 11 of file IDALHabitacion.cs.
Member Function Documentation
DeleteHabitacion()
bool UTN.Winform.AppAirBnB.Layers.Interface.IDALHabitacion.DeleteHabitacion (double pId)
Implemented in UTN.Winform.AppAirBnB.Layers.DAL.DALHabitacion.
Referenced by UTN.Winform.AppAirBnB.Layers.BLL.BLLHabitacion.DeleteHabitacion().
GetAllHabitacion()
List<HabitacionDTO> UTN.Winform.AppAirBnB.Layers.Interface.IDALHabitacion.GetAllHabitacion ()
Implemented in UTN.Winform.AppAirBnB.Layers.DAL.DALHabitacion.
Referenced by UTN.Winform.AppAirBnB.Layers.BLL.BLLHabitacion.GetAllHabitacion().
GetHabitacionById()
Habitacion UTN.Winform.AppAirBnB.Layers.Interface.IDALHabitacion.GetHabitacionById (double pId)
Implemented in UTN.Winform.AppAirBnB.Layers.DAL.DALHabitacion.
Referenced by UTN.Winform.AppAirBnB.Layers.DAL.DALReservacion.GetAllReservacion(), UTN.Winform.AppAirBnB.Layers.BLL.BLLHabitacion.GetHabitacionById(), UTN.Winform.AppAirBnB.Layers.DAL.DALReservacion.GetReserva(), and UTN.Winform.AppAirBnB.Layers.BLL.BLLHabitacion.SaveHabitacion().
SaveHabitacion()
Habitacion UTN.Winform.AppAirBnB.Layers.Interface.IDALHabitacion.SaveHabitacion (Habitacion pHabitacion)
Implemented in UTN.Winform.AppAirBnB.Layers.DAL.DALHabitacion.
Referenced by UTN.Winform.AppAirBnB.Layers.BLL.BLLHabitacion.SaveHabitacion().
UpdateHabitacion()
Habitacion UTN.Winform.AppAirBnB.Layers.Interface.IDALHabitacion.UpdateHabitacion (Habitacion pHabitacion)
Implemented in UTN.Winform.AppAirBnB.Layers.DAL.DALHabitacion.
Referenced by UTN.Winform.AppAirBnB.Layers.BLL.BLLHabitacion.SaveHabitacion().
The documentation for this interface was generated from the following file:
C:/Users/JorgeMario/Desktop/Proyecto Programado Cuatrimestre I 2018 v4/AppAirBnB/AppAirBnB/Layers/Interface/IDALHabitacion.cs