AppAirBnB: UTN.Winform.AppAirBnB.Layers.Interface.IDALReservacion Interface Reference
UTN.Winform.AppAirBnB.Layers.Interface.IDALReservacion Interface Reference
Public Member Functions
int GetNextNumeroReserva ()
int GetCurrentNumeroReserva ()
void SaveReserva (Reservacion pReserva)
List< Reservacion > GetAllReservacion ()
Reservacion GetReserva (double pNumeroReserva)
bool DeleteReserva (double pId)
Detailed Description
Definition at line 10 of file IDALReservacion.cs.
Member Function Documentation
DeleteReserva()
bool UTN.Winform.AppAirBnB.Layers.Interface.IDALReservacion.DeleteReserva (double pId)
Implemented in UTN.Winform.AppAirBnB.Layers.DAL.DALReservacion.
Referenced by UTN.Winform.AppAirBnB.Layers.BLL.BLLReservacion.DeleteReserva().
GetAllReservacion()
List<Reservacion> UTN.Winform.AppAirBnB.Layers.Interface.IDALReservacion.GetAllReservacion ()
Implemented in UTN.Winform.AppAirBnB.Layers.DAL.DALReservacion.
Referenced by UTN.Winform.AppAirBnB.Layers.BLL.BLLReservacion.GetAllReservacion().
GetCurrentNumeroReserva()
int UTN.Winform.AppAirBnB.Layers.Interface.IDALReservacion.GetCurrentNumeroReserva ()
Implemented in UTN.Winform.AppAirBnB.Layers.DAL.DALReservacion.
Referenced by UTN.Winform.AppAirBnB.Layers.BLL.BLLReservacion.GetCurrentNumeroReserva().
GetNextNumeroReserva()
int UTN.Winform.AppAirBnB.Layers.Interface.IDALReservacion.GetNextNumeroReserva ()
Implemented in UTN.Winform.AppAirBnB.Layers.DAL.DALReservacion.
Referenced by UTN.Winform.AppAirBnB.Layers.BLL.BLLReservacion.GetNextNumeroReserva().
GetReserva()
Reservacion UTN.Winform.AppAirBnB.Layers.Interface.IDALReservacion.GetReserva (double pNumeroReserva)
Implemented in UTN.Winform.AppAirBnB.Layers.DAL.DALReservacion.
Referenced by UTN.Winform.AppAirBnB.Layers.DAL.DALEncFactura.GetFactura(), and UTN.Winform.AppAirBnB.Layers.BLL.BLLReservacion.GetReserva().
SaveReserva()
void UTN.Winform.AppAirBnB.Layers.Interface.IDALReservacion.SaveReserva (Reservacion pReserva)
Implemented in UTN.Winform.AppAirBnB.Layers.DAL.DALReservacion.
Referenced by UTN.Winform.AppAirBnB.Layers.BLL.BLLReservacion.SaveReserva().
The documentation for this interface was generated from the following file:
C:/Users/JorgeMario/Desktop/Proyecto Programado Cuatrimestre I 2018 v4/AppAirBnB/AppAirBnB/Layers/Interface/IDALReservacion.cs