AppAirBnB: UTN.Winform.AppAirBnB.Layers.Interface.IBLLHabitacion Interface Reference
UTN.Winform.AppAirBnB.Layers.Interface.IBLLHabitacion Interface Reference
Public Member Functions
List< HabitacionDTO > GetAllHabitacion ()
Habitacion SaveHabitacion (Habitacion pHabitacion)
bool DeleteHabitacion (double pId)
Habitacion GetHabitacionById (double pId)
Habitacion UpdateHabitacion (Habitacion pHabitacion)
Detailed Description
Definition at line 11 of file IBLLHabitacion.cs.
Member Function Documentation
DeleteHabitacion()
bool UTN.Winform.AppAirBnB.Layers.Interface.IBLLHabitacion.DeleteHabitacion (double pId)
Implemented in UTN.Winform.AppAirBnB.Layers.BLL.BLLHabitacion.
Referenced by UTN.Winform.AppAirBnB.Layers.UI.Mantenimientos.frmMantenimientoHabitacion.toolStripBtnBorrar_Click().
GetAllHabitacion()
List<HabitacionDTO> UTN.Winform.AppAirBnB.Layers.Interface.IBLLHabitacion.GetAllHabitacion ()
Implemented in UTN.Winform.AppAirBnB.Layers.BLL.BLLHabitacion.
Referenced by UTN.Winform.AppAirBnB.Layers.UI.Mantenimientos.frmMantenimientoHabitacion.CargarDatos(), and UTN.Winform.AppAirBnB.Layers.UI.Filtros.frmFiltroHabi.toolStripBtnBuscar_Click().
GetHabitacionById()
Habitacion UTN.Winform.AppAirBnB.Layers.Interface.IBLLHabitacion.GetHabitacionById (double pId)
Implemented in UTN.Winform.AppAirBnB.Layers.BLL.BLLHabitacion.
Referenced by UTN.Winform.AppAirBnB.Layers.UI.Procesos.frmFacturacion.EstadoHabitaciones(), and UTN.Winform.AppAirBnB.Layers.UI.Procesos.frmReservacion.toolStripBtnReservar_Click().
SaveHabitacion()
Habitacion UTN.Winform.AppAirBnB.Layers.Interface.IBLLHabitacion.SaveHabitacion (Habitacion pHabitacion)
Implemented in UTN.Winform.AppAirBnB.Layers.BLL.BLLHabitacion.
Referenced by UTN.Winform.AppAirBnB.Layers.UI.Mantenimientos.frmMantenimientoHabitacion.btnAceptar_Click(), and UTN.Winform.AppAirBnB.Layers.UI.Procesos.frmFacturacion.EstadoHabitaciones().
UpdateHabitacion()
Habitacion UTN.Winform.AppAirBnB.Layers.Interface.IBLLHabitacion.UpdateHabitacion (Habitacion pHabitacion)
Implemented in UTN.Winform.AppAirBnB.Layers.BLL.BLLHabitacion.
The documentation for this interface was generated from the following file:
C:/Users/JorgeMario/Desktop/Proyecto Programado Cuatrimestre I 2018 v4/AppAirBnB/AppAirBnB/Layers/Interface/IBLLHabitacion.cs