AppAirBnB: UTN.Winform.AppAirBnB.Layers.Interface.IDALTarjeta Interface Reference
UTN.Winform.AppAirBnB.Layers.Interface.IDALTarjeta Interface Reference
Public Member Functions
List< Tarjeta > GetAllTarjeta ()
Tarjeta GetTarjetaById (double pIdTarjeta)
Detailed Description
Definition at line 10 of file IDALTarjeta.cs.
Member Function Documentation
GetAllTarjeta()
List<Tarjeta> UTN.Winform.AppAirBnB.Layers.Interface.IDALTarjeta.GetAllTarjeta ()
Implemented in UTN.Winform.AppAirBnB.Layers.DAL.DALTarjeta.
Referenced by UTN.Winform.AppAirBnB.Layers.BLL.BLLTarjeta.GetAllTarjeta().
GetTarjetaById()
Tarjeta UTN.Winform.AppAirBnB.Layers.Interface.IDALTarjeta.GetTarjetaById (double pIdTarjeta)
Implemented in UTN.Winform.AppAirBnB.Layers.DAL.DALTarjeta.
Referenced by UTN.Winform.AppAirBnB.Layers.DAL.DALEncFactura.GetFactura(), and UTN.Winform.AppAirBnB.Layers.BLL.BLLTarjeta.GetTarjetaById().
The documentation for this interface was generated from the following file:
C:/Users/JorgeMario/Desktop/Proyecto Programado Cuatrimestre I 2018 v4/AppAirBnB/AppAirBnB/Layers/Interface/IDALTarjeta.cs