AppAirBnB: UTN.Winform.AppAirBnB.Layers.Interface.IDALHuesped Interface Reference
UTN.Winform.AppAirBnB.Layers.Interface.IDALHuesped Interface Reference
Public Member Functions
List< Huesped > GetHuespedByFilter (string pDescripcion)
Huesped GetHuespedById (double pId)
List< Huesped > GetAllHuesped ()
Huesped SaveHuesped (Huesped oHuesped)
Huesped UpdateHuesped (Huesped pHuesped)
bool DeleteHuesped (double pId)
Detailed Description
Definition at line 10 of file IDALHuesped.cs.
Member Function Documentation
DeleteHuesped()
bool UTN.Winform.AppAirBnB.Layers.Interface.IDALHuesped.DeleteHuesped (double pId)
Implemented in UTN.Winform.AppAirBnB.Layers.DAL.DALHuesped.
Referenced by UTN.Winform.AppAirBnB.Layers.BLL.BLLHuesped.DeleteHuesped().
GetAllHuesped()
List<Huesped> UTN.Winform.AppAirBnB.Layers.Interface.IDALHuesped.GetAllHuesped ()
Implemented in UTN.Winform.AppAirBnB.Layers.DAL.DALHuesped.
Referenced by UTN.Winform.AppAirBnB.Layers.BLL.BLLHuesped.GetAllHuesped().
GetHuespedByFilter()
List<Huesped> UTN.Winform.AppAirBnB.Layers.Interface.IDALHuesped.GetHuespedByFilter (string pDescripcion)
Implemented in UTN.Winform.AppAirBnB.Layers.DAL.DALHuesped.
Referenced by UTN.Winform.AppAirBnB.Layers.BLL.BLLHuesped.GetHuespedByFilter().
GetHuespedById()
Huesped UTN.Winform.AppAirBnB.Layers.Interface.IDALHuesped.GetHuespedById (double pId)
Implemented in UTN.Winform.AppAirBnB.Layers.DAL.DALHuesped.
Referenced by UTN.Winform.AppAirBnB.Layers.DAL.DALReservacion.GetAllReservacion(), UTN.Winform.AppAirBnB.Layers.BLL.BLLHuesped.GetHuespedById(), UTN.Winform.AppAirBnB.Layers.DAL.DALReservacion.GetReserva(), and UTN.Winform.AppAirBnB.Layers.BLL.BLLHuesped.SaveHuesped().
SaveHuesped()
Huesped UTN.Winform.AppAirBnB.Layers.Interface.IDALHuesped.SaveHuesped (Huesped oHuesped)
Implemented in UTN.Winform.AppAirBnB.Layers.DAL.DALHuesped.
Referenced by UTN.Winform.AppAirBnB.Layers.BLL.BLLHuesped.SaveHuesped().
UpdateHuesped()
Huesped UTN.Winform.AppAirBnB.Layers.Interface.IDALHuesped.UpdateHuesped (Huesped pHuesped)
Implemented in UTN.Winform.AppAirBnB.Layers.DAL.DALHuesped.
Referenced by UTN.Winform.AppAirBnB.Layers.BLL.BLLHuesped.SaveHuesped().
The documentation for this interface was generated from the following file:
C:/Users/JorgeMario/Desktop/Proyecto Programado Cuatrimestre I 2018 v4/AppAirBnB/AppAirBnB/Layers/Interface/IDALHuesped.cs