appExamen1Sismos: UTN.Winform.Examen1.Sismos.Interfaces.IGestor Interface Reference
UTN.Winform.Examen1.Sismos.Interfaces.IGestor Interface Reference
Public Member Functions
void AgregarSismo (Sismo pSismo)
void AsignarInstitucion (IInstitucion PInstitucion)
List< Respuesta > ObtenerCalculos ()
string ObtenerXML ()
double TotalMagnitudes ()
Detailed Description
Definition at line 10 of file IGestor.cs.
Member Function Documentation
AgregarSismo()
void UTN.Winform.Examen1.Sismos.Interfaces.IGestor.AgregarSismo (Sismo pSismo)
Implemented in UTN.Winform.Examen1.Sismos.Gestores.Gestor.
Referenced by UTN.Winform.Examen1.Sismos.UI.frmPrincipal.CargarArchivoJSON(), and UTN.Winform.Examen1.Sismos.UI.frmPrincipal.tspbtnEjecutar_Click().
AsignarInstitucion()
void UTN.Winform.Examen1.Sismos.Interfaces.IGestor.AsignarInstitucion (IInstitucion PInstitucion)
Implemented in UTN.Winform.Examen1.Sismos.Gestores.Gestor.
Referenced by UTN.Winform.Examen1.Sismos.UI.frmPrincipal.tspbtnEjecutar_Click().
ObtenerCalculos()
List<Respuesta> UTN.Winform.Examen1.Sismos.Interfaces.IGestor.ObtenerCalculos ()
Implemented in UTN.Winform.Examen1.Sismos.Gestores.Gestor.
Referenced by UTN.Winform.Examen1.Sismos.UI.frmPrincipal.tspbtnEjecutar_Click().
ObtenerXML()
string UTN.Winform.Examen1.Sismos.Interfaces.IGestor.ObtenerXML ()
Implemented in UTN.Winform.Examen1.Sismos.Gestores.Gestor.
Referenced by UTN.Winform.Examen1.Sismos.UI.frmPrincipal.tspbtnEjecutar_Click().
TotalMagnitudes()
double UTN.Winform.Examen1.Sismos.Interfaces.IGestor.TotalMagnitudes ()
Implemented in UTN.Winform.Examen1.Sismos.Gestores.Gestor.
Referenced by UTN.Winform.Examen1.Sismos.UI.frmPrincipal.tspbtnEjecutar_Click().
The documentation for this interface was generated from the following file:
C:/Users/JorgeMario/Documents/Visual Studio 2015/Projects/appExamen1Sismo/appExamen1Sismo/Interfaces/IGestor.cs