AppAirBnB: UTN.Winform.AppAirBnB.Layers.Interface.IDALSeguridad Interface Reference
UTN.Winform.AppAirBnB.Layers.Interface.IDALSeguridad Interface Reference
Public Member Functions
void CreateUser (string pUuario, string pContrasena, string pBaseDatos)
IEnumerable< string > GetDataBases ()
IEnumerable< string > GetLoginsXDataBase (string pBaseDatos)
IEnumerable< string > GetLogins ()
Detailed Description
Definition at line 9 of file IDALSeguridad.cs.
Member Function Documentation
CreateUser()
void UTN.Winform.AppAirBnB.Layers.Interface.IDALSeguridad.CreateUser (string pUuario, string pContrasena, string pBaseDatos)
Implemented in UTN.Winform.AppAirBnB.Layers.DAL.DALSeguridad.
Referenced by UTN.Winform.AppAirBnB.Layers.BLL.BLLSeguridad.CreateUser().
GetDataBases()
IEnumerable<string> UTN.Winform.AppAirBnB.Layers.Interface.IDALSeguridad.GetDataBases ()
Implemented in UTN.Winform.AppAirBnB.Layers.DAL.DALSeguridad.
Referenced by UTN.Winform.AppAirBnB.Layers.BLL.BLLSeguridad.GetDataBases().
GetLogins()
IEnumerable<string> UTN.Winform.AppAirBnB.Layers.Interface.IDALSeguridad.GetLogins ()
Implemented in UTN.Winform.AppAirBnB.Layers.DAL.DALSeguridad.
Referenced by UTN.Winform.AppAirBnB.Layers.BLL.BLLSeguridad.GetLogins().
GetLoginsXDataBase()
IEnumerable<string> UTN.Winform.AppAirBnB.Layers.Interface.IDALSeguridad.GetLoginsXDataBase (string pBaseDatos)
Implemented in UTN.Winform.AppAirBnB.Layers.DAL.DALSeguridad.
Referenced by UTN.Winform.AppAirBnB.Layers.BLL.BLLSeguridad.GetLoginsXDataBase().
The documentation for this interface was generated from the following file:
C:/Users/JorgeMario/Desktop/Proyecto Programado Cuatrimestre I 2018 v4/AppAirBnB/AppAirBnB/Layers/Interface/IDALSeguridad.cs