AppAirBnB: UTN.Winform.AppAirBnB.Layers.Interface.IDALEncFactura Interface Reference
UTN.Winform.AppAirBnB.Layers.Interface.IDALEncFactura Interface Reference
Public Member Functions
EncFactura SaveFactura (EncFactura pFactura)
int GetNextNumeroFactura ()
int GetCurrentNumeroFactura ()
EncFactura GetFactura (double pNumeroFactura)
Detailed Description
Definition at line 10 of file IDALEncFactura.cs.
Member Function Documentation
GetCurrentNumeroFactura()
int UTN.Winform.AppAirBnB.Layers.Interface.IDALEncFactura.GetCurrentNumeroFactura ()
Implemented in UTN.Winform.AppAirBnB.Layers.DAL.DALEncFactura.
Referenced by UTN.Winform.AppAirBnB.Layers.BLL.BLLEncFactura.GetCurrentNumeroFactura().
GetFactura()
EncFactura UTN.Winform.AppAirBnB.Layers.Interface.IDALEncFactura.GetFactura (double pNumeroFactura)
Implemented in UTN.Winform.AppAirBnB.Layers.DAL.DALEncFactura.
Referenced by UTN.Winform.AppAirBnB.Layers.BLL.BLLEncFactura.GetFactura(), and UTN.Winform.AppAirBnB.Layers.DAL.DALEncFactura.GetFactura().
GetNextNumeroFactura()
int UTN.Winform.AppAirBnB.Layers.Interface.IDALEncFactura.GetNextNumeroFactura ()
Implemented in UTN.Winform.AppAirBnB.Layers.DAL.DALEncFactura.
Referenced by UTN.Winform.AppAirBnB.Layers.BLL.BLLEncFactura.GetNextNumeroFactura().
SaveFactura()
EncFactura UTN.Winform.AppAirBnB.Layers.Interface.IDALEncFactura.SaveFactura (EncFactura pFactura)
Implemented in UTN.Winform.AppAirBnB.Layers.DAL.DALEncFactura.
Referenced by UTN.Winform.AppAirBnB.Layers.BLL.BLLEncFactura.SaveFactura().
The documentation for this interface was generated from the following file:
C:/Users/JorgeMario/Desktop/Proyecto Programado Cuatrimestre I 2018 v4/AppAirBnB/AppAirBnB/Layers/Interface/IDALEncFactura.cs