AppAirBnB: UTN.Winform.AppAirBnB.Layers.Persistencia.IDataBase Interface Reference
UTN.Winform.AppAirBnB.Layers.Persistencia.IDataBase Interface Reference
Public Member Functions
double ExecuteNonQuery (IDbCommand pCommand)
int ExecuteNonQuery (ref IDbCommand pCommand, IsolationLevel pIsolationLevel)
int ExecuteNonQuery (List< IDbCommand > pCommands, IsolationLevel pIsolationLevel)
double ExecuteNonQuery (IDbCommand pCommand, IsolationLevel pIsolationLevel)
IDataReader ExecuteReader (IDbCommand pCommand)
DataSet ExecuteReader (IDbCommand pCommand, string pTabla)
double ExecuteScalar (IDbCommand pCommand)
Properties
IDbConnection _Conexion [get, set]
Detailed Description
Definition at line 10 of file IDataBase.cs.
Member Function Documentation
ExecuteNonQuery() [1/4]
double UTN.Winform.AppAirBnB.Layers.Persistencia.IDataBase.ExecuteNonQuery (IDbCommand pCommand)
Implemented in UTN.Winform.AppAirBnB.Layers.Persistencia.DataBase.
Referenced by UTN.Winform.AppAirBnB.Layers.DAL.DALSeguridad.CreateUser(), UTN.Winform.AppAirBnB.Layers.DAL.DALHabitacion.DeleteHabitacion(), UTN.Winform.AppAirBnB.Layers.DAL.DALHuesped.DeleteHuesped(), UTN.Winform.AppAirBnB.Layers.DAL.DALReservacion.DeleteReserva(), UTN.Winform.AppAirBnB.Layers.DAL.DALSysUserRolDTO.DeleteSysUser(), UTN.Winform.AppAirBnB.Layers.DAL.DALEncFactura.SaveFactura(), UTN.Winform.AppAirBnB.Layers.DAL.DALHabitacion.SaveHabitacion(), UTN.Winform.AppAirBnB.Layers.DAL.DALHuesped.SaveHuesped(), UTN.Winform.AppAirBnB.Layers.DAL.DALReservacion.SaveReserva(), UTN.Winform.AppAirBnB.Layers.DAL.DALSysUserRolDTO.SaveSysUser(), UTN.Winform.AppAirBnB.Layers.DAL.DALHabitacion.UpdateHabitacion(), UTN.Winform.AppAirBnB.Layers.DAL.DALHuesped.UpdateHuesped(), and UTN.Winform.AppAirBnB.Layers.DAL.DALSysUserRolDTO.UpdateSysUser().
ExecuteNonQuery() [2/4]
int UTN.Winform.AppAirBnB.Layers.Persistencia.IDataBase.ExecuteNonQuery (ref IDbCommand pCommand, IsolationLevel pIsolationLevel)
Implemented in UTN.Winform.AppAirBnB.Layers.Persistencia.DataBase.
ExecuteNonQuery() [3/4]
int UTN.Winform.AppAirBnB.Layers.Persistencia.IDataBase.ExecuteNonQuery (List< IDbCommand > pCommands, IsolationLevel pIsolationLevel)
Implemented in UTN.Winform.AppAirBnB.Layers.Persistencia.DataBase.
ExecuteNonQuery() [4/4]
double UTN.Winform.AppAirBnB.Layers.Persistencia.IDataBase.ExecuteNonQuery (IDbCommand pCommand, IsolationLevel pIsolationLevel)
Implemented in UTN.Winform.AppAirBnB.Layers.Persistencia.DataBase.
ExecuteReader() [1/2]
IDataReader UTN.Winform.AppAirBnB.Layers.Persistencia.IDataBase.ExecuteReader (IDbCommand pCommand)
Implemented in UTN.Winform.AppAirBnB.Layers.Persistencia.DataBase.
Referenced by UTN.Winform.AppAirBnB.Layers.DAL.DALHabitacion.GetAllHabitacion(), UTN.Winform.AppAirBnB.Layers.DAL.DALHuesped.GetAllHuesped(), UTN.Winform.AppAirBnB.Layers.DAL.DALPais.GetAllPais(), UTN.Winform.AppAirBnB.Layers.DAL.DALReservacion.GetAllReservacion(), UTN.Winform.AppAirBnB.Layers.DAL.DALSysUserRolDTO.GetAllSysUser(), UTN.Winform.AppAirBnB.Layers.DAL.DALTarjeta.GetAllTarjeta(), UTN.Winform.AppAirBnB.Layers.DAL.DALEncFactura.GetCurrentNumeroFactura(), UTN.Winform.AppAirBnB.Layers.DAL.DALReservacion.GetCurrentNumeroReserva(), UTN.Winform.AppAirBnB.Layers.DAL.DALSeguridad.GetDataBases(), UTN.Winform.AppAirBnB.Layers.DAL.DALEncFactura.GetFactura(), UTN.Winform.AppAirBnB.Layers.DAL.DALHabitacion.GetHabitacionById(), UTN.Winform.AppAirBnB.Layers.DAL.DALHuesped.GetHuespedByFilter(), UTN.Winform.AppAirBnB.Layers.DAL.DALHuesped.GetHuespedById(), UTN.Winform.AppAirBnB.Layers.DAL.DALImpuesto.GetImpuesto(), UTN.Winform.AppAirBnB.Layers.DAL.DALSeguridad.GetLogins(), UTN.Winform.AppAirBnB.Layers.DAL.DALSeguridad.GetLoginsXDataBase(), UTN.Winform.AppAirBnB.Layers.DAL.DALEncFactura.GetNextNumeroFactura(), UTN.Winform.AppAirBnB.Layers.DAL.DALReservacion.GetNextNumeroReserva(), UTN.Winform.AppAirBnB.Layers.DAL.DALReservacion.GetReserva(), UTN.Winform.AppAirBnB.Layers.DAL.DALSysUserRolDTO.GetSysUserByFilter(), UTN.Winform.AppAirBnB.Layers.DAL.DALSysUserRolDTO.GetSysUserById(), and UTN.Winform.AppAirBnB.Layers.DAL.DALTarjeta.GetTarjetaById().
ExecuteReader() [2/2]
DataSet UTN.Winform.AppAirBnB.Layers.Persistencia.IDataBase.ExecuteReader (IDbCommand pCommand, string pTabla)
ExecuteScalar()
double UTN.Winform.AppAirBnB.Layers.Persistencia.IDataBase.ExecuteScalar (IDbCommand pCommand)
Implemented in UTN.Winform.AppAirBnB.Layers.Persistencia.DataBase.
Property Documentation
_Conexion
IDbConnection UTN.Winform.AppAirBnB.Layers.Persistencia.IDataBase._Conexion get set
Definition at line 12 of file IDataBase.cs.
Referenced by UTN.Winform.AppAirBnB.Layers.Persistencia.FactoryDataBase.CreateDataBase().
 { get; set; }
The documentation for this interface was generated from the following file:
C:/Users/JorgeMario/Desktop/Proyecto Programado Cuatrimestre I 2018 v4/AppAirBnB/AppAirBnB/Layers/Persistencia/IDataBase.cs