appExamen1Sismos: UTN.Winform.Examen1.Sismos.Interfaces.IEvento Interface Reference
UTN.Winform.Examen1.Sismos.Interfaces.IEvento Interface Reference
Public Member Functions
void AgregarSismo (Sismo pSismo)
void AsignarInstitucion (IInstitucion pInstitucion)
double CalculoMagnitud ()
List< Respuesta > ObtenerCalculos ()
string ObtenerXML ()
Detailed Description
Definition at line 10 of file IEvento.cs.
Member Function Documentation
AgregarSismo()
void UTN.Winform.Examen1.Sismos.Interfaces.IEvento.AgregarSismo (Sismo pSismo)
Implemented in UTN.Winform.Examen1.Sismos.Clases.Evento.
Referenced by UTN.Winform.Examen1.Sismos.Gestores.Gestor.AgregarSismo().
AsignarInstitucion()
void UTN.Winform.Examen1.Sismos.Interfaces.IEvento.AsignarInstitucion (IInstitucion pInstitucion)
Implemented in UTN.Winform.Examen1.Sismos.Clases.Evento.
Referenced by UTN.Winform.Examen1.Sismos.Gestores.Gestor.AsignarInstitucion().
CalculoMagnitud()
double UTN.Winform.Examen1.Sismos.Interfaces.IEvento.CalculoMagnitud ()
Implemented in UTN.Winform.Examen1.Sismos.Clases.Evento.
ObtenerCalculos()
List<Respuesta> UTN.Winform.Examen1.Sismos.Interfaces.IEvento.ObtenerCalculos ()
Implemented in UTN.Winform.Examen1.Sismos.Clases.Evento.
Referenced by UTN.Winform.Examen1.Sismos.Gestores.Gestor.ObtenerCalculos().
ObtenerXML()
string UTN.Winform.Examen1.Sismos.Interfaces.IEvento.ObtenerXML ()
Implemented in UTN.Winform.Examen1.Sismos.Clases.Evento.
Referenced by UTN.Winform.Examen1.Sismos.Gestores.Gestor.ObtenerXML().
The documentation for this interface was generated from the following file:
C:/Users/JorgeMario/Documents/Visual Studio 2015/Projects/appExamen1Sismo/appExamen1Sismo/Interfaces/IEvento.cs