//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UTN.Winform.AppAirBnB.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UTN.Winform.AppAirBnB.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _256_256_82afcf99a703ccee975073f5bb0bc1b7 {
            get {
                object obj = ResourceManager.GetObject("256-256-82afcf99a703ccee975073f5bb0bc1b7", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _256_256_f4ec0361e8de14dd938e2f5da2780d32 {
            get {
                object obj = ResourceManager.GetObject("256-256-f4ec0361e8de14dd938e2f5da2780d32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _32_32_0428d53e7b6e545e0591f019a0392fd1_news {
            get {
                object obj = ResourceManager.GetObject("32-32-0428d53e7b6e545e0591f019a0392fd1-news", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _32_32_0719183b33494606b3a3d9449c6bd686_calculator {
            get {
                object obj = ResourceManager.GetObject("32-32-0719183b33494606b3a3d9449c6bd686-calculator", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _32_32_1149d4b4e6ca5d6735ced974424f1f3a_phone {
            get {
                object obj = ResourceManager.GetObject("32-32-1149d4b4e6ca5d6735ced974424f1f3a-phone", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _32_32_1b8a5ba29706cdc7c62e9b812886f19b_addressbook {
            get {
                object obj = ResourceManager.GetObject("32-32-1b8a5ba29706cdc7c62e9b812886f19b-addressbook", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _32_32_3011a484e031c9c016db2bcf62feda50_clock {
            get {
                object obj = ResourceManager.GetObject("32-32-3011a484e031c9c016db2bcf62feda50-clock", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _32_32_50025313cc1c6440651dfb884983fa83_megaphone {
            get {
                object obj = ResourceManager.GetObject("32-32-50025313cc1c6440651dfb884983fa83-megaphone", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _32_32_53df9782d9bacf85cae56004eace1272_puzzle {
            get {
                object obj = ResourceManager.GetObject("32-32-53df9782d9bacf85cae56004eace1272-puzzle", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _32_32_61c87da13517972f054915c9e7419d9f_unlike {
            get {
                object obj = ResourceManager.GetObject("32-32-61c87da13517972f054915c9e7419d9f-unlike", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _32_32_705abf03799f54ac0ee54fc08729044b_phone {
            get {
                object obj = ResourceManager.GetObject("32-32-705abf03799f54ac0ee54fc08729044b-phone", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _32_32_8144eb3f858e81ffdf6a058c1bdfe13b_calendar {
            get {
                object obj = ResourceManager.GetObject("32-32-8144eb3f858e81ffdf6a058c1bdfe13b-calendar", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _32_32_a5730ab4ecf3e9f080c982e6ca5a2002_book {
            get {
                object obj = ResourceManager.GetObject("32-32-a5730ab4ecf3e9f080c982e6ca5a2002-book", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _32_32_a7b4e7eafa76d027d523140496f14f6d_scanner {
            get {
                object obj = ResourceManager.GetObject("32-32-a7b4e7eafa76d027d523140496f14f6d-scanner", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _32_32_d412235b792cccfd81e6038865109033_printer {
            get {
                object obj = ResourceManager.GetObject("32-32-d412235b792cccfd81e6038865109033-printer", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _32_32_de0013d277ed47ae28dc3a4ddcf20ec2_cup {
            get {
                object obj = ResourceManager.GetObject("32-32-de0013d277ed47ae28dc3a4ddcf20ec2-cup", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _32_32_deba5ff0bff5a67725857f1f382c19da_like {
            get {
                object obj = ResourceManager.GetObject("32-32-deba5ff0bff5a67725857f1f382c19da-like", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _38BBC96B6 {
            get {
                object obj = ResourceManager.GetObject("38BBC96B6", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _48_48_062b562d65e87001955143c9ecc082d5_user {
            get {
                object obj = ResourceManager.GetObject("48-48-062b562d65e87001955143c9ecc082d5-user", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _48_48_10696bc060189f66efd1c9d2397cac66_bullseye {
            get {
                object obj = ResourceManager.GetObject("48-48-10696bc060189f66efd1c9d2397cac66-bullseye", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _48_48_2105a9c63eeaa7a280f82fb9c0ce8123_bulb {
            get {
                object obj = ResourceManager.GetObject("48-48-2105a9c63eeaa7a280f82fb9c0ce8123-bulb", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _48_48_25a6ad904f9df2822b07fe397f21c6fc_chart {
            get {
                object obj = ResourceManager.GetObject("48-48-25a6ad904f9df2822b07fe397f21c6fc-chart", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _48_48_2be631e7356ce10da373b8efd54fd80f_users {
            get {
                object obj = ResourceManager.GetObject("48-48-2be631e7356ce10da373b8efd54fd80f-users", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _48_48_549b73ca452c6fd477a938346bb8d9d3_chart {
            get {
                object obj = ResourceManager.GetObject("48-48-549b73ca452c6fd477a938346bb8d9d3-chart", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _48_48_5fcb865b3ad895719c10c7bfe5771fa4_pen {
            get {
                object obj = ResourceManager.GetObject("48-48-5fcb865b3ad895719c10c7bfe5771fa4-pen", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _48_48_6d18f14292ffd3debaca5d368aec541f_building {
            get {
                object obj = ResourceManager.GetObject("48-48-6d18f14292ffd3debaca5d368aec541f-building", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _48_48_7db7675b221877d6daa87d9361ba3d58_briefcase {
            get {
                object obj = ResourceManager.GetObject("48-48-7db7675b221877d6daa87d9361ba3d58-briefcase", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _48_48_89f8cc78e9d91a7a1c0d52b61d5c4f91_mobile {
            get {
                object obj = ResourceManager.GetObject("48-48-89f8cc78e9d91a7a1c0d52b61d5c4f91-mobile", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _48_48_8e6263cad82d695d5236c098e1d36714_industry {
            get {
                object obj = ResourceManager.GetObject("48-48-8e6263cad82d695d5236c098e1d36714-industry", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _48_48_b0c2ec075d62ad91d845ac99590a3e1d_presentation {
            get {
                object obj = ResourceManager.GetObject("48-48-b0c2ec075d62ad91d845ac99590a3e1d-presentation", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _48_48_f217a070ae265c06a3473771c368ac82_card {
            get {
                object obj = ResourceManager.GetObject("48-48-f217a070ae265c06a3473771c368ac82-card", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap a {
            get {
                object obj = ResourceManager.GetObject("a", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap airbnb_logo_ventana {
            get {
                object obj = ResourceManager.GetObject("airbnb-logo-ventana", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap airbnb_logo_white_image_green_background_93709650 {
            get {
                object obj = ResourceManager.GetObject("airbnb-logo-white-image-green-background-93709650", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap hotel {
            get {
                object obj = ResourceManager.GetObject("hotel", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap SbeKd2H {
            get {
                object obj = ResourceManager.GetObject("SbeKd2H", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Sin_título_115 {
            get {
                object obj = ResourceManager.GetObject("Sin-título-115", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap vista_wood_node_wallpapers_3527_1600x1200 {
            get {
                object obj = ResourceManager.GetObject("vista-wood-node-wallpapers_3527_1600x1200", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
